TVTower/TVTower

Spielanleitung.RAW.txt, Spielanleitung.txt, res/database/Default/database_ads.xml
- Database_ads.xml 0,5 zu 0,05 korrigiert
=> - Spielanleitung aktualisiert

source/Dig/base.gfx.gui.bmx
Linked lists are very expensive in this case.
=> [Performance] GUI: Using Array to replace reversed lists

README.md
Linux/Mac/Linux durch Linux/Mac/Windows ersetzen.
=> Replaced misspell

res/database/Default/user/therob.xml
=> Typos fixed in "Kommissar Wirsch" (several episodes), MIR & ISS

res/database/Default/database_programmes.xml
Last 1/3 fix for #98 and some additional typos. DE/EN.
=> Several typos fixed

res/database/Default/database_programmes.xml
Reminder for self: letzter Film: Hack the Fog
Anmerkung: Der Titel: "Die Streichholzhammerbowle" existierte 2 mal - aber mit unterschiedlichen Drehjahren und Werten. Ich hab aus einem einen fiktiven Nachfolger gemacht, wenns für dich ok ist. :)
=> Typo check - ca. 1/5 aller Filme geprüft.

source/common.misc.plannerlist.programmelist.bmx
Wenn man nur die Konstante von 8 auf 15 ändert, hat man zwar einen ähnlichen Effekt, aber bei wenigen Filmen sieht es nicht so schän aus.
Mit dieser Änderung ändert sich die Anzahl der Slots mit der Anzahl verfügbarer Filme. Dadurch müssen aber die Buttons neu gemalt werden, da sie sonst an der falschen Stelle erscheinen könnten.
Ich kenne die Programmiersprache und Konzepte noch überhaupt nicht. Z.B. müsste an einem nicht mehr verwendeten GUI-Element (null-Setzen des Buttons) nicht noch eine dispose-Methode aufgerufen werden, um kein Speicherleck zu verursachen etc.
An zwei Stellen, habe ich Ersetzungen vorgenommen, weil es mir schien, als ob das falsche Sprite/die falsche Methode referenziert wurde.
=> #148 dynamic tape count per page

source/game.screen.stationmap.bmx
Allow finalizing the station placement using arrow keys by pressing
space.
=> #134 place station using space

source/game.roomhandler.studio.bmx
Die Aktion für das Starten einer Produktion wird auch im Review-Dialogtyp angeboten - falls eine fertige Konzeption vorliegt.
=> #97 start production after review

res/lang/lang_de.txt, res/lang/lang_en.txt, source/game.production.productionmanager.bmx, source/game.roomhandler.studio.bmx
Erlaube nicht nur alle vorbereiteten Folgen einer Serie zu produzieren, sondern auch eine einzelne.
=> #142 allow production of single episodes

source/main.bmx
Ich habe mal die für mich relevantesten Tastenkürzel umgesetzt.
* Navigation in die wichtigsten Räume ohne über die Auswahl im Fahrstuhl gehen zu müssen.
* Geschwindigkeitslevel
* Schnellvorlauf
* Hilfe
* Raum verlassen
Die Kürzel für die Navigation weichen von der Dev-Variante etwas ab. Das ist Absicht, denn ich glaube für ein reguläres Spiel sollte sich der Spieler nicht immer wieder Fragen stellen müssen, welche der Doppelbelegungen nun mit (linkem ode rechtem) shift oder ctrl zu wählen war.
Für den Schnellvorlauf wäre mir wichtig, dass die Proportionen der verschiedenen Geschwindigkeiten stimmen (Fairness gegenüber der KI). Ich habe die mal aus dem Dev-Code übernommen. Hier muss ggf. noch die Prüfung rein, dass es kein Mehrplayer-Spiel ist.
Eine mögliche Verbesserung wäre, die …
=> regular game hotkeys

source/main.bmx
F1 zeigt spezifische Hilfe falls vorhanden und ansonsten die generelle Spielanleitung.
=> F1 auch für spezifische Hilfethemen

source/game.screen.supermarket.production.bmx
Ich habe mich mal an einer Implementierung für die Darstellersortierung (#123) versucht. Prinzipiell funktioniert es, könnte natürlich noch viel schöner sein.
Aktuell kann man zwischen Namensortierung und effektiver Erfahrung umschalten. Ich habe mich mit dem Berechnungsschema noch nicht auseinandergesetzt, aber Erfahrung ist noch nicht gleich Eignung (viel Kraft, wenn Kraft benötigt wird). Die einfachste Erweiterung würde wohl sein, direkt nach den Einzelwerten sortieren zu können (Aussehen, Charisma,...) ohne die für die Filmqualität relevante Gesamtwertung zu bekommen (es soll ja nicht zu einfach werden).
Ich wollte nur mal nachfragen, ob ich in die richtige Richtung laufe. Das Hovern/Auswählen, wie es bei der Nachrichten-/Werbesortierung implementiert ist, hatte ich kurz versucht, war …
=> Prototyp Darstellersortierung im Supermarkt

source/game.ingameinterface.bmx
Zeige Zuschauerinformation für den Kanal, dessen Programminformation gezeigt wird.
Closes #193
=> richtige Zuschauerzahl/Einschaltquote anzeigen

source/game.screen.supermarket.production.bmx
Bei der Sortierung nach Preis standen die Amateure ganz hinten.
=> [CustomProduction] fix fee sort order for amateurs

source/common.misc.plannerlist.base.bmx, source/common.misc.plannerlist.programmelist.bmx
Hover links anzeigen. Texte für Filmsortierung ergänzt.
closes #209
=> Position der Sortier-Hinweise

source/main.bmx
Bei der Optimierung ist ein permanentes Debuggen mit reingekommen.
=> Fix: no permanent debug stats

source/game.stationmap.bmx
=> Initiale Satelliten-Qualität begrenzen

source/game.screen.stationmap.bmx
Teilimplementierung für #114. Es fehlt noch die Nachricht, dass ein Vertrag auszulaufen droht.
=> Vertragsverlängerung standardmäßig angeschaltet

source/game.screen.programmeplanner.bmx
Home/Pos1 um nach Blättern im Programmplaner wieder zum aktuellen Tag zu gelangen.
=> schnelle Navigation zum aktuellen Tag

res/lang/rooms/rooms_de.txt, res/lang/rooms/rooms_en.txt, res/lang/rooms/rooms_es.txt, res/lang/rooms/rooms_fr.txt, res/lang/rooms/rooms_pt-br.txt, res/lang/rooms/rooms_tr.txt, source/game.room.base.bmx, source/game.room.roomdoor.tooltip.bmx, source/game.roomhandler.betty.bmx
Betty arbeitet nicht rund um die Uhr.
=> Bürozeiten Betty

res/database/Default/database_programmes.xml
original titles added for content with imdb_id
some imdb_ids added, some imdb_id duplicates resolved
cleanup and fixes of some original_titles
release year fix for 'Die Feuerzangenbowle'
This PR contains all changes done in https://github.com/TVTower/TVTower/pull/335 bit does not have an initial commit containing an unneccesary merge from TVTower -> My Fork.
=> Original Titles added and cleanup

res/database/Default/database.xml, res/database/Default/database_ads.xml, res/database/Default/database_news.xml, res/database/Default/database_people.xml, res/database/Default/database_programmes.xml, res/database/Default/database_scripts.xml, res/database/Default/user/jorgaeff.xml, res/database/Default/user/kieferer.xml, res/database/Default/user/nichtdiebetty.xml, res/database/Default/user/ronny.xml, res/database/Default/user/sjaele.xml, res/database/Default/user/speedminister.xml, res/database/Default/user/therob.xml
Mit diesem PR werden ein paar Formatprobleme der aktuellen XML-Dateien behoben. 
* remove  BOM
* fix property typos, use existing tag names
* fix xml format typos
* fix links to follow up news
=> clean up database files

docs/manual_de.md, source/main.bmx
Vorgeschlagene vereinfachte Tastenkürzel für Raumplan und Supermarkt wurden zu den Dev-Keys hinzugefügt.Dokumentation angepasst.
(siehe #353, #186)
=> Key-Bindings

source/common.misc.templatevariables.bmx, source/game.broadcastmaterialsource.base.bmx, source/game.gameinformation.base.bmx, source/game.gameinformation.bmx, source/game.production.script.bmx, source/game.programme.newsevent.bmx, source/game.world.worldtime.bmx
=> [Misc] allow time override for placeholder replacement

res/lang/gen_settings/genSettings_de.txt, res/lang/gen_settings/genSettings_en.txt, res/lang/gen_settings/genSettings_es.txt, res/lang/gen_settings/genSettings_fr.txt, res/lang/gen_settings/genSettings_pt-br.txt, res/lang/gen_settings/genSettings_tr.txt, source/game.game.bmx, source/game.gamerules.bmx, source/game.screen.menu.bmx
=> Option, um das Spiel ohne Kreditaufnahme zu starten

res/database/Default/database_programmes.xml
TED benötigt Flag für das Beibehalten der Ausstrahlungszeitbegrenzung
=> Ausstrahlungzeit TED

res/database/Default/user/kasi.xml
* copy data from
https://www.gamezworld.de/phpforum/viewtopic.php?id=13893 (post 11)
* fix syntax errors
* proof reading
* partial translation
* deactivate some scripts
* modify some flags/broadcast limits etc.
* main modifications are documented as comments before the script
closes #373
=> [DB] add script suggestions by kasi

source/game.ai.base.bmx
Ich habe gestern viel Zeit verbraten...
=> Konfiguriertes KI-Script muss auch verwendet werden

source/main.bmx
In diesem Vorschlag wird die Spielstandbackupdatei in jedem Fall erzeugt, wenn sich die Save-Versionen unterscheiden. Man könnte noch einen Konfigurationsschlüssel einführen, mit dem das Backup ausgeschaltet werden könnte.
Closes #394
=> [Savegame] create backup

res/database/Default/user/nichtdiebetty.xml, res/database/Default/user/rumpelfreddy.xml, res/database/Default/user/speedminister.xml
Ich habe soweit möglich das fictional-Flag gesetzt und Land und Geschlecht ergänzt. Ich habe die Länderliste aus der Dokumentation dafür nicht erweitert. Zunächst sind die einzelnen Dateien in einzelnen Commits angepasst.
=> add fictional flag to persons

source/game.screen.supermarket.production.bmx
* Keine Laien bei "Alle Berufe"
* Workaround, damit bei Filterwechsel die richtige Sortierung verwendet wird
closes #406
=> Auswahl Besetzung - Filter und Sortierung verbessern

source/game.production.script.bmx, source/game.programme.programmelicence.bmx
Die Minimum-Berechnung lieferte das falsche Ergebnis, wenn die erste Folge ein Limit hatte, aber die zweite nicht. Falls für Serien das Minimum -1 ist (aber trotzdem ein Limit vorhanden ist), wird für den Header nur ein generischer Hinweis angezeigt.
Ich lasse den PR zunächst als Draft, weil dieselbe Problematik auch für Drehbücher existiert. Hier wird aktuell für das Gesamtdrehbuch nur ein dort definiertes Limit angezeigt
* Head Limit 1, aber alle Folgen definieren ein anderes Limit - Limit 1 wird angezeigt
* Head ohne Limit, aber Folgen defnieren eins - kein Limit wird angezeigt
Die Frage wäre, wieviel Aufwand man da reinstecken möchte...
=> improve datasheet limit warning

source/game.roomhandler.news.bmx
Aktuell kann man Nachrichten, die man sich nicht leisten kann trotzdem in Liste der zu sendenden Nachrichten droppen. Es kommt dann zwar eine Anzeige, dass zu wenig Geld vorhanden ist, die Nachricht ist dennoch zunächst in der rechten Liste. Erst wenn man das Studio verlässt und wieder reingeht, sieht man, dass die Aktion nicht erfolgreich war.
Für den Verboten-Marker am Cursor (Hover) wurde auch nur der Owner geprüft, nicht aber ob die Nachrichten bezahlt waren (Owner ist für alle Listeneinträge der Spieler).
* Korrektur Cursor
* Veto für Drop, wenn man sich die Nachricht nicht leisten kann
=> [News] Behandlung zu teurer Nachrichten

source/game.game.bmx, source/game.gamerules.bmx, source/game.player.base.bmx, source/game.player.bmx, source/gamefunctions_debug.bmx
=> Fix: [NewsAgency] Unsubscribe genre on start now for free

source/common.misc.templatevariables.bmx
=> Fix: [Dig] Localization of "empty" locales but set placeholders

source/game.programme.newsevent.bmx
=> Triggerausführung bei Startnachrichten

source/game.award.base.bmx, source/gamefunctions_debug.bmx
Ich habe jetzt die Awardklassen ein wenig ueberarbeitet und die Logik darin (hoffentlich) vereinheitlicht.
Auch gibt es nun in der AwardCollection entsprechende Hilfsmethoden um dann per "debug-screen" Aktionen ausfuehren zu koennen (vorher fand das alles in `UpdateAwards()` statt).
Wenn ich dann den Debugscreen erweitert habe (derzeit nur "display" noch keine Interaktion drin), wird sich sicher noch der eine oder andere nun "hinzugewonnene" Bug bemerkbar machen ;)
=> Overhaul of awards, API preparation and award archiving

source/game.stationmap.bmx
=> Fix stationmap threadsafety

source/Dig/base.util.event.bmx
REMOVE afterwards (or disable/keep only for ?debug builds)
=> Added debug logs for not "threadsafe"-marked calls

res/ai/CommonAI/AIEngine.lua, res/ai/DefaultAIPlayer/DefaultAIPlayer.lua, res/ai/DefaultAIPlayer/TaskAdAgency.lua, res/ai/DefaultAIPlayer/TaskRoomBoard.lua, res/ai/DefaultAIPlayer/TaskSchedule.lua, res/ai/DefaultAIPlayer/TaskStationMap.lua, source/game.ai.bmx, source/gamefunctions_debug.bmx
* prevent segmentation faults
* log game time in AI log
* fix access to non-existing log function
* remove kiMsg and infoMsg
=> [AI] cleanup

res/lang/bossbetty/bossbetty_de.txt, res/lang/bossbetty/bossbetty_en.txt, res/lang/bossbetty/bossbetty_es.txt, res/lang/bossbetty/bossbetty_fr.txt, res/lang/bossbetty/bossbetty_pt-br.txt, res/lang/bossbetty/bossbetty_tr.txt, source/main.bmx
=> Sammy: Spieler auch informieren, wenn Preis gar nicht vergeben wurde

res/ai/DefaultAIPlayer/TaskStationMap.lua, source/Dig/base.gfx.imagehelper.bmx, source/Dig/base.gfx.sprite.bmx, source/Dig/base.util.vector.bmx, source/game.ai.bmx, source/game.broadcast.audienceresult.bmx, source/game.broadcast.base.bmx, source/game.broadcast.broadcaststatistic.bmx, source/game.game.bmx, source/game.network.networkhelper.bmx, source/game.screen.stationmap.bmx, source/game.stationmap.bmx, source/main.bmx
1000 * AscertainPlayerMarkets() (auf meinem PC):
release: 200ms
debug: 750ms
Erster Commit (AddMarket.Set()-Calls eingespart) :
release: 198ms
debug:   735ms
also noch nicht sonderlich viel ... Ersparnis (aber jeder "Method-Call" sorgt bei Debug ja fuer ... Debugframes ... da sind Einsparungen immer gut.
=> Optimize StationMap/Audience calculation

source/main.bmx
Statt beim Tastenkürzel "Gehe zu Studio" immer das erste zu nehmen, wir das erste nicht blockierte angesteuert.
=> Gehe zu Studio

source/game.broadcast.audience.bmx, source/game.debug.screen.page.publicimages.bmx
=> [Misc] Correct "WeightedAverage()"

res/lang/rooms/rooms_de.txt, res/lang/rooms/rooms_en.txt, res/lang/rooms/rooms_es.txt, res/lang/rooms/rooms_fr.txt, res/lang/rooms/rooms_pt-br.txt, res/lang/rooms/rooms_tr.txt, source/game.gameconstants.bmx, source/game.network.networkhelper.bmx, source/game.room.base.bmx, source/game.roomagency.bmx, source/game.roomhandler.adagency.bmx, source/game.roomhandler.base.bmx, source/game.roomhandler.roomagency.bmx, source/game.roomhandler.studio.bmx
=> [Rooms] Allow blocking rental changes (cancel, begin)

res/ai/DefaultAIPlayer/TaskAdAgency.lua, res/ai/DefaultAIPlayer/TaskMovieDistributor.lua, res/ai/DefaultAIPlayer/TaskSchedule.lua, source/game.ai.bmx, source/game.broadcast.audience.bmx, source/game.broadcast.base.bmx, source/game.programme.adcontract.bmx, source/game.programme.programmelicence.bmx
=> Fix: [AI] Temporarily replace broken float-params

source/game.debug.screen.page.playerbroadcasts.bmx
Hover für Filme und Werbung. Verbesserter Umbruch des Kofferinhalts.
=> Debug-Screen Programmplan

res/ai/CommonAI/AIEngine.lua, source/game.debug.screen.page.playerfinancials.bmx
In der Taskübersicht für die Finanzen sollten auch die täglichen Fixkosten angezeigt werden.
=> Fixkosten Debugansicht Finanzen

source/main.bmx
=> Cheat-Kommandos sind nur zusammen mit den Dev-Keys aktiv

docs/manual_de.md, docs/manual_en.md
=> Spielanleitung bezüglich Tastenkürzel überarbeitet

docs/manual_de.md, docs/manual_en.md
Mit "0" kann man ein Spiel im normalen Modus pausieren.
closes #606
=> Aktualisierung Handbuch

source/Dig/base.util.luaengine.bmx, source/game.ai.base.bmx, source/game.ai.bmx
=> Fix: [AI] Fixed AI.ReloadScript()

source/game.screen.stationmap.bmx
=> [Office] deferred reaction to station map changes stationmap screen

source/main.bmx
Da sich die Struktur der Events geändert hat, kann es beim Laden von alten Spielständen zu Segmentation Faults kommen. Die Eventliste wird einfach komplett geleert.
=> Spielstand: alte AIEvents löschen

source/Dig/base.util.helper.bmx, source/game.game.bmx, source/game.roomhandler.movieagency.bmx, source/main.bmx
=> [Movieagency] Shuffle initial offer pool

source/game.ai.bmx, source/game.player.programmeplan.bmx, source/game.screen.programmeplanner.bmx
=> Fix: [Programmeplan] Corrected IsModifiableSlot()

config/rooms.xml, res/ai/CommonAI/AIEngine.lua, source/Dig/base.util.xmlhelper.libxml.bmx, source/Dig/base.util.xmlhelper.mxml.bmx, source/game.achievements.base.bmx, source/game.ai.bmx, source/game.building.base.bmx, source/game.building.bmx, source/game.figure.base.bmx, source/game.figure.bmx, source/game.figure.customfigures.bmx, source/game.game.bmx, source/game.gameconstants.bmx, source/game.gameobject.bmx, source/game.misc.roomboardsign.bmx, source/game.player.bmx, source/game.programme.adcontract.bmx, source/game.programmeproducer.bmx, source/game.programmeproducer.sport.bmx, source/game.registry.loaders.bmx, source/game.room.roomdoor.base.bmx, source/game.room.roomdoor.bmx, source/main.bmx
=> [AI] Add ability to use elevatorplan

res/database/Default/database_scripts.xml, res/database/Default/user/kasi.xml, res/database/Default/user/kieferer.xml, res/database/Default/user/therob.xml
Drehbuchvorlagen mit höherem Potential benötigen gegebenenfalls auch größere Studios.
closes #199
=> Drehbuchvorlagen: benötigte Studiogröße

config/DEV.xml, config/gamesettings/default.xml, res/ai/DefaultAIPlayer/TaskSchedule.lua, res/database/Default/user/therob.xml, source/game.broadcastmaterial.news.bmx, source/game.game.bmx, source/game.gamerules.bmx, source/game.player.boss.bmx, source/game.player.difficulty.bmx, source/game.player.finance.bmx, source/game.production.script.base.bmx, source/game.programme.adcontract.bmx, source/game.programme.programmedata.bmx, source/game.programme.programmelicence.bmx, source/game.room.base.bmx, source/game.roomagency.bmx, source/game.screen.stationmap.bmx, source/game.stationmap.bmx, source/main.bmx
Im Moment sind die Werte für unterschiedliche Schwierigkeitsgrade fest im Code hinterlegt und andere, die auch pro Schwierigkeitsgrad unterschiedlich sein könnten, sind in den Regeln oder in der DEV.xml "global" hinterlegt.
Dieser PR soll als Diskussionsgrundlage dafür dienen, welche Werte wo definiert sein sollten und wie die Syntax aussehen könnte.
=> Konsolidierung GameRules, Difficulties, DEV.xml

source/Dig/base.util.mersenne.bmx
Entfernen der ursprünglichen Versionrückgängig gemacht. Wird für Arrays mit "geringer Kollisionswahrscheinlichkeit" verwendet.
=> RandRangeArray

source/Dig/base.util.string.bmx, source/common.misc.templatevariables.bmx, source/game.achievements.bmx, source/game.broadcastmaterialsource.base.bmx, source/game.database.bmx, source/game.production.script.bmx, source/game.programme.newsevent.bmx, source/game.programme.programmedata.bmx
Allows "nested" variables like `${MAIN${variant}}` which resolves `${variant}` first and allows to use this variable for others too. `${MAIN${variant}}` + `${CHILD${variant}}` both use the same "variant" then.
=> [Misc] Added ${var} support

res/ai/DefaultAIPlayer/TaskStationMap.lua, source/game.broadcastmaterial.news.bmx, source/game.player.finance.bmx, source/game.programme.adcontract.bmx, source/game.screen.stationmap.bmx, source/game.stationmap.bmx, source/game.world.worldtime.bmx
=> Fix: [Stationmap] Do not use Longs for exposed Lua functions

res/database/Default/user/ronny.xml, source/game.programme.programmedata.bmx, source/game.programme.programmedata.specials.bmx, source/game.programmeproducer.sport.bmx
=> Modifier notLive für Max-Topicality

res/database/Default/user/kasi.xml, res/database/Default/user/ronny.xml, res/database/Default/user/therob.xml
Diskussionsgrundlage für Kultursendungen. Wenn Modifier ausgewertet würden, könnte man noch an der Erholungsgeschwindigkeit und dem Altern schrauben. (Prototyp für die Auswertung habe ich. Da würden dann aber keine Werte gewürfelt werden, sondern die Werte für alle Drehbücher verwendet werden.)
=> Kultursendungen

source/game.game.bmx, source/game.screen.menu.bmx
Wenn man die Spieler wechselt, sollte auch die Farbe gewechselt werden.
=> Spielerwechsel

source/Dig/base.gfx.gui.bmx
=> Segmentation Fault bei Sortierung

source/game.player.programmecollection.bmx
=> KI-Nachrichten Segmentation Fault

source/game.roomhandler.scriptagency.bmx, source/game.screen.programmeplanner.bmx
=> Defer GUI-Refresh of ScriptAgency/Programmeplan to main thread

source/Dig/base.gfx.bitmapfont.bmx
=> [Dig] Fix Bitmapfont-Drawbox last line

source/game.building.bmx, source/game.game.bmx, source/game.gameconfig.bmx, source/game.world.bmx, source/main.bmx
Wetter, Ton, Nachrichten für erfolgreiche Werbung deaktivieren, Fernseher aus, nicht der Figur folgen.
closes #724
=> Beobachtungsmodus für hohe Geschwindigkeiten

source/game.screen.menu.bmx
Beim Start lassen sich nun per Knopfdruck die KI-Spieler mit zufälligen Werten belegen
closes #642
=> Randomisierung Spieler

source/main.bmx
=> [Misc] Allow subdirectories in savegame names.

source/game.building.elevator.bmx
see #471 
Die hier gemachten Änderungen helfen schon, die Zeit für das Betreten/Verlassen des Fahrstuhl von 70ms auf 25ms beim Vorspulen zu reduzieren. Durch die mehrfachen Update-Versuche entfallen effektiv Updatezyklen, die sonst nötig gewesen wären.
=> Beschleunigung Fahrstuhl

source/game.mission.bmx, source/game.mission.highscore.bmx, source/main.bmx
=> nosave-Annotation

source/game.gamerules.bmx, source/game.screen.menu.bmx, source/main.bmx
Moderate, fest hinterlegte Werteabweichung bei Aufträgen.
closes #749
=> Zufallswerte für Lizenzen bei Aufträgen

source/game.world.bmx, source/game.world.worldtime.bmx
=> [Misc] Optimize day phase calculation

source/game.production.productionmanager.bmx
Das ursprüngliche Studio der Vorproduktion kann in der Zwischenzeit abgestoßen worden sein. Vor der Ausstrahlung muss geprüft werden, dass der Raum ein Studio ist und dem Spieler gehört.
=> Richtiges Studio für Live-Ausstrahlung

source/game.screen.supermarket.production.bmx
Im Forum gab es ja die Meldung, dass die Produktionsfirma plötzlich nicht mehr auswählbar ist. Ich konnte das Problem in dieser Form zwar nicht reproduzieren, aber die aktuelle Aktivierung/Deaktivierung kam mir dennoch etwas seltsam vor und es gab weitere Bugs:
* Es sind ja nicht immer alle Slider sichtbar. Wenn man zunächst ein Konzept (z.B. Show) mit 4 Slidern bearbeitet und dann auf ein Konzept mit 6 umschaltet, sind die beiden hinzugekommenen Slider ggf. gar nicht bearbeitbar
* Wenn man den Supermarkt während des Bearbeitens mit Q verlässt und wieder betritt, wird "die falsche Firma" angezeigt (keine)
* Wenn man zwischen einem fertigen Konzept und einen "leeren" wechselt, wird bei dem fertigen zwar die richtige Gesamtanzahl der vergebenen Fokuspunkte angezeigt, aber eben nicht, welche …
=> Aktivierung Produktionsfirma Supermarkt

source/game.ingameinterface.bmx
Entfernen der vorhandenen führenden Leerzeichen im Interfacebereich.
see #791
=> Konsistenz % mit/ohne führendem Leerzeichen

res/lang/bossbetty/bossbetty_fr.txt, source/game.player.boss.bmx
Beim Durchprobieren der Sprachen ist mir aufgefallen, dass die Währungen tatsächlich jetzt schon inkonsistent sind!
closes #804
=> Trennzeichen bei Kreditrückzahlung

source/game.programmeproducer.bmx, source/game.roomhandler.scriptagency.bmx
closes #790
Die 15 Stunden Vorlauf sind Diskussionsgrundlage. (Zeit bis Austausch und Vorproduktionszeit berücksichtigen)
=> keine Live-Drehbücher mit abgelaufenem Datum anbieten

source/game.ingameinterface.bmx
Der Code hat die richtige Position berechnet gehabt, aber dann nicht zugewiesen...
closes #809
=> Familienmitglieder sollten nicht gleichzeitig auf selbem Platz sitzen

source/game.world.bmx
=> Wolkengeschwindigkeit bei Spielstart

source/game.broadcastmaterial.programme.bmx, source/game.programme.programmedata.bmx, source/game.programme.programmelicence.bmx
Prototyp ist implementiert. Imageverlust und Schwierigkeitslevel fehlen noch.
see #803
=> Einnahmen für Call-In

source/game.programme.adcontract.bmx
=> Werbung mit Fixpreis

source/game.screen.programmeplanner.bmx
=> Fix: [Programmeplan] Avoid programme/ad hover with lists open

source/game.debug.screen.page.adagency.bmx, source/game.player.programmecollection.bmx, source/game.roomhandler.adagency.bmx
=> Fix: [Adagency] Corrected "in suitcase" count

source/game.roomhandler.movieagency.bmx
Adjusted behaviour similar to adagency in PR #870
Closes #871
=> Fix: [Movieagency] Corrected drop on full suitcase

source/game.ai.bmx, source/game.award.base.bmx, source/game.award.customproduction.bmx, source/game.broadcast.base.bmx, source/game.broadcastmaterial.advertisement.bmx, source/game.broadcastmaterial.programme.bmx, source/game.database.bmx, source/game.game.bmx, source/game.newsagency.bmx, source/game.newsagency.sports.bmx, source/game.newsagency.sports.icehockey.bmx, source/game.newsagency.sports.soccer.bmx, source/game.person.base.bmx, source/game.person.bmx, source/game.player.programmeplan.bmx, source/game.production.bmx, source/game.production.script.bmx, source/game.programme.adcontract.bmx, source/game.programme.programmedata.bmx, source/game.screen.financials.bmx, source/game.screen.statistics.bmx, source/game.stationmap.bmx, source/game.world.worldtime.bmx, source/main.bmx, unittests/test.visual.world.weather.bmx
closes #820
direkt die MakeRealTime-Methode verwenden. Zu erwähnen ist aber, dass mit der Änderung bei Startjahr 1985 die 10-jährige Babsi Angora in der Besetzungsauswahl auftaucht - und zwar zweimal. Bitte also genauer auf diese vermeintlich kleine Anpassung schauen.
=> Geburtstagsumrechnung

source/game.award.customproduction.bmx, source/game.broadcastmaterial.programme.bmx, source/game.pressuregroup.bmx, source/game.production.bmx, source/game.production.productionconcept.bmx, source/game.programmeproducer.bmx, source/game.publicimage.bmx
* prints entfernt
* für Producer nicht die gesamte Entwicklungs-Debug-Information ausgeben
=> Logausgaben aufräumen

source/common.misc.gamegui.bmx, source/game.menu.escapemenu.bmx
=> Fix: [Misc] Reset cursor in modal windows

source/game.programmeproducer.sport.bmx
=> Fix: [Misc] Sports programme: Do not clone series id to episodes

source/game.database.bmx
Erster Entwurf für die Datenbankkorrektur. Ähnliche Beschränkungen im Supermarkt sind ein anderes Thema.
Bei einigen nichtfiktionalen Persionen wird gewarnt, dass nicht korrigiert wurde.
see #850
=> Bei Datenbank-Alterskorrektur Genre und Beruf berücksichtigen

source/game.programme.programmedata.bmx, source/game.screen.supermarket.production.bmx
Es ist zwar nicht mehr viel Platz...
closes #835
=> Rollenname bei Besetzungsauswahl im Supermarkt anzeigen

source/Dig/base.util.event.bmx, source/game.production.productionconcept.bmx, source/game.screen.supermarket.production.bmx
=> Fix: [CustomProduction] Defer Productionconcept-events (avoid child-thread-gui-interaction)

source/game.newsagency.base.bmx
Weil das Level schon bei Erreichen des MaxLevels und nicht erst bei der eigentlichen Explosion zurückgesetzt wird, interessiert sich die KI in der eigentlich heißen Phase nicht mehr für den Raumplan.
=> KI wird nicht korrekt über Terrorlevel informiert

res/database/Default/database_programmes.xml, res/database/Default/user/rumpelfreddy.xml
"Mein wunderbarer Waschsalon", "Chronik eines angekündigten Todes", "Tucker", what's a MadTV homage without these classics. `;)`
This PR adds a lot of non-fictional movies and series, from myself, from forum users, and a first batch of Stukov's (he has a lot of stuff but not in an immediately usable state).
=> Add a lot new programme entries

source/game.registry.loaders.bmx
Aufgrund von #925 habe ich mal den Loader mit Exceptions versehen, wenn unbekannte Werte auftauchen. Mit dem aktuellen Stand fliegen keine Exceptions.
Die Frage wäre, wie man hier grundsätzlich vorgehen möchte.
* Ignorieren von Fehlern ist unschön, da man versehentliche Konfigurationsfehler ggf. nicht bemerkt.
* Exception werfen ist am saubersten, führt aber zu Spielabbruch, unschön für den "Produktivbetrieb".
* print/Logging werden ggf. auch einfach ignoriert (Fehler-Log wäre aber wahrscheinlich der beste Kompromiss)
=> Härten des Modifier-Einlesen

res/database/Default/user/scr0llbaer.xml
This one adds my own `scr0llbaer.xml` user file for the fictional entries, mainly scripts.
=> Add new scr0llbaer.xml with fictional data entries

source/Dig/base.gfx.gui.button.bmx, source/game.screen.supermarket.production.bmx
=> Fix: [Dig] Correct theme changes for disabled buttons

source/game.newsagency.base.bmx, source/game.newsagency.bmx
Es muss nicht für jedes Match eine Sportnachricht erstellt werden.
=> Weniger Sportnachrichten

res/database/Default/database_people.xml, res/database/Default/database_programmes.xml, res/database/Default/database_programmes_fictional.xml, res/database/Default/user/scr0llbaer.xml
As we talked about it, I'm reactivating my live scripts again.
I wasn't / am not so happy with those though, but gradually improving, by creating even more of them. `:-]`
This kind of "diversification" alleviates some things I didn't like about them.
Adopting the "Dynamit - das Magazin" for the showbiz format, and changing the existing programme (which didn't make much sense without some special topic) into a special about Lady Di, what you think @GWRon ?
=> reactivate live scripts, some improvements

source/game.programme.programmedata.bmx
Minimaler Vorschlag für größeren Einfluss der Ausstrahlungshäufigkeit. 
see #784
=> Berechnung maximale Aktualität

source/game.production.script.bmx, source/game.roomhandler.scriptagency.bmx, source/gamefunctions_debug.bmx
=> Fix: [Scriptagency] Corrected "good script" prevention and caches

res/database/Default/user/cujo.xml
Ich habe einige kleine Änderungen vorgenommen, die von nittka vorgeschlagen wurden.
Größere Änderungen will ich im Moment nicht machen, da ich mich dazu neu einlesen müsste (Drehbücher). Ich denke, das File ist jetzt in einem Zustand, dass es in der nächsten Version ausgeliefert werden kann.
=> Neue Version meiner Daten

source/game.roomhandler.movieagency.bmx
* tägliche Prüfung der Filter
* Filterwerte anhand der Anzahl der Filme bestimmt
* aktuell zwei Varianten; wenn alle mehr als 20 Filme haben, wird mehr als "Ramsch" eingestuft
closes #947
=> Dynamischere Filter für die Filmagentur

source/game.newsagency.base.bmx
Ich habe den Ausschluss aufgrund des Produkts ergänzt, da in den Nachrichten aktuell explizit von Film die Rede ist. Nachrichten über Fernsehfilme könnte es ja ruhig auch geben.
see #949
=> Bei Filmnachrichten nur Filme berücksichtigen

source/game.world.weathereffects.bmx
They used TData instead of specific data containers - which made it rather expensive (especially for snow flakes...)
For snow this saved ~25-30.000 allocs/second (depending on update/fps rate)
=> [Misc] Optimize weather effects (Report: Dalli)

source/game.screen.achievements.bmx, source/game.screen.supermarket.production.bmx
=> Fix: [Supermarket] Defer GUI reaction on cast rearrangement. Report: @scr0llbaer9000

source/Dig/base.gfx.bitmapfont.bmx, source/game.gameconstants.bmx
=> Fix: [Misc] Change currency sign space to non-breaking

source/game.roomhandler.roomagency.bmx
Wenn ein Raum nicht gemietet werden kann (noch vermietet oder Provision zu hoch), wird der Mauszeiger durchgestrichen. Ein Anklicken des Raums hat keine Wirkung.
closes #975 
Den Text "x €/Spieltag" ->"x €/Tag" habe ich noch nicht angepasst und würde es aktuell so lassen. Insb. möchte ich kein Lehrzeichen vor/nach dem Schrägstrich einführen, da es sonst wieder zu ungewünschten Zeilenumbrüchen kommen könnte.
=> Raummakler: deutlicher Hinweis, wenn Mieten nicht möglich

source/game.person.base.bmx
Für fiktionale Personen kann ein Alter bei Spielstart statt Geburtsjahr angegeben werden. Das Jahr wird dafür als negative Zahl in der Datenbank angegeben (birthday="-27" entspricht Alter 27; birthday="-27-05-13" entspricht 13.5. vor 27 Jahren).
Zu beachten ist, dass für viele der fiktionalen Personen, für die dieses Feature verwendet werden soll, auch Programme mit aktuell festem Veröffentlichungsdatum relativ gemacht werden müssen, da sonst die automatische Alterskorrektur greift.
closes #970
=> relatives Geburtsjahr erlauben

source/game.programme.programmelicence.bmx
=> Land+Jahr - dynamisch mehr Platz; report scr0llbaer

res/lang/programme/programme_de.txt, res/lang/programme/programme_en.txt, res/lang/programme/programme_es.txt, res/lang/programme/programme_fr.txt, res/lang/programme/programme_pt-br.txt, res/lang/programme/programme_tr.txt, source/common.misc.plannerlist.programmelist.bmx, source/game.programme.programmelicence.bmx
=> Sortierung nach Anzahl Wiederholungen im Programmplan; report Dengstar

source/game.roomhandler.movieagency.bmx
Durch die Erweiterung der Datenbankeinträge gibt es vergleichsweise mehr Angebot im Erotik-Bereich. Das führt im Spiel dazu, dass in der Ramschkiste z.T. 5 Angebote stehen. Das ist im Verhältnis zu den anderen verfügbaren Kategorien zu viel.
Mit der vorgeschlagenen Änderung wird die Anzahl der Erotikangebote für die Ramschkiste eingeschränkt.
=> Weniger Erotikramsch anbieten

source/main.bmx
Am ersten Tag wird häufiger als alle 3 Stunden aktualisiert.
=> Für Startprogramm häufiger Angebot beim Filmverleih wechseln

source/common.misc.plannerlist.programmelist.bmx
=> Reparatur Paging von Episoden; report scr0llbaer

source/main.bmx
Im Developermodus kann man aktuell ohne Zeitverlust (Spielzeit) Räume wechseln, was gegenüber der KI ein unfairer Vorteil ist, da keine Wegzeit verbraucht wird. Mit dieser Änderung wird die Figur zum Ziel geschickt, gleichzeitig das schnelle Vorspulen aktiviert und bei Erreichen des Ziels wieder deaktiviert.
Dieser Schnellvorlauf wird auch für die schon vorhandene Zielwahl im normalen Modus aktiviert (bislang hätte man den Hotkey gedrückt und dann mit Rechts-Taste vorgespult, bis man da ist). Hier wäre noch zu klären, ob für den normalen Modus das Vorspulen deaktivierbar sein sollte.
Aktuell wird die nahezu obsolete Methode DEV_switchRoom noch für das goto-Kommando im Chat verwendet. Aber auch diese Funktion könnte durch das neue goTo ersetzt werden.
=> Statt Beamen Schnellvorlauf bei Hot-Key

res/database/Default/database_people_fictional.xml, res/database/Default/database_programmes_fictional.xml, res/database/Default/user/therob.xml, source/game.database.bmx, source/game.programmeproducer.bmx, source/game.screen.supermarket.production.bmx
Minderjährige sollten nicht für alle Besetzungsvarianten auswählbar sein. In der ersten Variante wird nur die direkte Besetzung eines Slots geprüft. Späteres Verschieben oder Copy/Paste wird noch nicht unterbunden. (Proof of Concept)
closes #850
closes #1011
=> Mindestalter für bestimmte Berufe/Genre

config/programmedatamods.xml, source/game.broadcast.audienceattraction.bmx, source/game.broadcastmaterial.base.bmx, source/game.broadcastmaterial.programme.bmx
* Berücksichtigung der Flagwerte (gleichberechtigt mit Hauptgenre)
* Ergänzung von bislang nicht vorhandenen Flagwerten
* Modifikation ausgewählter Programmgenre-Mods
closes #1009
=> Berücksichtigung der zeitabhängigen Attraktivitätswerte für Flags

source/game.achievements.bmx
=> Flag/Genre-Einschränkung für Programm-Erfolg berücksichtigen

source/game.ingameinterface.bmx
=> Ausschalter schaltet Fernseher auch wieder ein; Report Scr0llbaer

source/Dig/base.framework.tooltip.bmx
Tooltip wird nie nach links oder nach oben vom Bildschirm verschoben. Originalposition wird bei Änderung von Titel/Inhalt wiederhergestellt. (Achtung. Beim Manipulieren der area-Position von außen wird die Originalposition nicht aktualisiert.)
closes #943
=> Fix veschwindende Tooltips; Report scr0llbaer

source/game.programme.newsevent.bmx, source/game.programme.newsevent.template.bmx
=> kein Neustart aktiver Nachrichtenketten

source/game.programme.newsevent.bmx, source/game.programme.newsevent.template.bmx
Entgegen meiner Annahme wurde die Nachrichtenqualität bereits mit einem Zufallseinfluss versehen (wenn nicht unique). Den Wert habe ich etwas erhöht und zusätzlich Preis und Abnutzung ergänzt.
closes #1071
=> Mehr Nachrichtenrandomisierung

source/common.misc.plannerlist.programmelist.bmx
Lizenzen und Sublizenzen haben sich dieselbe Max-Size-Variable geteilt. Die Neuberechnung erfolgt sowohl bei Update als auch bei Draw abwechselnd für die beiden. Wenn sich die Größen also unterscheiden, werden bei jeder Neuberechnung die Buttons genullt. Damit haben Draw und Update aber nicht dieselben Buttons in der Hand...
Mit der Änderung wird immer explizit die max-Variable gesetzt und es werden nur die Buttons genullt, die für die Berechnung relevant sind.
=> Paging im Programmplaner

source/game.person.base.bmx
=> Fix falsches Geschlecht generierter Personen; Report nsalomon

source/game.screen.supermarket.production.bmx
closes #1102
In der angepassten Implementierung wird nicht mehr nach Job (in fester Reihenfolge, die nicht mit der in der Datenbank verwendeten Reihenfolge übereinstimmen muss) vorgegangen. Stattdessen wird pro Slot der benötigte Job ermittelt und ein passender Eintrag aus dem "Ursprungskonzept" verwendet.
Berücksichtigt werden dabei der Job und das gewünschte Geschlecht der Besetzung. Das funktioniert ganz gut - bis auf folgenden Anwendungsfall, für den mir kein richtig gutes Vorgehen einfällt: Wenn man eine Besetzung absichtlich mit einem abweichenden Geschlecht besetzt, wird das aktuell nicht weitergegeben. Wenn man die Daten zwischen Konzepten, die nichts wirklich miteinander zu tun haben, übernimmt, tut das nicht weh. Hat man aber z.B. eine Serie, würde man erwarten, dass die Daten …
=> Einstellungen übernehmen vertauscht Besetzung; Report nsalomon

res/lang/advertisement/advertisement_en.txt
I'm pretty sure these translations make more sense in English.
=> Improvements to advertisement English translation

docs/manual_en.md, res/lang/programme/programme_en.txt
As a result of this discussion: https://www.gamezworld.de/phpforum/viewtopic.php?pid=90441
... it seems like a better term for the movie Speed in English would be Pacing.
=> Translation: Speed -> Pacing

source/main.bmx
=> Fix: [Savegames] dynamically adjust antenna radius to fit old reaches

source/gameDebug/game.debug.screen.page.playerbroadcasts.bmx
Für eine einfachere Übersicht bei der Optimierung der Lua-Programmplanung soll folgende Anpassung vorgenommen werden:
* Sortierung der Lizenzen nach maximaler Aktualität
* Hervorhebung der Lizenzen, die gerade maximale Aktualität haben (grün)
Auf diese Weise lässt sich insbesondere Potential für die Primetime-Planung erkennen. So sieht man damit z.B. ziemlich schnell, dass die letzten verbliebenen "neuen guten Filme" schon im Nachmittagsprogramm gesendet werden, anstatt sie für den Abend zu reservieren.
=> Debugansicht Programmplan

source/game.screen.stationmap.bmx
=> fix [Stationmap] selected antenna by position

source/game.game.bmx
=> Name/Sender initialer Spieler; Report scr0llbaer

config/programmedatamods.xml, source/game.production.productionconcept.bmx
Ich bin mal die Liste der Genre durchgegangen und habe Modifikatoren ergänzt,
=> Review Fokus-Punkte and Personenattribute

source/Dig/base.util.persongenerator.bmx
Sample output:
```
country: pl
* first names: 104 x female, 110 x male
* last names: 105 x
* male:
Emil Sowa
Tom Gajda
Przemyslaw Kozioł
Krzysztof Wolski
Rafał Urban
Damian Mazur
Paweł Wysocki
Henryk Andrzejewski
Sylwester Nowakowski
Witold Antczak
Witold Tomczyk
* female:
Luiza Piotrowska
Zuzanna Szewczyk
Urszula Urbańska
Alina Tkaczyk
Ewelina Makowska
Paula Kucharska
Ola Jarosz
Gabriela Markowska
Paulina Jasińska
Diana Krawczyk
Lidia Dąbek
-------
```
closes #1159
=> [Dig] Person name generator: add Poland

res/database/Default/database_programmes.xml, res/database/Default/user/ronny.xml, res/database/Default/user/scr0llbaer.xml, res/database/Default/user/stukov_scripts_adaptations.xml, res/database/Default/user/therob.xml, source/game.database.bmx
=> Zielgruppendefinition Drehbuchvorlagen; Report scr0llbaer

source/game.database.bmx, source/game.programme.programmedata.bmx
=> Call-In-Sendungen sollten nicht vor dem Veröffentlichungsdatum verfügbar sein; Report scr0llbaer

source/Dig/base.util.localization.bmx, source/common.misc.templatevariables.bmx
Speedup creation of TLocalizedStrings based of "random-value-group"-TLocalizedStrings by factor 10-15x.
=> [Misc] Speed-up TLocalizedString-Random-Value-getter by 10x

source/main.bmx
=> Fix: [Misc] Repair provider connection in old savegames

res/database/Default/database_ads.xml, res/database/Default/user/scr0llbaer-ads.xml, res/database/Default/user/stukov_ads.xml
I started going over the new ads. I changed the min audiences so that they are more evenly distributed over the existing slots. In particular the min audience value 12.5 had a lot more new entries than other slots.
In a second round, I will go over repetitions and duration. @scr0llbaer9000: maybe you could already check if any changes violate your intentions.
=> Review of new ads' distribution

source/game.gamescriptexpression.bmx, source/game.programme.programmerole.bmx
Allow 
Programme: ${.self:"role":castIndex:"fullname"}
Programme: ${.self:"cast":castIndex:"roleid"}
generic: ${.role:roleGUID/roleID:"fullname"}
=> [Misc] Script expressions: Support ".role" and "self:role"

source/game.gamescriptexpression.bmx
Vorschlag für einige Verschiebungen. Insb. cast/role sollten nicht ganz hinten stehen, da es wohl die am häufigsten verwendeten Aufrufe sein werden.
=> Auswertungsreihenfolge Expressions

source/game.gamescriptexpression.bmx
=> Reparatur Spitznamenauflösung

source/game.screen.programmeplanner.bmx
=> Fix: [Programmeplanner] Reenable Shortcut-clicks on run programme

source/Dig/base.util.localization.bmx, source/Dig/base.util.scriptexpression_ng.bmx, source/game.gamescriptexpression.bmx
=> Fix: [Misc] Correct .locale-scriptexpression-handling

source/game.betty.bmx, source/game.broadcastmaterial.programme.bmx, source/game.modifier.base.bmx
=> Datenbankeffekt für Betty

source/game.betty.bmx, source/main.bmx
Länge und Ausstrahlungszeit berücksichtigen.
=> Anpassung Berechnung Betty-Punkte

source/game.database.bmx
=> Fix: [DB] Correct licence relative-year based release time

source/game.player.programmecollection.bmx
=> Fix: [Misc] Check licence existence before compacting

source/game.newsagency.sports.bmx, source/game.newsagency.sports.icehockey.bmx, source/game.newsagency.sports.soccer.bmx, source/game.person.base.bmx, source/game.programme.programmedata.specials.bmx, source/main.bmx
Add "sport data" to persons instead of having a custom extended type for it.
This allows for sportsman becoming actors, politicians, ... while keeping their "history".
=> [Misc] Sportsmen are normal "persons" now (like actors, musicians)

source/game.figure.customfigures.bmx
closes #876 
Nur der eine Raum wird immer blockiert.
=> Gerichtsvollzieher blockiert Raum

res/database/Default/database_programmes_fictional.xml, res/database/Default/database_scripts.xml
Of course "Kultur Heute" can't be on while Betty is in her office.
=> fix kultur heute time slots

source/Dig/base.util.math.bmx, source/game.broadcastmaterial.news.bmx, source/game.game.bmx, source/game.gameconstants.bmx, source/game.modifier.base.bmx, source/game.newsagency.base.bmx, source/game.newsagency.bmx, source/game.programme.newsevent.bmx, source/gameDebug/game.debug.screen.page.newsagency.bmx, source/main.bmx
=> Fix: [News] Avoid accidental scheduled news skip

source/game.newsagency.base.bmx, source/game.programme.newsevent.bmx
=> Fix: [News] Ignore news events happening before game start

source/game.programme.newsevent.template.bmx
=> Fix: [News] Allow reusing of news events with optional leafs

source/Dig/base.util.luaengine.bmx, source/Dig/base.util.luaengine.c
=> Fix: [Dig] Lua: Convert BBStrings from/to UTF8

res/database/Default/database_ads.xml, res/database/Default/database_news.xml, res/database/Default/database_people.xml, res/database/Default/database_programmes_fictional.xml, res/database/Default/lang/de.xml, res/database/Default/lang/en.xml, res/database/Default/lang_original/en.xml, res/database/Default/user/cujo.xml, res/database/Default/user/jorgaeff.xml, res/database/Default/user/kasi.xml, res/database/Default/user/kieferer.xml, res/database/Default/user/ronny.xml, res/database/Default/user/scr0llbaer.xml, res/database/Default/user/scr0llbaer_news.xml, res/database/Default/user/scr0llbaer_screenplays_adaptations.xml, res/lang/news/news_de.txt
Grammar and typo fixes, applying some more references.
No "Gänsefüßchen" changed in context of the current hotfix. No instances appear in ad titles.
=> Content fixes 2025-01

res/ai/CommonAI/AIEngine.lua, res/ai/DefaultAIPlayer/DefaultAIPlayer.lua, source/Dig/base.util.logger.bmx, source/Dig/base.util.luaengine.bmx, source/Dig/base.util.luaengine.c, source/game.ai.base.bmx, source/game.ai.bmx
=> [Dig] Rewrite TLuaEngine

source/game.roomhandler.news.bmx
=> Fix: [Misc] Allow interaction with news if saved in planner

source/game.ingameinterface.bmx
=> Genre-Anzeige im TV-Hover; report pauldim

res/ai/DefaultAIPlayer/TaskSchedule.lua, source/game.ai.bmx, source/game.figure.base.bmx, source/game.player.programmecollection.bmx, source/game.stationmap.bmx
Mit den vorgeschlagenen Anpassungen gab es in den Testspielen noch weniger (oder spätere) Abstürze. Ich habe einen Commit aus einem anderen PR übernommen, damit die float-Probleme im Debug-Modus nicht durchschlagen.
Wenn Du die so übernehmen würdest, könnte von mir aus gemergt werden.
=> Vorschläge für Erweiterungen des Mutex-PRs

source/game.player.programmecollection.bmx, source/game.production.bmx
=> Absturz bei Scriptentfernen verhindern

source/game.menu.escapemenu.bmx
Statt einer expliziten Konfigurationsmöglichkeit in den Settings, gibt es eine Checkbox beim Speichern. Dann sieht man gleich, ob man weiterspielt oder ins Menü zurückkehrt.
Wenn die Umsetzung so grundsätzlich in Ordnung ist, könnte man den Checkboxzustand noch in den Settings speichern.
Oder man merkt es sich einfach nur für das laufende Spiel.
closes #1314
=> Weiterspielen oder Menü nach Speichern

source/game.game.bmx, source/game.gameconstants.bmx, source/game.programmeproducer.specialprogrammes.bmx
see #1357 
Der Produzent erstellt direkt Lizenzen basierend auf ausrangierten Titeln. Der aktuelle Proof of Concept funktioniert schon prinzipiell.
Die Besetzung muss noch umgesetzt werden und ein paar Werte sollte vielleicht randomisiert werden.
Die Prüfung, ob Remakes nötig sind, dauert noch zu lange und könnte optimiert werden (letztes Jahr für vorhandene Filme einmalig ermitteln, Anzahl guter Titel direkt aus der Filmagentur nehmen).
Eine Frage ist, ob man immer nur in der Zukunft produziert oder auch mal so tut, als ob das Remake von vor 3 Jahren ist (sonst sind alle "neuen" Filme immer maximal teuer).
Draft-PR für frühes Feedback.
=> Produzent für Remakes

source/game.player.programmeplan.bmx
closes #1365 
Zuvor wurden die Lizenzen, deren Ausstrahlungslimit erreicht war, zur Minute 54 entfernt. Ich habe den Block auf Minute 55 nach Verarbeitung der Werbung verschoben. Unklar ist, warum der Fehler nicht immer aufgetreten ist.
=> Lizenzen mit Ausstrahlungslimit erst nach Verarbeitung der Werbung entfernen

source/game.programme.adcontract.bmx
=> Höhe der Vertragsstrafe berücksichtigt nur nicht erfüllte Werbeblöcke
