TVTower/TVTower

res/ai/TaskBoss.lua

Statt des Kontostandes des Spielers wurde die Summe des aktuell aufgenommenen Kredites ausgelesen.

Korrektur beim Auslesen des Kontostandes

---

source/game.player.base.bmx
source/game.screen.stationmap.bmx
source/game.screen.supermarket.production.bmx
source/main.bmx

Ich glaube, es wäre sinnvoll, die Sondertasten explizit aktivieren/deaktivieren zu können, damit eine abweichende Tastatur-Steuerung je nach Situation einfach und robust umgesetzt werden kann. Ich habe dafür hier die Player-API erweitert (und an zwei Stellen verwendet - entsprechend der verlinkten Tickets).
Für den Sendemastkauf ist es mir nicht gelungen, die Mausposition explizit zu setzen. Setzen der Variablen im Mousemanager führt nur zu einem kurzzeitigen Positionswackler; dann gewinnt aber sofort wieder die Position der "Virtuellen Maus".

#134, #147 add API enable/disable hotkeys

---

source/game.production.productioncompany.base.bmx

As noted in #153, the amateur production company was the most expensive.
This was caused by always returning 100% if max experience is 0.

fix experience percentage for amateurs

---

source/game.screen.supermarket.production.bmx

Die aktuelle Implementierung hat nur Personen hinzugefügt, wenn ein Jobfilter gesetzt war. Statt dem "Oder" könnte man auch die person.HasJob-Implementierung anpassen und für den Wert 0 (Beruf egal) true zurückliefern.

#139 fix job filter

---

source/game.screen.supermarket.production.bmx

Analog der anderen Planungselemente sollte möglicherweise auch das Editieren von Titel und Beschreibung nach Abschluss der Planung nicht mehr möglich sein.
Problematisch bei Serien ist der Serientitel. Aktuell bleibt dieser änderbar solange man noch eine Folge planen kann.

#147 edit button enablement

---

source/game.production.productionconcept.bmx

Beim Versuch eine Produktion zu beschleunigen war mir aufgefallen, dass sich bei der Vergabe von Tempo-Punkten nichts an der Zeit ändert. Tatsächlich wurden die Faktoren gar nicht geändert, sondern unter dem selben Namen nochmal deklariert.
Langfristig könnte man darüber nachdenken, ob nicht auch die Studiogröße über die Dauer entscheiden sollte (aufwändige Kulissen = häufigere Kulissenwechsel in kleinem Studio aber paralleles Kulissenaufbauen in größeren Studios möglich).
Als Konsequenz wäre die Produktionszeit zum Zeitpunkt der Konzeption nicht festgelegt. Das finde ich aber auch realistisch. Z.B. müsste die Produkionszeit auch steigen, wenn die selben Personen gleichzeitig in mehreren Studios arbeiten.

fix setting production speed has no effect

---

source/game.screen.stationmap.bmx

Dieser PR beinhaltet 2 Commits zum Schließen der Tickets #134 (Fixieren der gewählten Sendemastposition mit Leertaste möglich) und #129 (Markieren des über die Karte gewählten Sendemasts in der Liste).
Ich denke, dass das Markieren und Anzeigen API-Funktionalität der GUI-Liste sein könnte. Es gibt schon den Aufruf für das Setzen der Auswahl, aber wenn man dann von Hand dafür sorgen muss, dass dieser Eintrag auch in der GUI sichtbar ist, ist das nicht komfortabel. Ich könnte mit eine GUI.Option an der Liste vorstellen (REVEAL_ON_SELECTION/PRESERVE_VISIBLE_SELECTION_ON_RESIZE), die dann automatisch dafür sorgen, dass beim Selektieren eines Eintrags an die richtige Stelle gescrollt wird oder dass beim Ändern der größe ein bereits selektierter Eintrag sichtbar bleibt.

Station map

---

source/game.screen.supermarket.production.bmx

Die Werte sollten auch für Episoden übernommen werden. Ansonsten gehen die Änderungen bei einem zweiten Bearbeiten verloren. Ansonsten konnte ich die in #116 geschilderten Fehler nicht mehr reproduzieren.

#116 episode title and description

---

source/game.roomhandler.studio.bmx

Erster If-Block gelöscht. Es kann zwar sein, dass nur der count-Text falsch ist und hätte richtig  angezeigt werden müssen. Ich finde aber die Gesamtinformation "0/5 produziert, 2/4 geplant" OK.

#172 fix production info

---

source/game.screen.supermarket.production.bmx

Anstatt das gesamte Supermarktlayout umzuwerfen, wird der verfügbare Platz besser genutzt, falls keine Produktion ausgewählt ist. Wenn mehr als 3 Einkaufszettel existieren, vergrößert sich die Auswahlliste. Das erleichtert dem Spieler die Übersicht und Auswahl. Beim Selektieren einer Produktion nimmt die Liste wieder die vorige Größe an, um Platz für den "Abschließen"-Dialog zu machen.
Durch das automatische Beibehalten und Scrollen einer Selektion auch bei Größenänderungen, bleibt auch die in einer langen Liste unten selektierte Produktion sichtbar.

#145 supermarket concept list size

---

res/lang/lang_de.txt
res/lang/lang_en.txt
source/game.stationmap.bmx

Der englische Text könnte etwas zu breit sein. Für Satellitenanbindung habe ich die Warnung nicht implementiert; da sollte man es sich eher denken können.
Tatsächlich habe ich nicht geprüft, was passiert, wenn man schon einen Satelliten hat und in ein neues Bundesland vorstößt. In diesem Fall könnten ja neben dem Zuwachs des Senders noch weitere Satellitenzuschauer dazukommen!?

#140 reach level alert

---

source/game.roomhandler.scriptagency.bmx
source/game.roomhandler.studio.bmx

Verhindern des Verkaufs gebrauchter Drehbücher implementiert. Es ist mir aber nicht gelungen, in der Drehbuchagentur einen Dialog anzuzeigen, warum der Drop des Drehbuchs nicht klappt. Sollte der Drehbuchautor in dem Fall ggf. gar nich mehr hervorgehoben werden?
Wegwerfen im Studio geht.

#171 no selling of used scripts

---

config/gfx.xml
source/game.screen.supermarket.production.bmx

Da in #123 explizit nach Genre-Erfahrung gefragt wurde, habe ich neben Berufserfahrung auch noch eine Sortiermöglichkeit nach Genre-Erfahrung (für das Haupt-Genre) ergänzt.
closes #123 
Ich habe etwas rumprobiert, scheitere aber am Anzeigen eines Tooltips, wenn man über den Button hovert.

[CustomProduction] add sort by genre experience

---

source/game.misc.ingamehelp.bmx
source/main.bmx

Mit dieser Änderung soll die Unterstützung mehrerer Sprachen für die Spielanleitung vorbereitet werden.
Anstatt den IngameHelp-Fenstern den fertigen Text zu geben, lösen diese die Schlüssel selbst auf. Das ist in jedem Fall besser, da sonst Änderungen in der Spracheinstellung erst nach dem nächsten Spielneustart aktiv werden.
Die aus der Textdatei eingelesene Spielanleitung wird der Sprache als neuer Schlüssel hinzugefügt. Der Code für das Einlesen der Spielanleitungen ist vorbereitet aber noch auskommentiert. Hier muss zunächst noch die Position und das Format für die Anleitungen festgelegt werden.
Für die Screen-spezifische Hilfe habe ich die Hide-Optionen deaktiviert, da sie hier wie bei der Spielanleitung nicht sinnvoll sind.

Vorbereitung Spielanleitung in mehreren Sprachen

---

source/game.screen.programmeplanner.bmx

Beim Hervorheben der zu ereichenden Zuschauerzahl war die Argumentreihenfolge falsch.
Closes #218

PlayerID und Anzeigetyp vertauscht

---

source/game.room.roomdoor.bmx

Mit dieser Änderung werden die Tooltips für Türen, die nicht ganz zu sehen sind unten links an der Tür angezeigt.
Es hat mich schon in MadTV geärgert, dass ich eine halb sichtbare Tür oben anklicken kann, aber nicht den Tooltip sehen kann. Besonders ärgerlich ist das, wenn man ein Studio hat, das man nur halb sieht. Um zu prüfen, ob es blockiert ist, muss man hinfahren. So könnte man einfach den Tooltip prüfen.

Tooltip für "halbe" Türen

---

source/game.roomhandler.archive.bmx

Wohl durch das fehlende Alignment-Argument wurde der Hover mittig links oben angezeigt.
Closes #225

fix data sheet hover position in archive

---

res/lang/stations/stations_en.txt
res/lang/stations/stations_fr.txt
res/lang/stations/stations_pt-br.txt
source/game.screen.stationmap.bmx

Für die Auswahlknöpfe war der Tooltip unter dem nun größeren Mauszeiger. Verschiebung nach Links wie im Programmplaner.
Die ACTIVATIONTIME-Variable für die Fertigstellungs-Anzeige in der Karte konnte nicht aufgelöst werden. TIME wie in der deutschen Variante.

Tooltips/Lokalisierung Senderkarte

---

source/game.misc.ingamehelp.bmx

Ich war noch nicht zufrieden mit dem Stand der Online-Hilfe. Das Anzeigen der Hide-Option ist zwingend nötig
* sonst erscheint die Hilfe immer wieder
* sonst kann man die automatische Hilfe gar nicht abschalten
Der Spieler muss aber bei jedem Bildschirm wieder den Nicht-Nochmal-Haken setzen. Es ist aber unwahrscheinlich, dass er dieselbe Hilfe immer wieder automatisch sehen will. Daher sollte das Flag beim ersten Anzeigen standardmäßig gesetzt werden.
Beim Rumprobieren (mit Limit) ist mir zudem ein one-off-Fehler aufgefallen. Wenn das Limit auf 1 gesetzt wird, wird die Nachricht dennoch 2x angezeigt (für Anzahl 0 und Anzahl 1).

Hide-Option für Kontext-Hilfe

---

source/game.roomhandler.studio.bmx

Bei mehreren Live-Produktionen (Morning-Show) ist der customProductions-String "-1, -1, -1, -1", da es keine Folgennummern gibt. Daher sollte in diesem Fall einfach die Anzahl der Vorproduktionen angezeigt werden.
Edit: Hinweis - Für Live-Produktionen mit mehreren Folgen ist auch das Editieren des Titels noch etwas verwirrend. Name und Beschreibung werden nur für eine Folge übernommen. Wenn man dann aber bei der zweiten den Editier-Button anklickt, steht schon der geänderte Titel drin. (Beispiel moringshow mit 4 Folgen)

Studiodialog "Starte alle" für Liveproduktionen

---

source/game.roomhandler.studio.bmx
source/game.screen.supermarket.production.bmx

Beim Erstellen des Konzepts wird nicht nur der Custom-Titel mit hinzugefügter laufender Nummer gesettz, sondern auch die CustomDescription. Beim Öffnen des Fensters für das Editieren werden die Daten nicht aus dem Skript sondern aus dem Konzept direkt verwendet.
Durch den Custom-Titel ist es ohnehin nicht möglich, den Namen für alle Folgen gleichzeitig umzusetzen (wenn man sich schon alle Einkaufslisten geholt hat). Da ist das analoge Setzen der Beschreibung nur konsequent.
Wenn man Titel und Beschreibung für alle Produktionen ändern will, holt man zunächst nur eine Einkaufsliste, ändert dort Titel und Beschreibung und holt anschließend die restlichen Einkaufslisten. In diesem Fall wurden die Custom-Texte nämlich nicht gesetzt und die Daten werden für die Folgelisten aus dem (genänderten) …

Editieren der Titel für Live-Produktionen

---

source/game.ingameinterface.bmx
source/game.misc.ingamehelp.bmx
source/main.bmx

Vereinfachung der automatischen Hilfe. Jede Hilfeseite wird nur noch einmal (pro gestartetem Spiel) angezeigt, außer der Spieler deaktiviert die Hinweise durch einmaliges Setzen des "nicht mehr anzeigen"-Hakens. Falls gesetzt wird diese Option auch persistert, so dass beim Laden eines Spielstands die Hilfetexte nicht wieder angezeigt werden.
Wenn die Option wieder deaktiviert wird, werden Hilfeseiten auch wieder (einmalig) angezeigt.
PR zunächst zum Review, falls die Persistenzproblematik für entfallene Arrays noch behoben wird.
Closes #241

Hilfe - nur noch komplettes Deaktivieren

---

res/lang/rooms/rooms_de.txt
res/lang/rooms/rooms_en.txt
res/lang/rooms/rooms_es.txt
res/lang/rooms/rooms_fr.txt
res/lang/rooms/rooms_pt-br.txt
res/lang/rooms/rooms_tr.txt
source/game.screen.archivedmessages.bmx

Ich habe eine Überschrift hinzugefügt und den Abstand erhöht. Die Großschreibung im Code zu machen, finde ich an dieser Stelle nicht so sinnvoll. Der Key wird nur hier verwendet. Die Lokalisierung kann also schon mit der richtigen Schreibung erfolgen.
Wenn es Dir wichtig ist, kann ich das aber auch noch ändern.

Archivierte Nachrichten DropDown-Überschrift und Abstand

---

source/game.stationmap.bmx

Ein Änderungsvorschlag noch: auch der Preis sollte bei einer schon bestehenden Kabelanbindung versteckt werden. Insb. wenn nicht genug Geld da ist, sieht es sonst so aus, als könne man es sich nicht leisten.
Closes #247

Karte - auch Preis bei bestehender Anbindung verstecken

---

source/game.roomhandler.movieagency.bmx

Ein unverkäufliches Programm (selbstproduzierte Live-Show) sollte den Verboten-Marker bekommen.
Aktuell kann das Element durch das Veto schon nicht aus dem Koffer genommen werden. Mit dieser Änderung wird noch der Cursor entsprechend angepasst.

Filmagentur: Verboten-Cursor falls nicht verkäuflich

---

source/game.misc.ingamehelp.bmx

Analog dem Öffnen des Menüs mit Escape bricht das Öffnen der Hilfe Aktionen im Raum ab.
closes #253

Öffnen der Hilfe bricht Aktionen ab

---

source/common.misc.plannerlist.programmelist.bmx

Die zusätzliche Prüfung bei Serienfolgen hat dazu geführt, dass nicht der Aufhebe-Cursor aktiv wurde.

[Programmeplanner] Cursor für Serienfolge

---

source/game.roomhandler.betty.bmx

Das GUI-Geschenk darf nur initialisiert werden, wenn eins gekauft wurde.
closes #265

Segmentation Fault Betty

---

source/game.misc.ingamehelp.bmx

Rechtsklick nicht weiterleiten. Es sollte erst die Hilfe zugehen und für das Verlassen des Raums ein weiterer Klick nötig sein.

[IngameHelp] Right-click handling

---

source/game.roomhandler.studio.bmx

Einfach Dialog zumachen. Die AbortActions-Methode kümmert sich um den Rest.
Closes #274.

Studio - kein Veto bei offenem Dialog

---

source/game.screen.supermarket.production.bmx

Vereinheitlichung der Funktion für alle Felder. Beim Zurücksetzen eines leeren Werts wird der Ursprungswert wiederhergestellt.
Zurücksetzen setzt Fokus auf das entsprechende Eingabefeld.

Zurücksetzen beim Titel editieren

---

source/game.screen.supermarket.production.bmx

Die Längenbegrenzung auf 128 Zeichen schneidet bestehende Beschreibungen ab (Reportage aus dem Sendegebiet).

Länge Beschreibungsfelder

---

source/game.roomhandler.studio.bmx

Das Drehbuch sollte beim Ziehen vor den Details liegen. Aktuell verschwindet es und nur der Halten-Cursor ist sichtbar. Das sieht seltsam aus.

[Studio] Anzeigeebene Drehbuch

---

source/game.screen.stationmap.bmx
source/game.stationmap.bmx

Ansatz für #300. Für Verträge wird angenommen, dass die Mietkosten ggf. nötige Hardware enthalten, d.h. bei einer vorzeitigen Vertragsaufläsung kann es keine Erträge geben. Je nach Restlaufzeit ist eine Strafgebühr zu zahlen.
Für Antennen sinkt der Verkaufswert ebenfalls je nach Alter. In keinem Fall erhält man den gesamten Kaufbetrag zurück. Zunächst ist der Verkaufspreis positiv (Materialrestwert/Weiterverwendung potentiell möglich). Ist die Antenne aber zu alt können Verschrottungskosten anfallen.
Langfristig könnten die Parameter vom Schwierigkeitsgrad abhängen. Die aktuellen Parameter sind Diskussionsgrundlage, die Commits sollten vor einem Merge noch zusammengefasst werden.

Kosten für Vertragsauflösung

---

source/gamefunctions_debug.bmx

Vorschlag für die Vereinheitlichung der Aktionsbuttons im Debug-Screen. Ich habe eine Methode für das Erzgeugen und Anzeigen von Aktionen rausgezogen. Für die meisten "Aktionsgruppen" werden die Aktionen nun oben rechts in einer Box angezeigt.
Ausgelassen habe ich die Fälle, wo die Buttons zu breit sein müssen (print statistics) oder wo es mehrere Aktionsspalten gab.
Die Anzeige der Daten für die Drehbuchagentur scheint mir noch nicht ganz so zu sein wir gewünscht. Da müsste ich aber erst noch verstehen, was unter offer und available eigentlich stehen soll.

Vereinheitlichung Code im Debug-Screen

---

source/game.roomhandler.studio.bmx

Der LIMIT_REACHED-Text wird auch angezeigt, wenn es weniger als 8 Einkaufslisten geben kann.
Aktuell wird für die Anzeige des Texts nur CanCreateProductionConcept herangezogen (da darin auch das GameRule-Limit geprüft wird). Allerdings können bei Filmen und Serien mit weniger als 8 Folgen auch einfach schon alle Einkaufslisen geholt worden sein - ohne das Limit zu erreichen. In diesem Fall ist der Text verwirrend.

Studio: Dialog maximale Anzahl auch bei Filmen

---

source/game.production.bmx
source/game.production.productionmanager.bmx

Vorschlag für Umsetzung von #309. Für direkt produzierte Nachfolge-Episoden wird ein Faktor mitgegeben (2 = Aufbau und Aufräumen entfällt, 1 = nur Aufbau entfällt, 0 = keine Einsparungen). Anhand dieses Faktors und der Basisproduktionszeit wird eine Zeiteinsparung ermittelt.
Code-Cleanup noch nicht erfolgt.

Verkürzung Produktionszeit

---

source/game.ingameinterface.bmx

#318 - Der Code für das Trailer-Bild war schon vorbereitet, hat aber die falschen Schlüssel verwendet, daher zog immer der Fallback.

Genre-Bild beim Trailer verwenden

---

config/interface.xml

Vorschlag für Verwendung bestehender Sprites für die noch nicht definierten Genre.
Im zweiten Commit schlage ich vor für ausfallende Werbung des Programmausfallbild zu nehmen - im Programmplaner sieht es in diesem Fall schließlich mit einem roten leeren Block auch gleich aus.
Closes #318

Definition Genre-Sprites

---

README.md
source/main.bmx

Ich habe mal die Kategorie korrigiert und die Readme leicht angepasst. Sollte die vielleicht auch mal generalüberholt werden? 
Zumindest die Referenz auf Versionen 0.3.x sollten doch mittlerweile obsolet sein, Mac-OS-Startproblem, ...

fix .desktop file

---

source/game.screen.archivedmessages.bmx

Wenn man den Generalschlüssel hat, sollte der Links-Klick auf fremden Nachrichten im Büro nicht zum "Gelesen"-Markieren führen.

Fix archivierte Nachrichten

---

source/game.betty.bmx

Solange Geschenke nicht dynamisch erzeugt oder geändert werden, reicht der Index für die Identitätsprüfung.
Closes #343

fix: [Betty] compare presents by index

---

source/game.roomhandler.archive.bmx
source/game.roomhandler.news.bmx
source/game.roomhandler.office.bmx

Anpassungen bei Generalschlüsselbesitz: kein Zugriff auf die Karte, kein interaktiver Cursor in anderen Nachrichtenstudios, Filmstöbern in anderen Archiven.
Es gibt bei den Nachrichten allerdings noch eine optische Reaktion der Buttons wenn man draufklickt...
closes #339

Generalschlüsselaktionen

---

res/database/Default/database.xml
res/database/Default/database_achievements.xml
res/database/Default/database_ads.xml
res/database/Default/database_news.xml
res/database/Default/database_people.xml
res/database/Default/database_programmes.xml
res/database/Default/database_scripts.xml
res/database/Default/user/jorgaeff.xml
res/database/Default/user/kieferer.xml
res/database/Default/user/nichtdiebetty.xml
res/database/Default/user/ronny.xml
res/database/Default/user/rumpelfreddy.xml
res/database/Default/user/sjaele.xml
res/database/Default/user/speedminister.xml
res/database/Default/user/therob.xml
source/game.database.bmx
source/game.gamescriptexpression.bmx

Hier schonmal vorgeschlagene Anpassungen an den News-Datenbankeinträgen. Einige Sachen dürften echte Fehler sein, andere Geschmackssache. Ich habe die Commits getrennt gelassen, so dass es leichter ist Teile der Anpassungen rauszulassen.
Die Änderungen an den Genres lassen sich im DB-Editor ganz gut prüfen (weiteres Review wäre hier auch nötig), da nun im Outline das Icon für das News-Genre angezeigt wird.
@jukey - gern auch drüberschauen; Neugenerierung beim Editor ist nötig, da es Grammatik-Änderungen gab.

database cleanup

---

source/game.production.productionconcept.gui.bmx

Im Datenblatt für einen angestrebten Dreh sollte als Potential nicht 100% sondern der Wert des zugrundeliegenden Scripts angezeigt werden.
closes #290

Studio Potential

---

source/game.screen.supermarket.production.bmx

Scrollen in der Liste beim Vergrößern nur, wenn der Scrollbar überhaupt sichtbar ist.
closes #368

Fix: [Supermarket] Scrolling Einkaufszettelliste

---

res/database/Default/database_news.xml
res/database/Default/user/jorgaeff.xml
res/database/Default/user/kieferer.xml
source/game.database.bmx
source/game.game.bmx
source/game.newsagency.sports.bmx
source/game.newsagency.sports.icehockey.bmx
source/game.newsagency.sports.soccer.bmx
source/game.world.worldtime.bmx

Weitere Aufräumarebeiten in Datenbank und Zeitermittlung.
* DB-Zeitdefinitionen und min-max-Vertauschung
* Börsennachrichten mit sauberer Initial- und Folgenachricht (solange es keine "regelmäßige happen_time" gibt)
* Zeit aus Zeittyp 4 und 5 entfernt, Ermittlung der Zeit aus dem vorgegebenen Datum
* One-Off-Fehler bei Tag des Jahres

DB und Zeitaufräumen

---

source/game.database.bmx

Folgen definieren typischerweise das Genre nicht neu. Beim Einlesen der Daten darf daher nicht 0 als Fallback verwendet werden, sondern das schon beim Clonen gesetzte Genre.
closes #374

Fallback für Serienfolgengenre

---

source/game.production.scripttemplate.bmx

Der Datenbank-Einlesecode verwendet die schon im Template vorhandenen Slope-Werte als Fallback. Minimum und Maximum sind in der Datenbank zumeist gesetzt. Wenn aber slope fehlt, führt das zu seltsamem Verhalten. Für alle Serien aus demselben Template wird derselbe Preis verlangt.
Mit dieser Änderung wird slope immer mit 0.5 vorinitialisiert, so dass ein sinnvoller Fallback vorhanden ist.
Außerdem: Kulissen und Episodenanzahl werden nicht ausgewertet.

Fix: [CustomProduction] set default slopes

---

source/main.bmx

Mit dem /dev exec scriptFile kann man einfach mehrere Kommandos ausführen (oder ein "kompliziertes" mit kürzerer Eingabe). Das ist ganz nützlich, um Vorbedingungen für Testfälle zu schaffen (z.B. mehrere Drehbücher zur Verfügung stellen, oder Geld und Beliebtheit anpassen).
Nur mit "/dev" beginnende Zeilen werden verarbeitet, so dass man die Skripte gut kommentieren kann.
Damit könnte man sogar eine Art Testfallkatalog erstellen (Datei enthält /dev-Kommandos und lesbare Anweisungen, denen man für einen manuellen Test folgen kann). Dafür wäre es allerdings noch hilfreich, wenn man den Dateipfad bei Nichtexistenz nochmal manipuliert (suche Scriptdatei z.B. auch in tests/testcases: /dev exec t1 vs /dev exec tests/testcases/t1).

Dev-Kommando für Script-Ausführung

---

res/lang/production/production_de.txt
res/lang/production/production_en.txt
res/lang/production/production_es.txt
res/lang/production/production_fr.txt
res/lang/production/production_pt-br.txt
res/lang/production/production_tr.txt
source/game.game.bmx
source/game.gamerules.bmx
source/game.person.base.bmx
source/game.person.bmx
source/game.production.bmx
source/game.production.productionmanager.bmx
source/game.programme.programmedata.bmx
source/game.screen.supermarket.production.bmx

- Verfuegbare Amateure in eigener Liste (damit immer die "gleichen" Leute statt immer Zufall pro "Listenaufruf")
- Liste wird aller 4 Stunden erneuert / durchgewuerfelt
- Amateure listen nun ihre Produktionen auf
- Upgrade von Amateur zu Profi/Promi nach Abschluss der dritten Produktion mit demselben Beruf (statt vorher "alle Berufe zusammen")
- Auswahllisten haben nun immer 5 Amateure mit zur Auswahl

Feat chooseable amateurs

---

source/game.gamescriptexpression.bmx

Ich glaube, die Script-Auswertung des Wochentages muss auf die Alternative umgestellt werden. Das Spiel beginnt nicht immer am Montag.
Wie komme ich gerade jetzt darauf? Eine Möglichkeit eine Reihe von Samstagabendshows Live (am Samstagabedn) zu erzwingen, wäre mit den aktuellen Optionen auch möglich, wenn man ein Script per Availability am Donnerstag verfügbar macht und dann als Livezeit für die Kinder "in 2 Tagen", "in 9 Tagen" etc. zu definieren. Einfacher wäre natürlich eine Erweiterung der Zeit-Codes.

FIX: weekday-script

---

source/game.roomhandler.studio.bmx

Es ist genügend Platz, so dass der Dialog den Koffer nicht verdecken muss.

[Studio] Koffer etwas nach rechts rücken

---

res/database/Default/database_scripts.xml

Wegen der unterschiedlichen Anzahl von Optionen für den Titel konnte es dazu kommen, dass er in einer Sprache "MISSING" war.

Fix: [DB] script title

---

res/database/Default/database_scripts.xml
res/database/Default/user/therob.xml

Wenn bei den "Feelings" leere Werte erlaubt sein sollen, kann man diese alle an den Anfang stellen

Fix: [DB] make string option count match

---

source/game.programme.programmelicence.bmx

#409: Statt unterschiedliche Filter zu verwenden, könnte der Availability-Filter etwas abgeschwächt werden. Programme im eigenen Besitz würden dann trotz Erreichen des Ausstrahlungslimits angezeigt werden (könnten aber nicht im Programm platziert werden).
Typischerweise sollte es ja ein Datenbankfehler sein, wenn sich ein Programm nach Erreichen des Limits noch im eigenen Besitz befindet - außer eben bei Serienfolgen, die nicht einzeln zurückgegeben werden sollten. Und selbst wenn es gewollt ist (Limit erreicht, aber Warten bis Aktualität wieder hoch bevor man verkauft), muss man das Programm sehen können!
Da die Filter aber auch an anderen Stellen verwendet werden, kann ich gerade schlecht einschätzen, ob diese Änderung andere ungewünsche Nebeneffekte hat.

Weniger strenger Available-Filter

---

source/game.screen.programmeplanner.bmx

Das in #401 beschriebene Fehlverhalten für Live-Trailer (rot vor Releasezeitpunkt) lag wohl an den vertauschten Methodenparametern.

Fix: [ProgrammePlanner] enable trailer slot for live programmes

---

source/game.player.programmecollection.bmx
source/game.player.programmeplan.bmx
source/game.production.bmx
source/game.programme.programmelicence.bmx

Ziel ist, dass das Refill-Flag (#400) nicht nur für Einzellizenzen sondern auch für Serien korrekt ausgewertet wird. Es ist von der Datenbank her möglich, dass die Folgen jeweils einzelne Limits haben (Pilot 1x, alle anderen Folgen 2x).
Der aktuelle Ansatz ist, dass das Remove/Sell-Flag als gesetzt angesehen wird, wenn es im Header oder in einer der Folgen definiert ist. Es ist nämlich wenig sinnvoll, dass nur eine Einzelfolge zurückgegeben wird.
Das Refill-Flag wird aktuell pro Folge einzeln interpretiert (wenn es nicht schon für den Header gesetzt ist).
Mit dem aktuellen Stand funktionieren bei mir explizit definierte Filme und Serien (Test und Anpassung für Eigenproduktionen steht noch aus. Hier ist insb. auf die korrekte Übernahme der Lizenzflags aus den Vorlagen zu achten).
Je mehr …

Pool refills limits

---

source/game.game.bmx

Ich habe in der letzten Zeit beim Testspielen für meine Änderungen vergleichsweise häufig sofort zu Spielbeginn den Klatschreporter-Award erhalten. Daher würde ich die Kategorien der Startnachrichten nicht komplett dem Zufall überlassen.

Kategorien der Startnachrichten

---

source/game.roomhandler.studio.bmx

Für den Fall, dass mehrere Drehs pro Script möglich sind, werden für die Namensermittlung die anderen Einkaufslisten und bereits produzierte Programme herangezogen. Falls nur ein Dreh möglich ist, sollte das Thema schon durch die Namenseindeutigkeit des Scripts selbst geregelt sein.
closes #430

[CustomProduction] improve uniqueness title

---

source/game.database.bmx
source/game.production.script.bmx

Für Serien werden die optionalen Flags des Haupteintrags nicht an die Kinddrehbuchvorlagen weitergegeben. Stattdessen werden bei der Drehbucherstellung die Flags ermittelt und dann an die Folgen vererbt (so sind dann z.B. alle Folgen live). Einzelfolgen können weiterhin eigene optionale Flags haben.
Die Berechnung der Live-Zeit und das Deaktivieren von X-Rated kann infolgedessen erst nach dem Propagieren der Elternflags erfolgen.

Behandlung optionaler Flags bei Serie

---

source/game.production.bmx

Für Live-Produktionen darf das Verschieben der Einkaufszettelposition nicht erst nach Abschluss der Produktion erfolgen sondern schon nach Abschluss der Vorproduktion.
Closes #453

Studio: Einkaufszettel für Live-Produktionen

---

source/game.production.productionconcept.gui.bmx
source/game.screen.supermarket.production.bmx

Für Serien/Drehbücher mit mehreren möglichen Produktionen kann man mehrere Einkaufslisten fertigstellen und alle Produktionen auf einmal starten.
Wenn man dann in den Supermarkt geht, sieht man nur den Einkaufszettel der unmittelbar gestarteten Produktion nicht mehr. Die anderen sind noch sichtbar. Wenn man aber abwartet, bis die zweite Produktion startet, sollte sich die Farbe des Einkaufszettels nich auf "in Planung" zurückändern.
Außerdem wurde umgesetzt, dass der Einkaufszettel (wenn bereits in Produktion) verschwindet, wenn er angeklickt wird.
Closes #449

Einkaufszettel Serienproduktion im Supermarkt

---

source/game.roomhandler.movieagency.bmx

Analog zur Werbe- und Drehbuchagentur kann auch beim Filmhändler eine aufgehobene Lizenz nun via Rechtsklick auf die Originalposition zurückgelegt werden.
Closes #450

Rechtsklick beim Filmhändler

---

source/gamefunctions_debug.bmx
source/main.bmx

Bei der Analyse der Raumtafelansicht ist aufgefallen, dass beim Angriff auf ein Studio die Nachricht den falschen Raum anzeigt. In diesem Zusammenhang wurde auch die Debugansicht etwas aufgeräumt
* explizites Losschicken der beiden Terroristen
* sie ermitteln den Raum anhand der Tafel wie im Spiel
* Button-Selektionsanzeige in der Debugansicht aufgeräumt
* Aktionen markiert, die nicht implementiert sind
Mögliche Verbesserungen: Starten der verschiedenen Sammys, Sammy-Vergabe triggern, Mieten/Kicken für einzelne Räume.
closes #451

Aufräumen Debugansicht

---

docs/manual_de.md
docs/manual_en.md
source/game.game.bmx
source/gamefunctions_debug.bmx
source/main.bmx

Keine Reaktion auf Hoch/Runter (nur Weltgeschwindigkeit aber nicht Gebäude). Verlangsamte Personen/Fahrstuhl nur in "Presets" 1-3, bei Vorspulen (5,6,7,8 und Pfeiltasten) werden alle Geschwindigkeiten gleichermaßen behandelt.
Das Setzen der Geschwindigkeite erfolgt über eine einheitliche API (nicht Setzen aller drei Werte einzeln).
Zunächst Review. Falls OK würde ich noch das Handbuch entsprechend anpassen. Außerdem könnte man sich für die Presets nochmal den Faktor für die Entitäten anschauen. Der Fahrstuhl öffnet sich im Level 3 verglichen mit den restlichen Geschwindigkeiten ziemlich langsam. Vielleicht kann das noch etwas erhöht werden.
closes #437

Geschwindigkeitsberechnung Vorspulen

---

source/gamefunctions_debug.bmx

Der Vergleich der Zuschauerzahlen allein reicht nicht - die Zielgruppe muss berücksichtigt werden - analog Interface.
see #476

[Debug] Farbindikator wenn Zielgruppenwerbung nicht geschafft

---

res/ai/CommonAI/AIEngine.lua
source/game.ai.bmx

Bis die KI stärker ist sollte sie nicht künstlich warten. Es ist fair, den Raum unmittelbar zu verlassen, wenn ein Task abgeschlossen ist.

[AI] kein Bummeln

---

source/gamefunctions_debug.bmx
source/main.bmx

Bei vielen Programmen gibt es einen Überlauf nach unten, so dass man die Zuschauerstatistik nicht mehr gut sehen kann.
* Serienfolgen nicht einzeln anzeigen (die Aktualität der Einzelfolgen könnte man ja im Notfall auch im Büro direkt anschauen)
* Überlauf verhindern und den Platz unter der Werbung nutzen; selbst wenn es da zum Überlauf kommt, sieht man in der Zuschauerstatistik zumindest noch die Zuschauerzahlen besser)
* Beim Wechsel des aktiven Spielers auch den Kanal wechseln (erleichtert schnelle Wechsel in der Debug-Ansicht; um die KI an- und auszuschalten müssen beide Werte übereinstimmen, damit es verlässlich klappt)
closes #467

Debug Programmübersicht

---

source/gamefunctions_debug.bmx
source/main.bmx

Rausgezogen aus #465.
Um die KI über längere Spielstände bewerten zu können, sollte es neben dem "Vorspulen um einen Tag" ein allgemeines Vorspulen geben. Die Aktion könnte in der Debug-Ansicht untergebracht werden (KI-Aktionen oder Misc).
Aktuell sehe ich diese Funktion weniger für den ausgelieferten Zustand als für die Entwicklung (wo ich ohnehin immer vor dem Start compiliere). Insofern sind die Paramter Geschwindigkeit/Anzahl der Tage, die vorgespult werden etc. nicht so kritisch.
Das Tastenkürzel "y" würde ich lieber rausnehmen und die Funktion direkt in den Debug-Screen integrieren. Der Eingriff ist zu drastisch, wenn man aus Versehen y drückt.
Das Speichern der Spielstände würde ich zumindest auskommentiert drinlassen. Auf diese Weise kann man von einem späteren Stand (Sendernetz …

KI-Vorspulen

---

source/gamefunctions_debug.bmx

Der Last-Minute-Fix zum Verhindern des Flackerns beim Zurückblättern hat einen anderen Bug verursacht. Beim ersten Öffnen wird der falsche Tag angezeigt und beim Tageswechsel wird die Ansicht auch nicht aktualisiert.

[Debug] Programmansicht bei Tageswechsel

---

res/ai/CommonAI/AIEngine.lua
res/ai/DefaultAIPlayer/BudgetManager.lua
res/ai/DefaultAIPlayer/CommonObjects.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskArchive.lua
res/ai/DefaultAIPlayer/TaskBoss.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskNewsAgency.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua
source/Dig/base.util.luaengine.bmx
source/game.ai.bmx
source/game.programme.adcontract.bmx
source/game.roomhandler.archive.bmx

[EDIT] Im Laufe des PR sind noch Anpassungen dazugekommen
Es ist ein erster Schritt in Richtung stärkere Gegenspieler. 
* Informercials unterbinden (zunächst komplett - sie machen das Image kaputt)
* Versuch Wartezeit zureduzieren
* weniger "schlechte" Verträge schließen
* weniger Verträge schließen, die schon vorhandenen ähneln
* Versuch der Minimierung gefährlicher Werbung (Bugfix überzählige Spots, keine Werbung für Kinder/Manager, restriktiver bei Zielgruppenwerbung)
* keine Call-In-Shows (Image)
* Fix für #477 (Bestimmung der Mindestzuschauerzahl immer mit TVT.ME)
* Programmplanung macht zunächst Optimierung der nächsten Stunden (aktuelle Werbung)
* Es werden nur Lizenzen erworben, deren Qualität oberhalb des aktuellen Durchschnitts liegt
* Vereinfachung BudgetManager (die Mittelung …

erste Verbesserung KI

---

source/game.game.bmx

Damit die Bewegung der Figuren in Stufe 3 nicht so nach Schnellvorlauf aussieht. Durch die aktuelle Konstellation Stufe 1 Modifier 1 und Stufe 2 Modifier 2 ändert sich dort an den Geschwindigkeiten nichts. Der Exponent hat nur auf Stufe 3 eine Auswirkung, da hier die Basis dann nicht 0 oder 1 ist. Durch leichte Modifikation könnte man die Bewegung hier also noch schneller oder langsamer machen.
closes #490

Laufgeschwindigkeit in Stufe 3

---

res/ai/DefaultAIPlayer/BudgetManager.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskBoss.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskNewsAgency.lua
res/ai/DefaultAIPlayer/TaskRoomBoard.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua

Hier eine weitere Liste kleinerer Verbesserungen an der KI. Die Commits sind wieder erstmal einzeln zur besseren Übersicht. Ein Bug gibt es beim onMinute-Aufruf. Der liefert die falsche Zeit. Das kann mit der int-Long-Umstellung der Zeit zu tun haben. Kannst Du da mal draufschauen (dass das Event sofort die richtige Zeit bekommt).
* Budgetberechnung berücksichtigt Zeit (Fixkostenanteile über den Tag verteilt)
* um X:06 wird nicht die eigentliche Programmkorrektur gemacht, sondern die Schedule-Prio hochgesetzt (funktioniert besser, wenn man nicht sowieso im Büro ist)
* etwas vorsichtigere Werbungsschätzung für Prime-Time (Vertragsstrafen verhindern) und weniger überzählige Spots - kann noch optimiert werden, je geringer die Anforderungen des Spots sind, desto mehr überzählige Spots wären …

KI weitere Verbesserungen

---

source/game.programmeproducer.bmx

Als ersten Schritt nachdem das Script erzeugt wurde, nochmal den Titel prüfen und Titel mit Zähler ablehnen.
see #458

[ProgrammeProducer] Titel mit Zähler vermeiden

---

source/game.broadcastmaterial.news.bmx

Bei einem Hyperschnellspiel (Producer-Lizenz-Titel) kam es bei mir gerade einen Seg-Fault mit voriger Event-ID-Listen-Ausgabe im modifizierten Code.
Es gab wohl gerade kein Event und selbst nach der Ausgabe aller News hat nicht das "end" gezogen, sondern es gab einen SegFault (kein Event trotz ID, kein Titel?). Jedenfalls gibt es auch an der Stelle noch Verbesserungspotential.

SegFault in news event

---

res/ai/CommonAI/AIEngine.lua
res/ai/DefaultAIPlayer/BudgetManager.lua
res/ai/DefaultAIPlayer/CommonObjects.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskArchive.lua
res/ai/DefaultAIPlayer/TaskBoss.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskNewsAgency.lua
res/ai/DefaultAIPlayer/TaskRoomBoard.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua
tst

Erster Vorschlag für die Logging-API. Das meiste "Debug-Logging" dürfte ja in den Jobs erfolgen. Daher bekommt die Basisklasse unterschiedliche Log-Methoden. 
* Das Log-Level kann entweder am Job direkt gesetzt werden oder wird vom Task geerbt
* Es wird nicht das Ende sondern der Start eines Jobs geloggt (wenn man was an den Ausführungszeiten prüfen will, kann man das Ende-Logging in der Engine wieder einschalten)
* Das meiste Logging ist erst einmal deaktiviert und muss nach und nach an die neue API angepasst werden. Das kann im Zuge der weiteren Optimierung der KI-Performance erfolgen
Interessant wäre noch API für das kurzzeitge Ändern von Log-Levels. Anwendungsfall wäre, dass man das Logging unter bestimmten Nebenbedingungen feiner machen will. Z.B. Vergleichen der Werbung, wenn eine …

KI Logging

---

source/game.broadcast.base.bmx
source/game.broadcastmaterial.news.bmx

Sendeausfall in der Statistik-Übersicht. Außerdem war bei den Nachrichten wieder so ein Dateistartzeichen reingerutscht.

fix outage localization

---

res/database/Default/user/kieferer.xml
res/database/Default/user/ronny.xml
res/database/Default/user/therob.xml

Ich habe bei einem Teil der Drehbuchtitel ohne Variablen mal welche eingefügt. Vielleicht hast Du noch ein paar Ideen. Das generische <Produzent>s "Titel" habe ich noch nicht berücksichtigt. Da sollten wohl auch keine generierten Namen verwendet werden.
Ich hatte auch schon mal überlegt, ob es nicht sinnvoll wäre, bei den Jobs auch vordefinierte, nicht änderbare Personen (per Referenz) zu unterstützen. Dann könnte man nämlich erzwingen, dass ein bestimmter Regisseur oder Hauptdarsteller dabei ist, der dann auch im Titel oder der Beschreibung auftaucht. Das wäre aber eine größere Erweiterung.

[DB] mehr Variablen in Drehbuchtiteln

---

res/ai/CommonAI/AIEngine.lua
res/ai/DefaultAIPlayer/CommonObjects.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua

Hier ein weiterer Aufräum-PR. Vorrangig habe ich aus den Tasks die debugMsg-Aufrufe entfernt. Im AIPlayer gibt es noch eine Reihe von "globalen" Funktionen, bei denen ein Umbau auf das Logging mit zwei zusätzlichen Parametern die Lesbarkeit verschlechtern würde. Aber diese Stellen dürften auch weniger interessant für Änderungen oder schnelles An- und Ausschalten sein.
Die andere wichtige Änderung ist ein Umbau der Entscheidung, ob ein Werbevertrag abgeschlossen wird oder nicht. Statt anhand der Level zu entscheiden (Morgens, Mittags, Abends) finde ich, dass die geforderte Zuschauerzahl entscheiden muss, wie viele überschüssige Spots es geben darf. Es kann ja durchaus zur Primetime mal einen Film geben, der deutlich weniger Zuschauer hat als mit dem besten Film erreichbar sind. Da können …

KI Logging aufräumen, Werbevertragsauswahl

---

config/DEV.xml
source/game.game.bmx
source/game.programmeproducer.bmx

Zur Steuerung der Anzahl vom Spiel produzierter Programme kann die Anzahl der Produzenten und die minimale Wartezeit zwischen zwei Produktionen konfiguriert werden.
closes #459

konfigurierbare Anzahl von Produzenten

---

config/DEV.xml
res/lang/gen_settings/genSettings_de.txt
res/lang/gen_settings/genSettings_en.txt
res/lang/gen_settings/genSettings_es.txt
res/lang/gen_settings/genSettings_fr.txt
res/lang/gen_settings/genSettings_pt-br.txt
res/lang/gen_settings/genSettings_tr.txt
source/game.database.bmx
source/game.gamerules.bmx
source/game.screen.menu.bmx

Prototyp für die Randomisierung von Tempo, Kritikerbewertung, Zuschauererfolg und Preis von Lizenzen beim Start eines neuen Spiels.
Die in der Datenbank hinterlegten Werte werden zufällig und ohne Wichtung um +/-20% (absolut, nicht vom Ausgangswert) geändert. Durch den Ausgangswert (20% oder 80%) ist die Tendenz meiner Ansicht nach hinreichend festgelegt, so dass es nicht nötigt ist, auf dieser Basis noch eine Verschiebung eher nach oben oder eher nach unten zu erzwingen.
Die Höhe der möglichen Abweichung könnte noch pro Attribut konfigurierbar gemacht werden (dev.xml). Im Gespräch war aber auch eine neuen gameconfig.xml, in der Z.B. Parameter für die Schwierigkeitslevel oder andere Spielparamter zusammengefasst werden.
Im Draft-PR geht es zunächst um die Position und den Ansatz für die …

Randomisierung Lizenzen

---

source/game.ai.base.bmx

Wenn ein Spiel mit einer KI-Implementierung gestartet wurde, die es beim Laden des Spielstandes nicht mehr gibt, sollte es nicht zum Programmabsturz kommen. Stattdessen wird die Default-Implementierung geladen.

kein Absturz bei fehlendem KI-Skript

---

config/DEV.xml
source/game.game.bmx
source/game.gamerules.bmx
source/game.stationmap.bmx

Der im PR verfolgte Ansatz ist, möglichst eine Startreichweite von knapp über 1 Mio zu haben. Erster Ansatz war, feste Größen für bestimmte Jahresabschnitte zu vergeben. Implementiert ist aber eine automatische Radiusermittlung.
Ab 1997 ist der Radius so groß, dass man kaum im Startsendegebiet so viele Zuschauer zusammenbekommt, um die Sendelizenzen bezahlen zu können. Deshalb ist das Antennensenden dann ohne zusätzliche Lizenz möglich. Das könnte man aber auch vom Radius statt vom Jahr abhängig machen.
Die Koordinaten der temporären Antenne ist aus den Spielersetup entnommen. Langfristig könnte diese Startposition aber auch in der Karte stehen.
Siehe #518

Antennenreichweite vom Startjahr abhängig

---

res/ai/CommonAI/AIEngine.lua
res/ai/DefaultAIPlayer/CommonObjects.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskArchive.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua
source/game.ai.bmx
source/game.stationmap.bmx

Du hast ja mit dem Drüberschauen schon angefangen... Zum eigentlichen Knackpunkt bin ich noch nicht gekommen - der dynamischen "Level-Zuweisung" für Filme. Die ist immer noch statisch. Mein lokaler Ansatz, die Qualität auf der "Roh-Qualität" basieren zu lassen, ist nämlich nach hinten losgegangen. Zwar wurden dann die "erwarteten" Filme im Hauptprogramm gezeigt, aber eben auch wenn sie sich noch ein paar Tage hätten erholen müssen.
Deshalb habe ich zunächst alle anderen Anpassungen aufgesammelt, die ich noch so gemacht habe:
* Filmverkauf für den schlechtesten, häufig gesendeten Film (Verbesserung Fundus)
* ein bisschen mehr Koordination Fundus- und Senderaufbau (Freigabe von Budget, wenn noch nicht genug Filme da sind)
* kleinere Verbesserungen bei der Sendungsplanung (korrekte …

KI-Verbesserungen

---

source/Dig/base.util.luaengine.bmx

Die Benachrichtigung ist während der Entwicklung hilfreich. Für Spieler dürfte sie aber eher verwirrend sein.

Keine Popup bei Lua-Fehler

---

source/game.betty.bmx

Neben den Bettypunkten für die Spieler muss auch die Geschenkhistorie zurückgesetzt werden. Ansonsten werden im Laden nach einem Neustart die falschen Zahlen für bereits gekaufte Geschenke angezeigt. Und auch die Prüfung, ob ein Geschenk an dem Tag noch überreicht werden darf, geht sonst schief.

Betty - Geschenkhistorie muss zurückgesetzt werden

---

res/ai/DefaultAIPlayer/TaskStationMap.lua
source/game.stationmap.bmx

Bei der Ermittlung der Attraktivität von Kabel- und Satellitenverträgen muss in Betracht gezogen werden, ob diese überhaupt abgeschlossen werden können (Mindest-Image). Ansonsten kann es vorkommen, dass eine KI, die mit dem Image nicht vom Fleck kommt, überhaupt nicht mehr ausbaut. (Kabelvertrag gewinnt wegen Attraktivität, Buy schlägt fehl und das immer wieder.)

KI-Stationsausbau

---

source/game.production.script.bmx

Besonders bei frühem Spielstart gibt es vergleichsweise wenige Kultursendungen. Da können Eigenproduktionen helfen. Analog zu den Programmen sollte daher erkennbar sein, ob es das Flag gesetzt ist.

Kultur-Flag bei Drehbüchern anzeigen

---

source/game.betty.bmx

Der Kommentar impliziert, dass das Image bei Betty 150% des Senderimage betragen kann. Der Code erlaubte allerdings maximal das Senderimage. Mit der Änderung kann es nun wirklich entsprechend mehr Bettypunkte geben.
Die Frage wäre, ob man das nicht sogar auf das Doppelte oder Dreifache erhöhen sollte. Aktuell spielt es vermutlich noch keine Rolle, wenn man aber Missionen einführt, in denen es darum geht, möglichst schnell bei Betty im Ansehen zu steigen, könnte es eine Strategie sein, mit möglichst vielen Geschenken und Kulturprogrammen ans Ziel zu kommen, dabei aber das Senderimage (etwas) zu vernachlässigen (geringere Einschaltquoten).

Image bei Betty sollte höher sein können als das Senderimage

---

source/main.bmx

Die Spielerfarbe wird in der Gewinnernachricht gezeigt analog zum zerstörten Raum nach einem Anschlag.

Spielerfarbe in Sammy-Gewinnernachricht

---

source/game.stationmap.bmx

Die API hat bislang das Kaufen von Antennen außerhalb der Karte zugelassen.

Antennen außerhalb der Karte verhindern

---

res/ai/DefaultAIPlayer/BudgetManager.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/Strategy.lua
res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskNewsAgency.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua
source/game.stationmap.bmx

Der Budgetmanager kümmert sich nicht mehr um die Investitionsstrategie.
Antennenpositionen werden nicht mehr zufällig ermittelt, um Überlappungen (und damit Fixkosten) zu vermeiden.

KI Änderung Budgetberechnung; Stationskauf

---

res/ai/DefaultAIPlayer/CommonObjects.lua
res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskArchive.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua

* Faktor für geratene Zuschauerzahl (ein erhöhtes Risiko für frühe Stunden ist nicht so kritisch, meist ist "schlechtere" Werbung ohnehin noch da, auf diese Weise wird aber auch bessere geholt)
* weniger Attraktivität für oft gesendete Programme
* mehr schlechte Lizenzen verkaufen
* weniger Animation (oft Kinderprogramm) zur Primetime
* Werbung, die am selben Tag fertig werden muss nicht von der Berücksichtigung ausschließen

weitere KI-Verbesserungen

---

source/game.roomhandler.movieagency.bmx

Die Reichweite bei einer gewonnenen Auktion muss persistiert werden, damit bei gleichzeitiger Reichweiteerhöhung kein (nur wenig) Gewinn gemacht werden kann.
Der Verkaufspreis wird nicht identisch dem Kaufpreis sein (andere Rundung).
closes #612

Filmpreis nach Auktion und Reichweitelevelerhöhung

---

res/ai/DefaultAIPlayer/BudgetManager.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskNewsAgency.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua

* Aufteilung des Restbudgets, wenn ein Task Tagesmaximum hat
* bei Auktionen sollte das Gebot und nicht der eigentliche Preis herangezogen werden
* mehrfache Senderkäufe ermöglichen, wenn das Restbudget groß genug ist
* mit der angepassten Stationsauswahl kann die Auswahl attraktiver Sender vereinfacht werden
* Beim Kultur-Sammy Kulturnachrichten senden (alle mit derselben Prio, da sonst die mit gewürfelt höherer Nachrichtenprio bevorteilt werden)

KI-Verbesserung

---

res/ai/DefaultAIPlayer/TaskStationMap.lua
source/game.game.bmx
source/game.stationmap.bmx

Wenn die Reichweite der Startantenne zu klein ist, sollte ein kleiner Kabelvertrag verwendet werden. Beim aktuellen DEV-Parameter von 950000 Zuschauern ist das im Startjahr 2000 der Fall.
Zum aktuellen Zeitpunkt bin ich mir nicht mehr sicher, ob man die Startreichweite für die Schwierigkeitsgrade unterscheiden sollte. Es sollte eigentlich ausreichen, die Preise etc. zu variieren. Da die Werbeeinnahmen im direkten Verhältnis zur Reichweite stehen, wäre es ziemlich aufwändig hier eine gute Balance zu finden (unterschiedliche Startreichweite impliziert ggf. unterschiedliche Antennenradien, die das gesamte Spiel über bestehen bleiben).
Ich denke, auch mit der gleichen Startzuschauerzahl gibt es genügend Stellschrauben, unterschiedliche Level zu erreichen und die Initialreichweite kann in der …

Kabel statt Antenne bei zu geringer Zuschauerzahl

---

source/game.programmeproducer.bmx

Damit nicht ausschließlich die ohnehin schon "beste" Produktionsfirma immer verwendet wird, bekommt die Auswahl einen Zufallsfaktor.
closes #628

Produktionsfirma mit Zufallsfaktor

---

source/gamefunctions_debug.bmx

Ursprünglich wurde beim KI-Spiel das Tempo auf 0 gesetzt und nach dem Speichern wieder auf den Standardwert, da es zu gelegentlich zu Abstürzen beim Speichern kam. Das soll eigentlich nicht (mehr) vorkommen. Insofern können diese beiden Geschwindigkeitsanpassungen entfallen.
Vorteil ist auch, dass man während des KI-Spiels die Geschwindigeit anpassen kann und dann dauerhaft mit dieser weitergespielt wird.

KI-Spiel - keine Geschwindigkeitsänderung nach dem Speichern

---

res/lang/production/production_fr.txt
res/lang/rooms/rooms_fr.txt
res/lang/stations/stations_de.txt
res/lang/stations/stations_en.txt
res/lang/stations/stations_es.txt
res/lang/stations/stations_fr.txt
res/lang/stations/stations_pt-br.txt
res/lang/stations/stations_tr.txt

* einheitliche Einrückung
* ein Variablen-Typo bei der Erweiterung der französischen Version
* Kommentare mit doppeltem Doppelkreuz (um sie bei der Konsistenzprüfung leichter von auskommentierten Schlüsseln zu unterscheiden)

Konsistenzprüfung Lokalisierung

---

res/ai/CommonAI/AIEngine.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskCheckSigns.lua
res/ai/DefaultAIPlayer/TaskNewsAgency.lua
res/ai/DefaultAIPlayer/TaskRoomBoard.lua
source/game.ai.bmx
source/gamefunctions_debug.bmx

Statt immer zum Raumplan zu gehen zu müssen, um umgehängte Schilder zu erkennen, macht die KI das nun beim Fahrstuhl. Zum Raumplan wird nur gegangen, wenn für die eigenen Räume Gefahr besteht oder wenn Schilder der Gegner umgehängt werden sollen.

Prüfung der Raumschilder beim Fahrstuhl

---

res/ai/DefaultAIPlayer/BudgetManager.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/Strategy.lua
res/ai/DefaultAIPlayer/TaskArchive.lua
res/ai/DefaultAIPlayer/TaskBoss.lua
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskNewsAgency.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua

* Senderausbau: Null-Prüfungen, höhere Reichweiteschwellen (schnellerer Ausbau bei sinkenden Zuschauerzahlen)
* Negativer Kontostand wird etwas später ausgeglichen (zwischenzeitliche Werbeeinnahmen)
* neuen Kredit aufnehmen, wenn alter abbezahlt (mehr Geld für Investitionen vorhanden)
* kein Lizenzverkauf, wenn zu wenige da sind
* Startprogrammanpassungen (keine globale Budgetbegrenzung, Preis pro Block statt Gesamtpreis), Startprogramm muss erst komplett sein, bevor normaler Lizenzkauf startet

[KI] Performanceverbesserungen

---

source/game.programme.programmelicence.bmx

Diese Änderung adressiert #572. Die Reichweitelevel bleiben in der aktuellen Form erhalten, aber die Lizenzpreise steigen nicht mehr linear an. Siehe auch Analyse in #630. Der langsamere Preisanstieg macht "gute" Lizenzen bei höheren Leveln nicht sofort wieder unattraktiv. Die Werbeeinnahmen steigen stärker als die Lizenzpreise, so dass man durch den Ausbau die Programmqualität verbessern kann (und nicht in niedrigem Level Lizenzen horten muss)

Preisänderung bei Reichweiteerhöhung

---

source/Dig/base.util.mersenne.bmx

Verwendung der alternativen Implementierung, die nur höchstens so viele Zufallsanfragen stellt, wie die gewünschte Liste lang ist. Ergänzung des Kommentars, dass die Grenzwerte inklusive sind (wie von den verwendenden Methoden erwartet).

[Misc] replace and fix RandRangeArray

---

source/game.gameconstants.bmx
source/gamefunctions_debug.bmx
source/main.bmx

Auf dem zweiten Quotenbildschirm gibt es eine Übersicht über alle Spieler (insb. für eine schnelle Übersicht über Reichweite, aktuelles Image, aktuelle Einschaltquoten).

Zweiter Quotenbildschirm

---

source/game.stationmap.bmx

Wenn schon zwei Spieler Kabelverträge für ein Land haben, wird das Mindestimage auf 0 gesetzt. Imagemäßig abgeschlagene Spieler bekommen damit zumindest die Möglichkeit, durch den Reichweiteausbau mehr Werbeeinnahmen zu generieren.
closes #626

Mindestimage entfernen

---

config/gamesettings/default.xml

Damit der Ausbau der Reichweite nicht ganz so schnell geht, sollen die Antennenpreise erhöht werden.

Erhöhung Antennenpreise

---

source/game.database.bmx
source/game.production.bmx
source/game.production.script.base.bmx
source/game.production.script.bmx
source/game.production.scripttemplate.bmx
source/game.programme.programmedata.bmx

Unterstützung des modifiers-Tags auch in Drehbuchvorlagen.
Der zweite Commit ändert die Semantik des Refresh-Modifiers. Anstatt auf den Gesamtfaktor angewandt zu werden, bezieht er sich auf die "prozentuale Änderung". Wenn also der Basisfaktor 1.4 ist (Anstieg um 40 %) würde der modifier 0.5 den Anstieg auf die Hälfte reduzieren (1.2) zuvor wäre der Faktor komplett halbiert worden (0.7).
Diese Änderung macht die Bedeutung des Modifiers für die Verwendung in der Datenbank verständlicher.
closes #676

Modifier in Drehbuchvorlagen unterstützen

---

res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskScripts.lua
source/game.ai.bmx
source/game.person.base.bmx
source/game.production.productionconcept.bmx
source/game.production.script.base.bmx
source/game.production.script.bmx
source/game.programmeproducer.bmx
source/gamefunctions_debug.bmx

Erste Version. Drehbuchkauf und Produktion funktionieren im Prinzip. Für die Planung wird der Producer-Code verwendet. Da eine komplette Planung innerhalb LUA ziemlich aufwändig wäre, würde ich das auch grundsätzlich so lassen. Man könnte noch weitere Parameter für die Planung mitgeben (Budgetaufteilung Cast/Firma) oder den gewürfelten Cast auswerten, um noch Modifkationen vorzunehmen.
Die KI reagiert auf den Sammy, ansonsten ist der Task aber niedrig priorisiert. Vielleicht sollte man die Anzahl der Produktionen in einer Sammy-Phase aber noch auf 1 beschränken, sonst gibt es ggf. zu viele pro Spieler. Es wird auch noch keine "echte" Budgetplanung gemacht, was ich aber auch nicht so schlimm finde.
Closes #549

KI Eigenproduktionen

---

res/database/Default/user/therob.xml

In der Datenbank kam price::age als modifier vor, der aber vom Code nicht unterstützt wird.
Meiner Ansicht nach sollte der vorhandene Price-Modifier ausreichen.

Entfernung eines nicht unterstützten Modifiers

---

source/game.production.productionconcept.bmx

Wenn die Drehbuchvorlage eine Produktionszeit definiert hat, wurde bislang die Verlängerung der Zeit durch die Auswahl von Fokuspunkten ignoriert. Die Zeit war also konstant egal ob Amateure ohne Punkte oder eine Level-5-Firma mit 25 Punkten gewählt war. (base-Zeit wurde nach Modifikation wieder zurückgesetzt)

keine feste Produktionszeit

---

source/game.programme.adcontract.bmx
source/game.screen.supermarket.production.bmx
source/main.bmx

Bei der Auswahl der Besetzung soll die gewählte Sortierung beibehalten werden.
Bei der Prüfung ist aufgefallen, dass das Sortieren der Werbeverträge kaputtgegangen war. Die Sortiermethode gibt den Spieler nicht mit und der Default -1 führt bei der Ermittlung der möglichen Zuschauerzahl zum Absturz.
closes #651

Sortierung der Besetzung beibehalten

---

source/game.roomhandler.movieagency.bmx

Runden der Preise am Ende nicht vor der Multiplikation mit dem Reichweitelevelfaktor.
closes #696

Runden der Auktionspreise

---

source/game.debug.screen.page.modifiers.bmx
source/gamefunctions_debug.bmx
source/main.bmx

Prototyp für die Erweiterung - Anzeige der Werte für die Schwierigkeitsgrade, Möglichkeit für die Manipulation.
Mit der aktuellen Implementierung teilen sich alle Spieler mit gleichem Level wohl ein Objekt. D.h. man kann zur Zeit nicht nur für einen Spieler einen Wert anpassen.
Wenn es keine grundsätzlichen Einwände gibt, würde ich das so für weitere relevante Werte erweitern.
closes #559

Debug-Screen Modifiers

---

source/game.broadcast.base.bmx
source/game.publicimage.bmx

In #504 wurden mögliche Anpassungen an der Imageberechnung besprochen. Der aktuelle Vorschlag ist eine (codemäßig) minimalinvasive Änderung für die Berechnung der Imageanpassungen.
Aktuell wird die absolute Zuschauerzahl pro Zielgruppe für die Reihenfolgefestlegung der Sender herangezogen. Das bevorteilt Spieler, die eine schnelle Senderausbaustrategie verfolgen übermäßig, da bei mehr Zuschauern selbst bei schlechterer Einschaltquote mehr Zuschauer erreicht werden können. Dadurch steigt ggf. trotz "schlechterem" Programms bei höheren Werbeeinnahmen auch noch das Image stärker (platt ausgedrückt: viel Mist ist besser als wenig Qualität).
Ich argumentiere, dass die vorgeschlagene Änderung (die Einschaltquote zur Basis der Reihenfolgeermittlung zu machen) dem Zielbild der Einbeziehung der …

Änderung der Berechnung der Imageupdates

---

config/DEV.xml

Nachdem die KI jetzt selbst produzieren kann, werden meiner Ansicht nach nicht mehr so viele Default-Produzenten benötigt.

Weniger Produzenten

---

source/game.newsagency.base.bmx
source/game.player.base.bmx

Bevor die Nachrichten in der Liste erscheinen, muss das Abo-Level effektiv geworden sein. Diese zusätzliche Prüfung erfolgt ausschließlich an den "Hinzufüge"-Stellen (sonst würde z.B. der Auswahl-Button das falsche Level anzeigen).
Sobald die Prüfung einmal erfolgreich war, wird der Zeitstempel des Abo zurückgesetz, um einen ständigen Zeitvergleich zu vermeinden.
closes #699

Nachrichtencheat verhindern

---

source/game.game.bmx
source/game.player.programmecollection.bmx

Seit die KI Eigenproduktionen machen kann, kann es zum Absturz bei Bankrott kommen. Das Script wird erst verkauft, danach werden ggf. Lizenzen angepasst. Der Verkauf setzt aber den Owner schon auf -1, so dass die ProgrammeCollection nicht mehr existieren kann.
Zur Sicherheit habe ich auch die Schritte für den Bankrott getauscht: Produktionen abbrechen, dann Scripte verkaufen und zuletzt Lizenzen.
Das Problem war (indirekt) aufgefallen, weil es bei den Testspielen mit Level schwer, häufiger frühe Abstürze gab. Die KI kommt hier mit Reichweite und Geld nicht so gut in die Gänge - laufende Serienproduktionen (noch kein sauberes Budget-Handling) führen dann öfter zu negativem Kontostand und ggf. Bankrott.

Absturz bei Bankrott verhindern

---

source/game.screen.supermarket.production.bmx

Da die Methode auch bei anderen Buttons aufgerufen wurde, hat sich bei Auswahl der Besetzung die Sortierung geändert. Mit diesem Commit wird zunächst geprüft, ob der Sortierbutton geklickt wurde.

Supermarktsortierung

---

config/DEV.xml
config/gamesettings/default.xml
source/game.gamerules.bmx

Die vorgeschlagenen Anpassungen setzen die Mindestzuschauerzahl hoch (insb. für die Startjahre, in denen die Zuschauerzahl runtergeht), machen das "normale" Spiel etwas schwieriger (leicht ungefähr gleich altes normal) und das schwere etwas leichter.
Die Werte sind ja individuell anpassbar, wenn jemand noch mehr Herausforderung braucht.

Anpassung Schwierigkeitsstufen

---

source/game.roomhandler.adagency.bmx

Die Aenderung sollte an sich keine Notwendigkeit bezueglich Threadsicherheit haben, da beide "RefreshGUIElements()"-Aufrufe durch "Mausklicks" zustande kamen.

[Misc] Defer GUI-Refresh in AdAgency

---

config/DEV.xml
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/database/Default/database_scripts.xml
source/game.broadcastmaterial.news.bmx
source/game.database.bmx
source/game.debug.screen.page.playerbroadcasts.bmx
source/game.player.bmx
source/game.player.financehistory.bmx
source/game.player.programmeplan.bmx
source/game.production.script.bmx
source/game.production.scripttemplate.bmx
source/game.programme.newsevent.bmx
source/game.programme.programmedata.bmx
source/main.bmx

siehe #700. Mit den vorgeschlagenen Änderungen steigen die Sielstandgrößen im späteren Spiel wesentlich geringer an (z.B. Tag 40 42MB statt 78MB). Die Hauptplatztreiber sind NewsEvents, die Finanzeinzeltransaktionshistorie (irrelevant wenn älter als 2 bis 3 Tage) sowie der Programmplan (meiner Ansicht nach irrelevant für die KI-Spieler; selbst wenn man den Generalschlüssel hat, interessiert man sich ja eher für das zukünftige Programm).
Das Kürzen der Programmliste führt dazu, dass für den ersten Tag verfügbaren Tag das Programm von 0 Uhr nicht mit angezeigt wird. Das sollte aber verkraftbar sein.
Bei meiner Analyse sind noch ProgrammeRoleCollection und PlayerCollection aufgefallen. Deren Platz steigen auch kontinuierlich an.

Größe Spielstände

---

source/game.game.bmx
source/game.gameconfig.bmx
source/main.bmx

Wenn man im normalen Spiel vorspult, sollte auch in einem Raum die gleiche Geschwindigkeit verwendet werden. Man möchte ja explizit vorspulen, ggf. aber Büro sein und den Programmplan beobachten.

Raumgeschwindigkeit bei Vorspulen nicht ändern

---

config/gamesettings/default.xml
res/ai/DefaultAIPlayer/TaskMovieDistributor.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua
source/game.game.bmx
source/game.player.difficulty.bmx

Vereinfachung der Berechnung für Startkapital; nur Geld und Lizenzen zählen, nur ein Startsender, dafür höheres Startkapital. Zunächst als Draft, da ich noch schaue, ob ich durch eine kleine Anpassung am KI-Verhalten verhindern kann, dass nicht sofort superteure Lizenzen gekauft werden.
closes #555

KI-Spielerbankrott

---

source/game.betty.bmx

Die technische Kopplung wird aufgehoben. Stattdessen kann ein Auftrag fordern, dass man sich nicht nur auf die Betty-Liebe konzentrieren darf.

Betty-Liebe von Senderimage unabhängig machen

---

source/game.game.base.bmx
source/game.game.bmx
source/game.gameconstants.bmx
source/game.mission.base.bmx
source/game.mission.bmx
source/game.mission.highscore.bmx
source/game.screen.menu.bmx

Ich glaube, das Einführen einer ID für ein Spiel wäre doch keine schlechte Idee. Selbst wenn sie nicht unmittelbar benötigt wird, würde sie uns dennoch erlauben, später Highscore-Einträge aufzuräumen bzw. Abfragen "Es gibt schon einen Highscore für dieses Spiel. Überschreiben/Aktuellen verwerfen/beide speichern?" zu integrieren.
Achtung: Es gibt aktuell noch einen unschönen Missionsbug. Der Missionsschwierigkeitsgrad geht beim Speichern aktuell verloren. D.h. Highscores für dieselbe Mission werden derzeit mit unterschiedlichen Missions-IDs gespeichert. Ich bin dran.

ID für Spiel

---

source/main.bmx

Der Profiler sollte auch in "logfiles/" schreiben.

Pfad für Profiler-Log

---

source/game.player.base.bmx
source/main.bmx

(Report scr0llbaer) Das Setzen des max-Levels in der Get-Methode funktioniert nur, wenn sie auch zur richtigen Zeit aufgerufen wird; z.B. wenn man aus Versehen auf den Knöpfen hovert.
Durch die regelmäßige Prüfung ist sichergestellt, dass das Max-Level des Tages auch ermittelt wird.
closes #745

Berechne korrekte Nachrichtenkosten

---

source/game.player.bmx

Aus ungeklärtem Grund funktioniert die Variante mit Listener-Methode nicht (mehr). Beim Iterieren über die Spieler werden keine Einträge ausgewertet. Ich habe das Aufrufen daher in eine Lister-Function umgewandelt.

Fix Spielstandgröße

---

source/game.mission.bmx
source/game.mission.highscore.bmx

Entschuldige die kurzfristige Änderung, aber ich denke damit wird es später wesentlich leichter, Highscore-Übersichten zu bauen.
Ich habe den Kartennamen aus der Missions-ID rausgenommen und zum Teil des Highscore gemacht.
Wenn dann mal weitere Karten kommen sollten, kann man damit leichter alle Highscores desselben Typs finden und dann nach Karte gruppieren.
Auch jetzt schon steht die Karte bei der Auswahl im Haupmenü noch nicht zur Verfügung (UNKNOWN) und ich könnte mir vorstellen, dass es neben der Auswahl einen Knopf für "Highscores anzeigen" geben könnte.
Weiterhin habe ich duplizierten Code für das Erstellen des Highscore-Eintrags rausgezogen und für statistische Zwecke noch die Anzahl der Tage im Highscore hinterlegt (es kann ja schon einen Unterschied machen, wie schnell ein Jahr …

Highscore-Aufräumen

---

source/game.world.bmx
source/game.world.worldweather.bmx
source/main.bmx
unittests/test.visual.world.weather.bmx

Ich spiele gerade mit der Wettersimulation herum. Ich habe den Ansatz verworfen, nur punktuell Temperaturplausibilitätsprüfungen zu machen. Meiner Ansicht nach macht es nur Probleme, sich ausschließlich auf die Sonnenscheindauer etc.zu verlassen. Kurze Begründung: Ziel wäre ja, in den Jahreszeiten halbwegs nachvollziehbare Temparaturbereiche zu erhalten. Die Wettersimulation weiß aber überhaupt nichts über die Anzahl der Tage pro Saison. Und es macht für die Simulation einen erheblichen Unterschied, ob das Ansteigen der Temparatur innerhalb eines Tages erreicht werden muss oder über fünf.
Um diesem Problem komplett aus dem Weg zu gehen, verfolge ich den Ansatz, pro Monat einen Nachttiefsttemparaturbereich und einen Tageshöchsttemparaturbereich zu hinterlegen. Es wird dann jeweils eine …

Wettersimulation

---

source/game.newsagency.bmx
source/game.world.worldweather.bmx
unittests/test.visual.world.weather.bmx

Bei einem Wertebereich von -4 bis 4 für die Windgeschwindigkeit, ist der Faktor 40 für die Geschwindigkeit in km/h sinnvoller. Zudem wurden die Werte für die Nachrichten angepasst (ungefähr anhand der Skala aus der Wikipedia).
see #607

Nachrichtenwindwerte

---

source/game.stationmap.bmx

In der aktuellen Implementierung kommt es zu einer ConcurrentModification. Das Array, über das iteriert wird, wird durch das "cancel" kürzer.
closes #775

Kabelvertrag auslaufen lassen

---

source/game.production.bmx
source/game.production.productionmanager.bmx

Mit dem zur Verfügung gestellten Spielstand sieht man, dass die Liveproduktion bei der Ausstrahlung nicht das "pausierende" GetProductionManager().StartLiveProductionInStudio(production.GetID()) ausführt.
Wenn man wie im Commit die Zeit für die Prüfung nach vorne verlegt, funktioniert das Pausieren... allerdings nur, wenn die Ausstrahlung auch wirklich zur geplanten Live-Zeit stattfinden. Verlegt man die Ausstrahlung um eine Stunde nach hinten, tritt wieder der "ursprüngliche" Fehler auf. Die laufende Produktion wird nicht korrekt pausiert.
closes #770

Fix: Liveproduktionen unterbrechen laufende Produktion

---

source/game.roomhandler.roomagency.bmx
source/main.bmx

Reguläres Raumverlassen versuchen, bevor Kick als Fallback ausgeführt wird.
Q ist laut Handbuch für das Verlassen des Raums vorgesehen. Insofern sollte reguläres Raumverlassen simuliert werden (Werbeverträge unterschreiben).
Wenn man kein versehentliches Werbevertragsunterschreiben möchte, sollte man die Verträge nicht in den Koffer legen...
Die Änderung beim Makler ist dafür, dass beim Raumbetreten nicht schon der Raumplan geöffnet ist. Mit Q wird der Raum ja verlassen, ohne dass alle Screens zu sein müssen.

Fix: Q für Raumverlassen (Report ARC-2000)

---

res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua

Ich habe angefangen, ein kleines Analysetool für die KI-Logs zu schreiben (Branch im Dictionary-Check-Repo). Hintergrund war die Frage, wie lange die KI eigentlich (in Spielminuten) für die jeweiligen Tasks benötigt und wie lange sie zwischen den Räumen unterwegs ist. Insb. auch im Vergleich zwischen den verschiedenen Geschwindigkeiten.
Ein wenig verwunderliches Ergebnis ist, dass die Taskausführung bei Geschwindigkeit 1 wesentlich schneller (oft weniger als 1 Minute) geht als bei Geschwindigkeit 3 oder den Vorspulgeschwindigkeiten. Das liegt vor allem daran, dass die Realzeitsekundenticks dazukommen. Interessanter war da schon die Erkenntnis, dass der Schedulingtask (bei mir) bei den hohen Geschwindigkeiten um die 20 Spielminuten dauert (und zwar auch, wenn man brainSpeed variiert). Das …

KI-Geschwindigkeit

---

source/game.screen.stationmap.bmx

Bei Antenne, Kabel und Satellit wird das Vorzeichen vor den Verkaufspreis gepackt.
closes #810

Vorzeichen bei Senderverkauf

---

source/game.gameeventkeys.bmx
source/game.stationmap.bmx

Mit dieser Änderung findet überhaupt keine Reduktion statt. Es sollte möglich sein, mit Antennen und Kabelverträgen Werbeeinnahmen zu steigern und das geforderte Image zu erreichen.
Im Vergleich zu Sendegenehmigungen für ein neues Bundesland ist der Preis für den Vertragsabschluss für Satelliten ziemlich gering.
closes #811

Keine Reduktion des geforderten Image für Satellitenvertrag

---

source/game.roomhandler.movieagency.bmx

Erste Fix-Variante  - Veto, wenn der Film von der Liste nicht angenommen wurde. Damit wird das falsche Zurückstellen unterbunden. Allerdings kann man damit normale Filme und Trash "austauschen", womit man aktuell höchstens sich selbst verwirren dürfte.
closes #828

Film nicht falsch zurückstellen

---

source/game.production.scripttemplate.bmx

Falls ein Job eine Rolle definiert, selbst aber kein Geschlecht vorgibt, sollte das Geschlecht der Rolle verwendet werden.

Geschlecht der Rolle an den Job weitergeben (scr0llbaer)

---

source/game.player.base.bmx
source/game.player.difficulty.bmx

Aktuell kommt man auf zwei Wegen an das Objekt für die Schwierigkeit. Per Player-ID aus der DifficultyCollection und direkt per Getter am Player. Der persistiert aber das Objekt nicht selbst, sondern initialisiert es beim ersten Aufruf anhand des Levelnamens. Beim Laden werden die Level aber neu initialisiert, so dass DifficultyCollection und Player auseinanderlaufen.
Mit diesem Fix holt sich der Spieler seinen Initialwert von der Collection.
closes #823

Korrekte Initialisierung des Difficulty-Objekts

---

source/main.bmx

Mit U kann man die Sprachen wechseln. Das könnte nicht nur für Übersetzungen interessant sein sondern auch für die UI-Entwicklung (Breiten von Controls...) - wenn denn die Übersetzungen einmal da sind.

Schneller Sprachwechsel im Entwicklermodus

---

source/game.screen.stationmap.bmx

Beim Update wurde die Aktualisierung mit einem anderen Flag-Pattern geprüft als in ReactToStationMapChanges selbst. Daher würde ich die Aktualisierung bei jeder Änderung aufrufen und die Prüfung nur in ReactToStationMapChanges machen.
closes #851

GUI-Listenaktualisierung bei Antennenverkauf

---

source/game.programme.programmelicence.bmx

Bei längeren Produktionsländerkombinationen (GB/USA) wird aktuell das Erscheinungsjahr abgeschnitten.

Erscheinungsjahr abgeschnitten (scr0llbaer)

---

source/game.ingameinterface.bmx
source/game.room.base.bmx
source/game.room.roomdoor.bmx
source/main.bmx

Nur Jahr+Monat im Interface anzeigen
closes #808
Eine Alternative wäre noch, den Monat in GetDayOfMonth auszuwerten und bei Februar ein Max von 28 zuzulassen. Aber die Methode wird schon ziemlich häufig aufgerufen...

Datumsangabe im Interface

---

config/screen_elements.xml

see #813 
Die Frage wäre, ob man im Büro das Ausrufezeichen für Zielgruppe auch noch einfach in derselben Farbe anzeigen kann. Das Ausrufezeichen im png hat jedenfalls nur aktuelle rotbraun.

Farben für Zielgruppenwerbung (Fix durch lonk0123)

---

source/game.stationmap.bmx

Mit späteren Startjahren werden Satelliten extrem attraktiv, da die Reichweite stark steigt, der Kaufpreis aber sehr niedrig ist. Im Gegensatz zu Kabelverträgen (Genehmigungsgebühren mit Kosten von ca 1 pro neuem Zuschauer) und Antennen (Reichweite-Kaufpreis-Verhältnis auch ca 1) war der Reichweitefaktor bisher ein Bruchteil.
Mit der vorgeschlagenen Änderung bleiben die Kaufpreise für Satelliten in frühen Jahren ähnlich, steigt dann aber auf ein mit den anderen vergleichbares Niveau.
closes #855

Erhöhung des Satellitenkaufpreises

---

res/ai/CommonAI/AIEngine.lua
res/ai/DefaultAIPlayer/DefaultAIPlayer.lua
res/ai/DefaultAIPlayer/TaskArchive.lua
res/ai/DefaultAIPlayer/TaskCheckSigns.lua
res/ai/DefaultAIPlayer/TaskSchedule.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua
source/game.ai.bmx
source/game.broadcast.audienceresult.bmx
source/game.stationmap.bmx

Wieder zunächst zur Begutachtung zwei Punkte, die mir für die KI-Performance seit einer Weile auf der Seele lagen. Zu Sendungsbeginn hat die KI ja schon geprüft, ob die Werbebedingung erfüllt ist - aber nur wenn keine Zielgruppe involviert war und der aktuelle Task wurde nicht wirklich unterbrochen. Weiterhin eine rudimentäre Auswertung der Einschaltquote um schlechte Filme frühzeitig zu verkaufen.
Die Erkennung beinhaltet nun auch Zielgruppen und ich habe die Engine so angepasst, dass ein unterbrechbarer Task (noch auf dem Weg) wirklich abgebrochen wird. Dadurch kommt es gefühlt zu wesentlich weniger Werbeausfällen.
Beim Erstellen der BusinessStatistik wird für Sendungen (mit nahezu maximaler Aktualität wegen der Vergleichbarkeit) die Einschaltquote ermittelt und abgespeichert. Bei …

KI - Werbeplanung, Lizenzverkauf

---

source/game.screen.supermarket.production.bmx

Disable focus point sliders until a company is selected.
Also refresh dropdown value on reset (else savegame load will display "old value")
Closes #861
Closes #830

[CustomProduction] Disable focus point sliders until company selected

---

source/game.game.bmx

Vor der Durchschnittsbildung wird erstmal fleißg aufaddiert. Dabei kann es zum Overflow kommen.
Zusätzlich habe ich das Startkapital auf 100Mio begrenzt. Das sollte ausreichen. Es geht ja nur darum, dass die neue KI nicht untergeht.

Integer overflow bei KI-Bankrott; report lonk0123

---

source/game.programme.programmedata.bmx

Für ein fertiges Programm sollten Personen mit mehreren Funktionen im Datenblatt nicht ignoriert werden.
closes #833

Besetzung mit mehreren Funktionen im Datenblatt anzeigen

---

source/common.misc.templatevariables.bmx

Wie im großen Lokalisierungs-PR bemerkt (und lokal verifiziert), müssen aktuell Titel-Einträge mit Variablen gedoppelt werden, auch wenn sie für alle Sprachen gleich aussehen würden.
Ich denke, der Bug lag darin, als Ausgangspunkt für eine Sprache direkt den resultierenden Eintrag zu verwenden. Der wurde beim Iterieren über mehrere Sprachen aber vielleicht schon modifiziert und enthält gar keine Variablen mehr.
* Titel mit Variablen nur für de
* Ersetzungen für de haben stattgefunden
* Basiseintrag für en = resultierender Eintrag für de -> enthält keine Variablen mehr
* vorhandene Variablen für en werden gar nicht verwendet
Als Fix wird in jedem rekursiven Schritt das vorige Ergebnis zwischengespeichert und *dieses* wird als Ausgangspunkt für alle Sprachen in diesem Schritt verwendet. …

Variablenersetzung mit Default-Sprache

---

source/common.misc.templatevariables.bmx
source/game.database.bmx
source/game.production.bmx
source/game.production.scripttemplate.bmx
source/game.programme.newsevent.bmx

Da das Expressionrefactoring die Erweiterung der Referenzierbarkeit von Rollen und Personen verzögert, habe ich den entsprechenden PR aufgetrennt. Damit können schon erste Verbesserungen (insb. im Bereich Nachrichten) angegangen werden. Im ersten Teil sind folgende Punkte enthalten
* Propagieren des Rollengeschlechts auf den Job
* Propagieren von Variablen an angestoßene Folgenachrichten (Personenreferenzen noch nicht unterstützt)
* Rollendefinition auch in Programmen (für späteres Referenzieren der Cast-Rollen in Titel/Beschreibung)
closes #836

Propagieren von Variablen für Nachrichten

---

source/game.database.bmx

Der Konsistenz wegen würde ich die Personen- und Programmdateien auch nach dem Aufteilen gleich behandeln. Ich habe gleichzeitig das Logging angepasst und die Anzahl der Drehbuchvorlagen ausgegeben.

Einlesen der Datenbankdateien an neue Aufteilung anpassen

---

res/database/Default/database_people.xml
res/database/Default/database_programmes.xml
res/database/Default/user/kasi.xml
res/database/Default/user/speedminister.xml
res/database/Default/user/therob.xml

A few more things can be done in this phase.
* Fix wrong values for fictional resp. add the tag in user files where it was missing, as discussed
* Fix long-standing indentation/whitespace issues in `database_people.xml`
* Some minor content corrections
* Add missing IMDB data to the remain real-people entries in [speedminister.xml](https://github.com/TVTower/TVTower/compare/master...scr0llbaer9000:TVTower:res-update-2b-fix-fictional?expand=1#diff-7de15ca888e729f8e17e4435b2e4ff1d7a850b7ee060d9cca8a336fe6b583bf2), to be moved in subsequent step.
No entries have have been moved in this commit.

fix fictional, correct some content & whitespace

---

source/game.database.bmx
source/game.programme.newsevent.template.bmx

Mit dieser Änderung kann man mehrere Initialnachrichten mit derselben Thread-ID markieren, um anzuzeigen, dass sie zum selben Thema gehören und nicht gleichzeitig gestartet werden sollen.
Wird ein Template verwendet, wird nicht nur das Template selbst als verwendet markiert, sondern auch alle anderen Templates mit derselben Thread-ID.
Bei einem Aufräumen der Nachrichten, sollten Thread-IDs entfernt werden, wenn sie nicht benötigt werden.

Nachrichtenketten mit derselben ID sollen nicht gleichzeitig starten

---

source/game.programmeproducer.bmx

Um die Verschwendung von Drehbüchern mit mehreren möglichen Produktionen zu vermeiden (oder der Dauerproduktion einer einzigen Sendung), sollen die In-Game Produzenten solche Drehbücher bei der Auswahl ignorieren.

Produzent soll Drehbuch mit mehr als einer Produktion ignorieren

---

res/database/Default/database_people.xml

Now on to new game data that I submit in parallel non-conflicting PRs.
This one has new person data required for my new programme entries.
I have also added all person entries I found from https://github.com/Marathony and from https://github.com/StukovTTV as I work with that dataset already when I create new programme entries locally.
I found we also need to introduce and cater for `nick_name_original`.

Add new person data, introduce nick_name_original

---

config/DEV.xml
source/game.debug.screen.page.adagency.bmx
source/game.gamerules.bmx
source/game.roomhandler.adagency.bmx

Es gibt zwei fertig implementierte Strategien für das Auffüllen der Werbung. Einmal feingranular nach Image und Einschaltquoten (gut für Tagesprogramm) und einmal grob (Billig und Rest, gefühlt gut für großes Prime-Angebot). Letztere war Default und sorgt dafür, dass das Werbeangebot ziemlich unausgewogen sein konnte (viel Prime-Werbung, kaum was für den Tag).
Ein globales Umschalten war per Dev-Optionen möglich.
Mit diesem PR wird ohne großes Anpassen der Strategien selbst dafür gesorgt, dass beim Austausch von Werbung zufällig eine der beiden Strategien verwendet wird und damit mal mehr Tageswerbung und mal mehr Primewerbung zur Verfügung steht.
closes #920
Edit: ggf. kann man von 50:50 auf 65:35 zugunsten der "aktuellen" Strategie wechseln, damit es nicht so leicht ist, gutes …

Strategie für Auffüllen der Werbung

---

source/game.database.bmx

Wenn beim Einlesen die Parentdaten des Felds targetGroupAttractivityMod für eine Folge übernommen werden, sind die Werte hinterher 0. Könnte am "falschen" Clonen Struct liegen.
Jedenfalls passt es ohne die Übernahme des Felds.

Propagieren targetGroupAttractivityMod für Serienfolgen

---

source/main.bmx

Bislang waren die Einschaltquoten für Live-Programme zu niedrig, da die Qualitäts-Werte des Programms erst berechnet wurden, wenn die Zuschauerzahlen schon aufgrund der nicht gesetzten Werte ermittelt wurden.
closes #928

Liveprogramm-Zuschauerzahl

---

source/game.roomhandler.adagency.bmx

Der niedrige Durchschnittswert für Tag ein sorgt dafür, dass ggf. zu wenige passende Verträge für den Filter existieren und er angepasst wird - auf Mindestquote 0, wodurch Schrottwerbung in der Hauptauswahl erscheint.

Werbefilter Tag 1

---

source/game.database.bmx
source/game.production.bmx
source/game.production.script.base.bmx
source/game.production.script.bmx

Aktuell sind feingranulare Anpassungen für Programme und Nachrichten möglich. Mit dieser Änderung kann auch für Drehbuchvorlagen die Zielgruppenattraktivität in der Datenbank hinterlegt werden.
Die Werte werden 1:1 von der Vorlage ans Drehbuch an die Programmdaten weitergegeben. Für Wertebereiche sehe ich hier keine Notwendigkeit. Für das Ergebnis gibt es genügend andere Zufallseinflüssen.

Zielgruppenattraktivität für Drehbuchvorlagen

---

source/game.production.script.bmx

Drehbücher für "Dauerformate" (Morgenshow) sind außer am Titel aktuell schwer zu erkennen. Insb. die Anzahl der möglichen Produktionen wird erst nach dem Kauf im Studio sichtbar.
Minimalumsetzung für die Anzeige im Datenblatt.

Anzahl Produktionen für Drehbuch anzeigen

---

source/game.production.productionconcept.bmx

Bislang wurden die Kosten und die Zeit aufgrund der Gesamtfokuspunktanzahl berechnet. Es erscheint aber sinnvoller, diese Werte pro Kategorie zu ermitteln. Je mehr Punkte in einer Kategorie vergeben werden, desto länger und teurer wird es (immer mehr Aufwand für etwas Verbesserung).
Außerdem sollten Zeit und Kosten wesentlich stärker als linear steigen. Bei den Kosten muss man sich überlegen, ob sich der zusätzliche Punkt lohnt. Bei der Zeit muss man sich überlegen, ob man Punkte für das Produktionstempo vergibt, um das Studio nicht so lange zu blockieren.
Achtung. Am Script gibt es das Flag "fictional", was wohl eine andere Bedeutung hat als das fictional an Nachrichten oder Programmen ("Sachbuch vs Roman"?). Es wird in der Datenbank aktuell nicht verwendet!

Kosten- und Zeiteinfluss der Fokuspunkte

---

source/game.production.script.bmx
source/game.roomhandler.scriptagency.bmx

Beim reinen Auffüllen (z.B. nach Drehbuchkauf) sollen möglichst keine Super-Drehbücher erzeugt werden. Es soll nicht mehr so einfach sein, durch Kauf von Drehbüchern und anschließendem Wiederbetreten der Agentur an neu erzeugte gute Drehbücher zu kommen. Die Änderung ist nur wirksam, wenn keine Drehbücher mehr im Pool sind, wenn also alle Drehbücher neu erzeugt werden müssten.
Auch gab es im Forum die Anmerkung, dass sich das Angebot in der Agentur zu selten ändert. GetRandomAvailable hat immer eins aus dem Pool geliefert, solange noch Drehbücher im Pool vorhanden waren (d.h. es gab nur wirklich neue, wenn beim Auffüllen wieder alle aus dem Pool entfernt wurden).
Mit einer gewissen Wahrscheinlichkeit wird nun ein Drehbuch auch neu erzeugt, wenn der Pool noch nicht leer ist.

Auffüllstrategie Drehbuchagentur

---

source/game.database.bmx
source/game.game.bmx
source/game.programme.programmedata.bmx

Es soll grundsätzlich die Möglichkeit geschaffen werden, Personennamen und Rollen zu lokalisieren.
Statt alle Sprachvarianten in die Hauptdatei zu integrieren, was eine Anpassung der Datenbanksyntax erfordert, werden die sprachspezifischen Daten analog den Sprachpropertydateien ausgelagert.
Per Konvention gibt es im Hauptdatenbankverzeichnis ein Unterverzeichnis "lang", in dem für jede unterstützte Sprache eine XML-Datei liegt. Diese XML-Datei enthält dann die Daten ausschließllich für die Datensätze, die eine Lokalisierung benötigen. Beim Start eines neuen Spiels oder beim Laden, wird die jeweilige Sprachvariante gelesen, damit die Namen für das gestartete Spiel zur Sprache passen.
Per Konvention ist Englisch die Standardsprache. D.h. Wenn ein Eintrag für eine andere Sprache ergänzt …

Lokalisierung von Personen und Rollen

---

source/game.production.script.bmx
source/game.programmeproducer.bmx
source/game.roomhandler.studio.bmx

Für Drehbuchvorlagen ohne Kindelemente aber mit mehreren möglichen Produktionen gibt (Showformate), wurden sinnvolle Änderungen vorgeschlagen.
* Einzelfolgen immer mit Nummer (auch erste Folge: `X #1, X #2, ...`)
* selber Drehbuchname wird geschützt, so lange noch ein aktives Drehbuch existiert (d.h. bis zurückgegeben oder abgedreht)
* Drehbuchname kann wiederverwendet werden, wenn der "Schutz" erloschen ist (Show mit demselben Namen kann durch jemand anderen weitergeführt werden)
see #552

Titelbehandlung für Drehbücher mit mehreren Produktionen

---

res/database/Default/database_programmes.xml
res/database/Default/database_programmes_fictional.xml
res/database/Default/user/jorgaeff.xml
res/database/Default/user/kasi.xml
res/database/Default/user/ronny.xml
res/database/Default/user/scr0llbaer.xml
res/database/Default/user/therob.xml

Some minor things I found during playtesting.
Some `staff` `function` corrections.
Some adjustments to some `targetgroupattractivity` values.
`Neid-Reiter` for consistency (had long already been used in news items, I had forgotten about the German version; though I don't find that spoof title all too good).
Shortened some too long descriptions (of old items) to fit into the available space.

Minor content corrections

---

source/game.production.productioncompany.base.bmx
source/game.production.productionconcept.bmx
source/game.programmeproducer.bmx

see #907 
Prototyp für das Abhängigmachen der Firmenkosten von der Blockanzahl (analog Besetzung). Ebenfalls werden die Fokuspunkte nach hinten deutlich teurer.
Für ein Problem mit diesem Ansatz gibt es noch keinen Hebel. Es gibt aktuell noch keine Möglichkeit, die Produktionskosten zu beeinflussen (außer dass der Spieler nur Amateure wählt). Das siebenstündige Nachtprogramm wird mit dieser Änderung noch unattraktiver. Aufgrund der hohen Blockzahl explodieren die Kosten, die Beschränkung der Ausstrahlungszeit (wenigste Zuschauer) und der Ausstrahlungshäufigkeit (einmal) verhindern aber, dass man die Kosten überhaupt reinbekommen kann.

Kosten der Produktionsfirma von Blockanzahl abhängig machen

---

source/game.newsagency.base.bmx
source/game.programme.newsevent.bmx

Im Zusammenhang mit #955 habe ich den Effekt modifyAvailability für Nachrichten ausprobiert. Der Trigger feuert und setzt das Flag. Wenn die Nachricht dann aber dran war, hatte das Flag allerdings wieder seinen Ausgangswert.
Es stellte sich heraus, dass unmittelbar nach dem RunFunction das UndoFunction lief. Ich denke, das soll nicht sein - wenn das Setzen erfolgreich war, soll der Effekt permanent sein.
Weiterhin fehlte bei Nachfolgenachrichten die Prüfung des Flags, so dass sie trotz "Verbots" verfügbar wären.

Event für Nachrichtenverfügbarkeit korrekt behandeln

---

source/basefunctions.bmx
source/common.misc.plannerlist.contractlist.bmx
source/game.achievements.bmx
source/game.award.base.bmx
source/game.broadcastmaterial.advertisement.bmx
source/game.gameconstants.bmx
source/game.ingameinterface.bmx
source/game.production.productionconcept.gui.bmx
source/game.programme.adcontract.bmx
source/game.programme.programmelicence.bmx
source/game.roomhandler.movieagency.bmx
source/game.roomhandler.news.bmx
source/game.roomhandler.roomagency.bmx
source/game.screen.financials.bmx
source/game.screen.stationmap.bmx
source/game.screen.supermarket.presents.bmx
source/game.screen.supermarket.production.bmx
source/game.stationmap.bmx
source/main.bmx

closes #822
Vorschlag ist, eine Konstante statt einer lokalisierten Währung zu verwenden. Falls wir das so machen wollen könnten wir noch überlegen, ob ein Leerzeichen vor dem Währungssymbol stehen soll oder nicht (z.B. auch indem dieses Leerzeichen Teil der Konstante ist und nicht bei jeder Verwendung einzeln ergänzt werden muss).

konsistentere Verwendung des Währungszeichens

---

source/game.production.bmx
source/game.roomhandler.movieagency.bmx

Ist aufgrund des Schwierigkeitsgrades der Filmpreisfaktor hoch, soll dieser nicht für den Verkauf von Eigenproduktionen angewandt werden (höherer Verkaufspreis).
see #784

Verkaufspreis von Eigenproduktionen soll Preisfaktor ignorieren

---

source/game.programme.newsevent.template.bmx

Die Datenbank sieht für Nachrichtentemplates zwar Qualitäts-Wertebereiche vor. Diese werden jedoch aktuell nicht genutzt. Für Einmalnachrichten ist das nicht so problematisch. Wiederkehrende Nachrichten sollten jedoch nicht immer dieselben Werte haben.
Daher wird, wenn Flag 2 nicht gesetzt ist und kein Qualtiätsbereich definiert ist, der Qualitätswert randomisiert.

Nachrichten: Randomisierung wiederkehrender Nachrichten

---

source/game.world.bmx

Reinit before new (or loaded) games start. Weather data is persisted, so loading in will overwrite it correctly.

Fix: [Misc] Reinitialize world weather each game

---

source/game.ingameinterface.bmx
unittests/test_tvfamily.bmx

(Eine) Ursache war die feste Position des Arbeitslosen. Hätte dort jemand sitzen bleiben wollen, wurde die Position zwar nicht übernommen aber auch nicht aufgrund anderer sitzenbleibender Personen neu berechnet.
Der neue Testfall erzeugt zufällige Konstellationen. Vor der Änderung gab es Fehler. Nach der Änderung lief der Test bei mir auch mit 50 Mio Iterationen ohne Fehler durch.
closes #964

Überlappende Couch-Positionen

---

source/game.ai.bmx

Bei der aktuellen Implementierung wird der Fall nicht berücksichtigt, dass gar keine Sendegenehmigung nötig ist. Das führt ins. bei späterem Spielstart dazu, dass die KI nur im Startland Antennen kauft, obwohl sie sich auch die in anderen Bundesländern leisten könnte.

KI über korrekten Sendegenehmigungspreis informieren; Report Yoshi

---

source/game.programme.newsevent.template.bmx

Wenn die Verfügbarkeitseinschränkung für Nachrichten sehr stark ist (sript mit And-Verknüpfung), wird es aktuell wahrscheinlich gar nicht verwendet, da es innerhalb des verfügbaren Zeitraums auch noch aus den vielen Möglichkeiten per Zufall ausgewählt werden muss.
Die vorgeschlagene Änderung erhöht die Wahrscheinlichkeit der Auswahl und macht damit das Erstellen solcher Nachrichten auch attraktiver.

Sendewahrscheinlichkeit für News erhöhen

---

source/game.database.bmx

Beim Datenbankeinlesen wird für Einträge mit unbekannter Sprache die ID -1 verwendet. Beim Setzen des Eintrags wird dann die aktuelle Sprache verwendet. Stattdessen sollten diese Einträge ignoriert werden.
closes #987

Datenbankeinträge mit nicht unterstützter Sprache ignorieren; report Scr0llbaer

---

source/game.production.productionconcept.gui.bmx

Die Anpassung ist nicht optimal. Bei Serien wird für den Serientitel immer nur eine Zeile zur Verfügung gestellt.
closes #993

Überlappende Texte im Supermarkt; report lonk0123

---

source/game.production.script.bmx
source/game.production.scripttemplate.bmx

Z.B. in scripttemplate-ron-visiting wird die Möglichkeit verwendet, eine Serie mit wenigen Folgen zu definieren, die aus einer langen Liste möglicher Folgen zufällig ausgewählt wird. Die Annahme der ersten Implementierung war, dass die Serien nichts wirklich miteinander zu tun haben, also immer eine Pilotfolge existiert (erstes Kind).
Möchte man ein solches Template aber nutzen um eine Serie mit mehreren Staffeln zu definieren (wobei die Einzelfolgen für sich selbst stehen sollten), wäre es ungünstig, wenn das erste Kind-Template immer dabei wäre.
Mit der gemachten Anpassung kann die "Pilotfolge" als optional markiert werden.

optionale "Pilotfolge" für Seriendrehbuchvorlagen

---

source/Dig/base.util.localization.bmx

Wenn ein Schlüssel nicht vorhanden ist, muss der Fallback verwendet werden. Durch die Initialisierung und Rückgabe von "availableStrings" gab es nie einen Fallback. Änderung bitte genau prüfen.
closes #1005

Reparatur Lokalisierungs-Fallback; report scr0llbaer

---

source/game.broadcastmaterial.base.bmx
source/game.broadcastmaterial.programme.bmx
source/game.programme.programmedata.bmx

In der aktuellen Filmpreisberechnung ist der Wertverlust aufgrund nicht maximaler Aktualität implizit (quality). Die vorgeschlagene Änderung berechnet den Basispreis aufgrund der maximalen Aktualität (ohne Anpassung) und zieht davon einen Wertverlust ab (wodurch sich diese Preisdifferenzen zum aktuellen Stand ändern). Erster Vorschlag ist, den Preisverlust auf die Hälfte des Ausgangspreises zu beschränke und von der Differenz zur maximalen Aktualität abhängig zu machen.
Grundsätzlich werden durch diese Änderung weitere Balancinganpassungen der Filmpreise erleichtert, da Basispreis und Wertverlust separat bearbeitbar sind.
Besonders teure Filme sind dadurch (weiter) nicht unmittelbar rentabel, da der Wertverlust der ersten Ausstrahlung (zur Primetime) durch Werbeeinnahmen nicht …

Anpassung Filmpreis(reduktion) und Ausstrahlungsattraktivität

---

source/game.person.base.bmx

Ein Debugspiel ist bei mir an dieser Stelle mit Segmentation-Fault abgestürzt. Die Variable jobsDone ist nur mit der Länge von "castJobs" initialisiert. Hier wird aber bislang über alle Jobs iteriert (ging bislang gut, da es zuvor keine Drehbücher mit Models etc. gab).
Unklar ist, ob das wirklich die richtige Lösung ist (Model-Jobs werden nun nicht gezählt).

Absturz bei ProductionFinish

---

res/ai/CommonAI/AIEngine.lua

closes #1034 
Die Blockade scheint nicht dauerhaft zu sein. Vielleicht ist das Problem deshalb nicht schneller hochgekocht. Einerseits kommt es selten vor, dass derselbe Task sofort nochmal aktiviert wird. Andererseits sorgt die Prioritätsneuberechnung dafür, dass irgendwann ein anderer Task wichtiger wird und die Blockade auflöst.

fix [AI] figure stuck in office; report Paneologe

---

source/game.award.base.bmx
source/game.award.culture.bmx
source/game.award.news.bmx

* Erhöhung des Zufallszeitfensters zwischen 2 Sammys
* grundsätzlich geringerer Imagezuwachs für News/Kultur
* der mögliche Imagegewinn sinkt mit jeder Ausschreibung eines Sammy

Sammy weniger häufig, geringerer Imagegewinn; Report Yoshi

---

source/game.programme.programmedata.bmx

Die Anzahl der Wiederholungen sollte grundätzlich einen höheren Einfluss auf die Einschaltquote haben (Erhöhung der Faktoren). Außerdem stand ja als TODO schon drin, dass die Entwicklung nicht linear sein sollte.
In der aktuellen Umsetzung bleibt es bei einem Einfluss der ersten 10 Wiederholungen - danach sollte das Programm so unattraktiv sei (auch des Alters wegen), dass man es ohnehin nicht mehr in der Prime-Time senden würde.
Der Verlust pro Wiederholung ist zunächst gering, steigt dann stark an und schwächt sich dann wieder ab.

Höherer Einfluss der Wiederholungen auf die maximale Aktualität (und damit die Einschaltquote)

---

source/game.broadcast.broadcaststatistic.bmx
source/game.programme.programmelicence.bmx

Im Datenblatt für Programme wird aktuell die maximale Zuschauerzahl angezeigt, was beim Sendegebietsausbau wenig aussagekräftig ist. Mit Shift kann die maximale Einschaltquote angezeigt werden.
Für die Datenhaltung wurde nur diese Zahl zusätzlich abgelegt. Noch mehr AudienceResult-Objekte nur dafür wären meiner Ansicht nach Overkill.

Anzeige maximale Einschaltquote

---

source/game.publicimage.bmx

Die Werte für die Imageanpassung nach eine Ausstrahlung werden an das aktuelle Image gekoppelt. Wenn das eigene Image höher als das Durchschnittsimage liegt, wird der Zugewinn reduziert, ein möglicher Verlust aber vergrößert, bei niedrigem Ausgangsimage umgekehrt.
Einerseits wird der KI nach einem Bankrott dadurch das Imageaufholen erleichtert, andererseits spiegelt es auch die Zuschauererwartung wider. Bei hoher Beliebtheit wird einem ein schlechtes Programm eher übelgenommen, bei geringem Image ist man von einem guten Programm positiv überrascht.
Bewegen sich alle Spieler im selben Imagebereich hat die Änderung praktisch keine Auswirkung.

[Balancing] Anpassung der Imageneuberechnung

---

source/game.programme.adcontract.bmx

In der ersten Version habe ich das Datenblatt für Werbung um eine Zeile erweitert, in der die Beträge pro Block angezeigt werden.
Optisch gefällt mir das aber nicht wirklich. Ich wäre eher für ein Umschalten der Anzeige - Gesamtbetrag Default, pro Block bei gedrückter Shift-Taste.

Anzeige Einnahme/Strafe pro Werbespot; report Paneologe

---

source/game.broadcast.genredefinition.movie.bmx
source/game.broadcastmaterial.advertisement.bmx
source/game.production.productionconcept.bmx
source/game.production.script.bmx
source/game.programme.programmedata.bmx
source/game.programmeproducer.bmx
source/game.screen.supermarket.production.bmx
unittests/movieGenreDefinitions.bmx

Zunächst Vorschlag für den Lösungsansatz. Anstatt an allen Stellen Haupt- und Subgenres getrennt zu betrachten und Wete zu aggregieren, werden beim Getter alle Genres mitgegeben. Für kombinierte Genres wird dort ggf. ein Aggregat erzeugt und persistiert.
Im ersten Commit wird erstmal nur ausgegeben, dass mehrere Genres angefragt werden und die Definition des Hauptgenres zurückgegeben.
closes #1010

Berücksichtigung Subgenres

---

source/Dig/base.util.mersenne.bmx
source/game.broadcast.genredefinition.movie.bmx
source/game.popularity.bmx
source/game.popularity.genre.bmx
source/gameDebug/gamefunctions_debug.bmx

Ich habe mir mal den Einfluss der Genre-Beliebtheit (Film) etwas genauer angeschaut. Der Wert taucht ja aktuell in der Quotenansicht nicht auf, hat aber einen nicht zu vernachlässigenden Einfluss.
Mit dem aktuellen PR soll folgendes erreicht werden:
* Genre, die seit einer Aktualisierung nicht ausgestrahlt wurden beliebter machen
* Genre, die ausgestrahlt werden weniger beliebt machen (unmittelbare Sättigung) - nicht nur beim "Update"
Dabei sind die Anpassungen nach oben und unten beschränkt und ergänzen die bestehende Berechnung lediglich.

dynamischere Genre-Beliebtheit

---

res/database/Default/user/ronny.xml
res/database/Default/user/scr0llbaer.xml
source/game.programme.programmedata.bmx

* Berechnung nur wenn nötig (aktuell<max)
* Genrepopularität bei der Erholung berücksichtigen (auch für Min-Werte)
* langsamere Erholung

[Balancing] Anpassung der Aktualitätserholung

---

source/game.game.bmx
source/game.gameconstants.bmx
source/game.room.base.bmx

Meldung im Forum, dass die Zielauswahl nicht immer betretbar ist (schon jemand im Raum).
Ich konnte das Problem bei mir sporadisch reproduzieren. Gelegentlich war er auch betretbar, obwohl die Ausgaben hätten erwareten lassen, dass die Meldung kommen müsste (canEnterRoom liefert False, weil ein anderer Spieler gerade im Raum ist).
Ursache für das Verhalten dürften die KI-Änderungen zur Terroristenanalyse sein. Da habe ich ja eingebaut, dass gelegentlich im Plan geschaut wird, ob die Räume verschoben sind. Zuvor hat wahrscheinlich keine andere Figur den Plan überhaupt betreten...
Die vorgeschlagene Änderung ist eine Sonderbehandlung des Plans bezüglich "kann betreten werden".

Fahrstuhlplan nicht immer betretbar; Report Paneologe

---

source/main.bmx

Beim Einbau der Missionen wurde die Zeit, zu der die Sammy-Updates angestoßen wurden geändert (Minute 59, damit die Auswertung am richtigen Tag stattfindet).
Das hat aber auch dazu geführt, dass die Sammys auch nur zu dieser Zeit gestartet werden (0:59) und zu dieser Zeit am nächsten Tag enden.
Mit dieser Reparatur werden die Sammys am Tagesbeginn gestartet (und enden damit 23:59) und werden am Tagesende abgeschlossen.

Reparatur Sammy-Zeiten; Report Streuner

---

config/gamesettings/default.xml
source/game.broadcastmaterial.programme.bmx
source/game.player.difficulty.bmx
source/game.programme.programmelicence.bmx
source/gameDebug/game.debug.screen.page.modifiers.bmx

Ein größerer Einfluss wäre möglich, wenn man die Aktualitätserholung vom Schwierigkeitsgrad abhängig machen würde. Das ist aber konzeptionell nicht ganz trivial, da die Aktualität ja nicht am Filem sondern an den Daten hängt, die nicht wirklich einen Besitzer haben. Auch im Fall von Programmen, die nach der Ausstrahlung verkauft werden, verpufft der Effekt ggf. (starker Spieler verkauft Programm -> erholt sich schneller, als wenn er es behalten hätte).
Daher als kleiner Ansatz: den Verlust der Aktualität bei Ausstrahlung mit einem schwierigkeitsabhängigen Faktor zu versehen.

[Balancing] Aktualitätsverlust bei Ausstrahlung abhängig vom Schwierigkeitsgrad

---

source/game.database.bmx
source/game.production.scripttemplate.bmx

see #995
Der XML-Errorhandler-Code in main.bmx um Zeile 140 greift nicht. Beim lokalen Einlesen einer Datei, in der ein Attribut doppelt definiert wird, gibt es zwar ein "print" des Fehlers (mit unbrauchbarer Zeilennummer), aber die erwartete Log-Ausgabe kommt nicht.

Datenbankfehler abfangen

---

source/game.ingameinterface.bmx
source/main.bmx

see #635
Aktuell kann man zwischen Fernsehfamilie und Chat umschalten. Die aktuelle GUI-Umsetzung erlaubt auch nur zwei Modi. Im ersten Teil dieses PRs wird das verallgemeinert (Modus aus, Fernsehfamilie, Chat). Die Pfeiltasten bleiben oben und es sind immer hoch und runter sichtbar.
Ich habe das PNG für den Chat anpassen müssen (unsauberes Copy/Paste), damit der ungenutzte Streifen oben und nicht unten ist. Das muss @GWRon nochmal ordentlich machen (am besten korrektes PNG zukommen lassen, damit es in diesen PR integriert werden kann).
Zunächst wäre der grundsätzliche Ansatz zu diskutieren. Nächster Schritt wäre dann den Modus Zuschauerverteilung umzusetzen (Hover->Fenster).

Erweiterung Interfacebereich

---

source/game.popularity.genre.bmx

* Schwellwert für das Zählen einer Ausstrahlung etwas erhöht
* Beliebtheit nicht sofort bei erster Ausstrahlung des Genres reduzieren
* Beliebtheit nicht nur bei gar keiner Ausstrahlung erhöhen

Beliebtheitseffekt von Ausstrahlungen etwas reduzieren

---

source/game.roomhandler.movieagency.bmx

Nicht aufgefallen, da bislang nicht verwendet... Das availability flag konnte beim Ermitteln der Angebote ignoriert werden. Ist kein Filter gesetzt, wird nicht geprüft und die Filter können via "checkAvailability" die Prüfung ausschalten (weil isAvailable() an der Lizenz mehr prüft als nur das Flag allein).

Filmhändler darf keine Filme anbieten, die das NotAvailable-Flag gesetzt haben

---

config/DEV.xml
config/gamesettings/default.xml
res/database/Default/database_ads.xml
res/database/Default/user/speedminister.xml
source/game.roomhandler.adagency.bmx
source/gameDebug/game.debug.screen.page.misc.bmx

Ich habe im Misc-Debug-Screen die Ausgabe der Statistik erweitert - csv-Format mit weiteren Spalten, die den Vergleich der Werbeverträge vereinfacht (Basiswert, Profit pro Spot, Sortierung nach Zuschauerzahl). Damit bekommt man eine relativ gute blockweise Übersicht über "ähnliche" Verträge.
Grundsätzlich habe ich die Profit-Werte der Zielgruppenwerbung in der Datenbank reduziert, da durch den Zielgruppen-Modifier der Schwierigkeitsgrade ohnehin eine Aufwertung dieser Verträge erfolgt. Die aktuellen Aufschläge waren einfach zu hoch. Weiterhin habe ich Zielgruppenwerbung bei "cheap" zugelassen, da es eine Reihe definierter Verträge gab, die nie verwendet wurden.
Da die Werbeeinnahmen durch die Änderungen zurückgegangen sind, habe ich zudem die Modifier für die täglichen …

Balancing Werbeverträge

---

res/database/Default/user/jorgaeff.xml
res/database/Default/user/ronny.xml
source/game.broadcastmaterial.programme.bmx
source/game.database.bmx
source/game.gameconstants.bmx
source/game.popularity.bmx
source/game.production.scripttemplate.bmx
source/game.programme.programmelicence.bmx

see #1058
Erster Prototyp:
* ausschließlich Lizenzeffekte - keine globalen Effekte für Daten (was wäre das Anwendungsszenario)
* happen(=broadcastDone), sowie broadcastFirstTimeDone
* zunächst modifyProgrammeAvailability
TODOS:
* aktuellen Stand mit Serien testen (effekt am parent, effekt an Einzelepisode, Freischalten einer Serie aktiviert alle Episoden)
* modifyScriptAvailability (bei Ausstrahlung eines Programms ein Remake-/Fortsetzungstemplate aktivieren)
* Programmeffekte in Drehbüchern umsetzen (Aussenden einer Serie aktiviert Drehbücher für die nächste Staffel; Hauptproblem wird hier, dass das Auffinden selbst produzierter Lizenzen...)

Umsetzung Effekte von Programmausstrahlung

---

source/game.production.script.bmx
source/game.production.scripttemplate.bmx

Aktuell wird eine Vorlage als verwendet markiert, sobald ein Drehbuch erstellt wurde, selbst wenn dieses nie verwendet wird.
Damit das "usedLimit" überhaupt sinnvoll einsetzbar ist, sollte die Vorlage nur dann markiert werden, wenn das Drehbuch verkauft oder vom In-Game-Produzenten verwendet wurde.

Drehbuchvorlage nicht bei jeder Verwendung markieren

---

source/game.database.bmx
source/game.production.bmx
source/game.production.script.base.bmx
source/game.production.script.bmx

Im ersten Schritt werden Effekte aus der Datenbank gelesen und an die erzeugten Lizenzen weitergegeben. Auf diese Weise kann z.B. durch die Ausstrahlung einer selbstgedrehten Staffel 1 die Drehbuchvorlage für Staffel 2 freigeschaltet werden.
In einem zweiten Schritt könnten auch Produktionseffekte implementiert werden (Effekt, wenn Produktion gestartet/abgeschlossen wurde). Ich glaube aber fast, dass der Großteil des gewünschten Verhaltens schon mit diesem Stand erreicht werden kann.
closes #1058
closes #972

Unterstützung Effekte in Drehbuchvorlagen

---

source/game.database.bmx

closes #1064
Die Reihenfolge des Einlesens der Datenbankdateien hat einen unerwünschten Nebeneffekt auf den möglichen Cast. Ist beim DB-Einlesen eine Person noch nicht bekannt, wird sie als fiktionale Person angelegt und später ggf. durch eine andere DB-Datei erweitert. Zu dem Zeitpunk wird das fiktional-Flag aber nicht wieder auf "0" zurückgesetzt.
Durch diese Härtung bekommt die unbekannte Person das fiktional-Flag des Programms - Programm und Cast passen also "zusammen".

Datenbank: Auswirkung Reihenfolge des Einlesens der Dateien

---

config/programmedatamods.xml
source/game.broadcast.genredefinition.movie.bmx
source/game.programme.programmedata.bmx
source/game.registry.loaders.bmx

Aktuell waren die Modifier fest im Code hinterlegt. Mit diesem PR werden sie analog der Time-Mods in die Konfigurationsdatei gepackt. Damit sind zentrale Stellschrauben (zum Vergleich) auch an einer Stelle.
Ich habe leichte Anpassungen vorgenommen (separate Commits) und auch die im Komödien-PR gemachten Anpassungen integriert.
Für Komödien habe ich zumindest die Erholung etwas verlangsamt (aktuell wengier Verlust, schnellere Erholung).

Modifier für Genreaktualisierung und -abnutzung in die programme-mods verschieben

---

source/Dig/base.util.mersenne.bmx

Bei der Werberandomisierung ist mir aufgefallen, dass die erzeugten Zufallszahlen außerhalb des erwarteten Wertebereichs liegen können.
Schon eine Handvoll Aufrufe des einfachen gaussRand liefert Werte kleiner als 0 oder größer als 1. Bei vorgegebenem Wertebereich wird das nur dadurch abgemildert, dass mit einem "abs"-Wert multipliziert wird und daher keine Werte kleiner dem Minimalwert rauskommen.
Vorschlag ist, die Ausreißer einfach auszusortieren und die restliche Berechnung unverändert zu lassen.

Workaround Gauss Zufallszahl außerhalb des Wertebereichs

---

config/DEV.xml
source/game.game.bmx
source/game.gamerules.bmx
source/game.programme.adcontract.bmx
source/game.roomhandler.adagency.bmx
source/main.bmx

Initialer Vorschlag für die Randomisierung der Werbewerte. Damit Debug-Export die Werte nicht verfälscht werden, erfolgt die Randomisierung erst beim Hinzufügen in der Werbeagentur.
Der erste Commit wäre nochmal zu diskutieren. Ich habe mich daran gestört, dass nicht die Dev-Werte des gespeicherten Spielstands verwendet werden (alter Spielstand ohne Randomisierung, nach Laden in neuer Version wird plötzlich randomisiert - die Datenbank wird ja auch nicht auf den neusten Stand gebracht). Wenn man die neuen dev-Werte verwenden möchte, kann man ja das Chat-Kommando verwenden.
closes #1070

Randomisierung Werbung

---

source/game.game.bmx
source/game.gamerules.bmx
source/main.bmx

Es wird ein explizites Feld für den Modus eingeführt. Dann muss die Auswertung nicht immer auf den Config-Key gehen.
Ich hatte in einer früheren Version eingebaut, dass der Modus auch beim Laden eines Spiels immer aus der DEV.xml geholt wird. Aktuell wäre ich eher dafür, dass die Werte immer wie im Spielstand gespeichert verwendet werden - ist konsistenter.

Auswertung Debug-Modus vereinfachen

---

source/game.screen.archivedmessages.bmx

Rechtsklick bei Archivnachrichen immer als behandelt  betrachten.
Wenn aus Versehen der Modus nicht wie erwartet ist, geht bei Rechtsklick auf eine Nachricht der Screen zu. Dafür sollte der Spieler explizit woanders geklickt haben.

Klickbehandlung bei Archivnachrichten; Report engsoz

---

config/settings_colors.xml

Ich habe versucht, die Farben weiter auseinander zu bekommen. Ein Grün weniger (3 statt 4), Versuch pro Farbton dunkel, mittel und hell hinzubekommen.
closes #874

Spielerfarben unterschiedlicher gestalten

---

source/main.bmx

Der Cache des Sprites wurde bei Bankrott nicht invalidiert - Vorschlag: der Einfachheit halber bei allen Türen.

Türfarbe nach Bankrott aktualisieren; Report engsoz

---

source/game.production.script.bmx
source/game.production.scripttemplate.bmx
source/game.programmeproducer.bmx

Zu Spielbeginn sollten vorrangig Drehbücher für Studiogröße 1 verfügbar sein. Die Wahrscheinlichkeit, dass die anderen Drehbücher angeboten werden steigt mit jedem Spieltag.
closes #1080

Drehbuchangebot bezüglich Studiogröße einschränken

---

source/game.roomhandler.scriptagency.bmx

Falsches Vorzeichen bei der Ermittlung des spätesten Entfernungszeitpunkts. In der aktuellen Implementierung konnten die Drehbücher noch 15 Stunden nach dem Live-Termin verfügbar sein.

Fehler bei Livescriptentfernung

---

source/game.programme.adcontract.bmx
source/game.roomhandler.adagency.bmx

Die Sortierung im Koffer wird der ausgewählten Sortierung in der Werbeagentur angepasst. Vorschlag im zweiten Commit: statt den absoluten Profit für einen Vertrag zu vergleichen sollte der Profit pro Spot verglichen werden.

Werbekoffersortierung

---

source/game.roomhandler.adagency.bmx

rote Einfärbung für Verträge mit wenig verbleibender Zeit
closes #779

Einfärbung Werbung im Koffer

---

source/game.screen.archivedmessages.bmx

Das Event für den Filterwechsel wird hin und wieder wohl auch ohne Nutzerinteraktion gefeuert. Als Ergebnis stimmen mutmaßlich ausgewählte und der tatsächliche Filter nicht mehr zusammen (da "0" von "nicht gesetzt" nicht unterschieden werden kann).
Aus diesem Grund bekommt "alle ausgewählt" einen anderen Wert.

Filter archivierte Nachrichten

---

source/game.misc.roomboardsign.bmx
source/game.newsagency.base.bmx

closes #1094 
* höhere Wahrscheinlichkeit für das Finden von Spuren
* korrigierte Wertanpassung
* beim Ändern eines Schilds werden nicht alle, die es bewegt haben zurückgesetzt.

Imageänderung bei Explosion

---

source/game.screen.archivedmessages.bmx

closes #1097
(Mindesthöhe beibehalten, damit die Nachrichten nicht so unruhig aussehen, wenn alle unterschiedliche Höhen haben. So sind nur die besonders langen etwas größer.)

archivierte Nachrichten nicht in der Höhe beschneiden; Report Pampelmops

---

source/game.broadcast.audience.bmx

Für kombinierte Zielgruppen wurde das "Get" auf dem Index statt auf der ID der Teilzielgruppe aufgerufen.

Bugfix Zuschauerberechnung für kombinierte Zielgruppen; Report dirkw

---

source/game.screen.statistics.bmx

closes #1096 
* aktueller Block wenn nichts anderes selektiert/gehovert
* Deselektion ermöglicht
* selektierter Block wird nur hervorgehoben, wenn nichts anderes gehovert wird (sonst ist optisch unklar, welcher von beiden eigentlich angezeigt wird)

Statistikbildschirm: Anzeige aktueller Block

---

res/database/Default/database_programmes.xml
res/database/Default/user/therob.xml

Im Forum wurde angemerkt, dass bei Fuchs unter Füchsen in der letzten Serie das falsche Fernsehbild gezeigt wurde. Tatsächlich war das Hauptgenre der letzten Folge als "Monumental" angegeben. Für "überlange" Finalfolgen würde ich "Monumental" nicht als Hauptgenre verwenden sondern als Untergenre.
Ich habe die Datenbank mal nach Stellen durchsucht, an denen Einzelfolgen die data-Tags enthalten und damit die Daten des Haupteintrags überschreiben. In diesem PR wurden diese z.T. angepasst:
* Löschen von duplizierten Einträgen
* Löschen von Einzelattributen, die keine Änderung bewirken
* Anpassung Subgenre statt Hauptgenre für lange Finalfolgen einer Serie

Episoden-Genre, Report Der Baum

---

res/database/Default/database_people_fictional.xml
res/database/Default/lang/de.xml
res/database/Default/lang/en.xml
res/database/Default/lang_original/de.xml
res/database/Default/lang_original/en.xml
source/game.database.bmx
source/game.newsagency.base.bmx
source/game.person.base.bmx
source/game.person.bmx
source/game.production.productionmanager.bmx
source/game.programmeproducer.bmx

Die Frage wäre, ob zusätzlich das Filtern in person.base erweitert werden sollte:
Die Producer nutzen nicht die castable-Filter, was zur Folge hat, dass zwar auf bookable geprüft wird, aber wenn alle bookable aber nicht castable sind, rutschen eben trotzdem  ungewollte Einträge durch.
Eine Erweiterung wäre ggf. ohnehin besser, da mit dieser Änderung nur neue Spiele repariert werden. In alten Spielständen haben die Personen ja schon das falsche Flag.
closes #1111

Bug bezüglich bookable-Flag; Report scr0llbaer

---

res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/ai/DefaultAIPlayer/TaskStationMap.lua
source/game.ai.bmx
source/game.stationmap.bmx

Für den eigentlichen Kauf von Antennen und Vertragsabschlüsse müssen noch Api-Änderungen vorgenommen werden. Um zu verhindern, dass an derselben Stelle mehrere Antenne gebaut werden, wird "extern" geprüft, dass es dort nicht schon eine Antenne gibt.

Anpassung Lua an neue Kartenlogik

---

source/game.screen.programmeplanner.bmx

This fix cleans up the code handling "shortcut-copies/episode creation":
- less often executed
- at the right moment executed (before even dragging, or once we finished dropping)
- removing unused variables which just existed because of lacking events we now have
As result this corrects the behaviour when using the shortcuts on an "daychange" programme (starting a day earlier and ending the other day).
Fixes #1120

Fix: [Programmeplanner] Fix shortcut-helpers and daychange programme

---

config/gamesettings/default.xml
source/game.stationmap.bmx

Initialvorschlag für die Kostenanpassung
* laufende Kosten richten sich ausschließlich nach Receiver (sonst entsteht eine zu große Diskrepanz, wenn die Coverage der Antennen stark fällt); dafür können die laufenden Kosten stärker ansteigen
* die Kaufkosten enthalten einen wesentlich geringeren Anteil für die Bevölkerung (sonst werden die Kaufkosten bei sehr späten Startjahren verhältnismäßig zu teuer)
closes #1128

Anpassung Antennenkosten nach Kartenumstellung

---

source/game.database.bmx

closes #1145
* korrekte(re) Übernahme der Werte für Charisma, Humoer etc. für Personen
* Anpassung der gewürfelten Minimal- und Maximalwerte bei Vorhandensein von Datenbankwerten
* 0 in der Datenbank wird nur für "_min" interpretiert, ansonsten als fehlender Wert (zu viele Attribute in der Datenbank stehen auf 0)

Definition Personenattribute; Report Klotz am Bein

---

source/game.screen.programmeplanner.bmx

Wird an Tag x ein Live-Programm veröffentlicht, werden zunächst alle Slots rot markiert und anschließend die Slots ab der Veröffentlichung grün (live) markiert oder die Markierung entfernt. Endet das Live-Programm aber am nächsten Tag (0 Uhr oder 1 Uhr etc), wurden alle Slots ab diesem Zeitpunkt wieder entmarkiert (aber eben am falschen Tag)...
closes #1151

Reparatur Programmplanermarkierung; Report scr0llbaer

---

source/Dig/base.util.persongenerator.bmx

Wie bereits kommuniziert habe ich die Aenderungen aus dem PR #1161 extrahiert ... und nun gleich nochmals ueberarbeitet.
Vorher: Vornamen statt Familiennamen (doppelter Array)
Nun: (geschlechtsspezifische) Endungen vom Familiennamen werden entfernt und mit dem passenden (geschlechtsspezifischen) Ersatz ergaenzt.
Der Fallback ist die Nutzung des Patronyms (der "maennlichen Variante").
Testausgabe:
```
country: gr
* first names: 204 x female, 210 x male
* last names: 143 x
* male:
Ippokrátis Papandréos
Adrianós Xenákis
Apollonios Koútras
Erotókritos Oikónomos
Agápios Kefalogiánnis
Dionýsios Skoúfis
Spyrídon Perákis
Valentínos Karamanlís
Léandros Stélios
Marínos Georgíos
Anastásios Nikólos
* female:
Melína Karamanlí
Charalambía Bakópoulou
Anárgiri Fotiádi
Dáfni Makrí
Evgenía Elía
Christína …
```

Fix: [Dig] Correct family names for Greek person names

---

source/main.bmx

Mit #1167 sind nicht alle Call-In-Programme automatisch verfügbar (released). Wenn sie allerdings in einem früheren Spielstand kein explizites Veröffentlichungsdatum hatten (-1) wären sie nun grundsätzlich nicht mehr auswählbar.
Mit dieser Datenbankreparatur bekommen solche Einträge 0 Veröffentlichungszeit und fallen damit unter "released".

Spielstandreparatur Call-In

---

source/game.programme.programmelicence.bmx

Für Vergleiche von Programmen kann der Preis pro Block interessant sein. Insb. bei Serien müssen ja auch nicht alle Folgen dieselbe Länge haben. Daher der Vorschlag bei shift den Preis pro Block anzuzeigen (analog Prämie pro Block bei Werbung).

Datenblatt: Anzeige Preis pro Block

---

source/main.bmx

* Dateiname autosave_autosave vermeiden
* Fast-Forward nach Laden eines Autosave vermeiden
(Wenn man selbst explizit einen Spielstand speichert macht man das zu einem Zeitpunkt, bei dem man die Spielgeschwindigkeit unter Kontrolle hatte. Autosave passiert mit hoher Wahrscheinlichkeit bei einem Fast-Forward-Raumwechsel. Daher sollte beim Laden des Spiels die Geschwindigkeit runtergesetzt werden.)

Verbesserung Autosave; Report bol

---

source/game.production.bmx
source/game.screen.programmeplanner.bmx

Mehrfachproduktionen werden anders als Serien behandelt (kein Container). Daher kann man im Programmplaner auch nicht sofort mit shift die nächste "Folge" planen.
Ich habe mit den Bestandsdaten keine Möglichkeit gefunden, Lizenzen, die aus demselben Script entstanden sind, zu extrahieren (Ansatz Counter aus Titel rausschneiden habe ich nicht verfolgt). Daher habe ich die script-ID an die Programmdaten gepackt und hole bei shift alle Lizenzen derselben ID und "kopiere" die mit dem nächsten Veröffentlichungsdatum.

Nächstes Element einer Mehrfachproduktion bei shift anbieten

---

source/game.programme.newsevent.template.bmx

Mit der Umstellung der Expressions muss auch die Heuristik für "komplexe" Nachrichtenverfügbarkeit umgestellt werden (&&->.and)

Anpassung Heuristik Nachrichteverfügbarkeit

---

res/database/Default/database_scripts.xml
res/database/Default/user/eggi_screenplays_adaptations.xml
res/database/Default/user/scr0llbaer.xml
res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
res/database/Default/user/stukov_scripts_adaptations.xml
source/game.database.bmx
source/game.gamescriptexpression.bmx

closes #1203
Anpassung der Datenbank, des Reparaturcodes und des Zugriffs via Index.
Nicht repariert wären die Spielstände, die mit der Discord-Snapshot erstellt wurden, da dort ja der falsche Index gesetzt wurde. Das ließe sich nur beheben, wenn man jetzt nochmal die Datenbankversion hochsetzt und eine Indexersetzung in der neuen Rollensyntax macht.

Rollenreferenzen jobindexbasiert machen

---

res/database/Default/lang/de.xml
res/database/Default/lang/en.xml
res/database/Default/lang/pl.xml
res/database/Default/lang_original/de.xml
res/database/Default/lang_original/en.xml
res/database/Default/lang_original/pl.xml
source/game.database.bmx

Umsetzung der vorgeschlagenen Umbenennung von roles nach programmeroles. Fallback im Datenbankeinlesecode ist ergänzt.

Umbenennung roles in lang-Dateien

---

source/game.production.script.bmx

Der auskommentierte Code für unverwendete Titel wurde entfernt. Ob Title mit Counter genutzt werden, wird noch außerhalb der Methode geprüft. Die Schleife ist auch nicht (mehr) nötig (immer nur ein Durchlauf).
Ergänzt wurde, dass nicht nur die übergebenen Template-IDs (gerade in Agentur angeboten) ignoriert werden, sondern auch die von aktuell im Pool befindlichen Drehbüchern. Ohne diese Prüfung kann dieselbe Vorlage dann trotzdem zweimal im Pool existieren und dann doppelt in der Agentur angeboten werden.

Aufräumen Erzeugung zufälliges Drehbuch

---

source/game.broadcastmaterial.advertisement.bmx
source/game.programme.adcontract.bmx

closes #1208
Der Code für die Prüfung wurde von Advertisement nach AdContract verschoben, da der Großteil der Prüfungen ohnehin am Vertrag stattfindet. Auf diese Weise würden auch weitere Einschränkugnen (verbotene Genre siehe #1200) automatisch im Datenblatt abgehandelt werden und müssten nicht gesondert geprüft werden.

Indikator, wenn aktuelle Sendung Genre-Anforderungen nicht erfüllt

---

source/Dig/base.util.scriptexpression_ng.bmx

see #1212
Bevor ich richtig anfange, möchte ich sicherstellen, dass die Richtung stimmt.
Als ersten Punkt würde ich gern für alle Vergleichsfunktionen die Kurzschreibweisen einführen:
* .cmp:param1:param2 liefert boolen wie bisher
* .comp:param1:param2:resultTrue:resultFalse liefert je nach Vergleich das erste oder zweite Ergebnis
Eine andere Parameterzahl führt zu einem Fehler. Damit könnten einfache Verzeigungen weniger aufwändig geschrieben werden. Und das Verhalten ist "offensichtlich" (keine impliziten Defaults).
Um das einheitlich zu gestalten würde ich gern .eq und .neq semantisch ändern, da ich die akutelle Implementierung auch eher für einen seltenen Sonderfall halte. Aktuell kann .eq beliebig viele Parameter bekommen und ist "true" genau dann wenn alle gleich sind - es ist also …

Erweiterung der Vergleichsoperatoren

---

source/game.database.bmx

"all" als unterstützes Sprach-Tag

---

res/database/Default/database_ads.xml
res/database/Default/user/scr0llbaer_ads.xml
res/database/Default/user/stukov_ads.xml
source/game.database.bmx
source/game.programme.adcontract.bmx

see #1200 
Bislang können Einschränkungen für Programmtypen bei Werbeverträgen konfiguriert werden (erlaubt/verboten). Das wurde aber bislang nicht ausgewertet.
Wie im Ticket beschrieben würde ich zunächst die Felder, die nicht unterstützt werden sollen entfernen (Editor/Dokumentation).

Keine Einschränkung für Programmtyp in Werbeverträgen

---

res/database/Default/database_news.xml
res/database/Default/database_programmes_fictional.xml
res/database/Default/database_scripts.xml
res/database/Default/user/ariksan.xml
res/database/Default/user/cujo.xml
res/database/Default/user/eggi_screenplays_adaptations.xml
res/database/Default/user/kasi.xml
res/database/Default/user/kieferer.xml
res/database/Default/user/nichtdiebetty.xml
res/database/Default/user/ronny.xml
res/database/Default/user/scr0llbaer.xml
res/database/Default/user/scr0llbaer_news.xml
res/database/Default/user/scr0llbaer_screenplays_adaptations.xml
res/database/Default/user/speedminister.xml
res/database/Default/user/stukov_ads.xml
res/database/Default/user/stukov_scripts_adaptations.xml
res/database/Default/user/therob.xml

WIP: I have started cleaning up variables either using the all-languages tag or turning variables to global ones. The first commit contains changes in the user databases. I have not dealt with all cases because I need feedback for the general pattern
* ads - very often the names are identical in all languages (and we don't have variables, yet; should ad names be "global" in general or rather get the same value in each language?
* programme and script template (original) titles without variables - if they are identical in all languages, turn them into global titles or rather all-languages
Edit: The general pattern (I tried to follow)
* randomcity -> global
* worldtime -> global
* contains variable or role reference -> all (role localization)
* identical fixed values -> global

Datenbankbereinigung localized string

---

source/Dig/base.util.localization.bmx
source/game.programme.programmedata.specials.bmx
source/game.programmeproducer.sport.bmx

see #1223 
UCFirstAllEntries schien Ursache zu sein. Nahm man die Aufrufe raus, passten die Texte. Ich vermute unerwünschte Seiteneffekte beim set+get+cache+Defaultwerte.
Die Hilfsmethode sollte überhaupt nur die existierenden Einträge anpassen.

Reparatur kaputte Match-Texte

---

res/database/Default/database_achievements.xml

Blockbuster-Erfolg in Bronze, Silber und Gold mit steigenden Einschaltquoten für mehr Blöcke zur Primetime.
closes #1202

Erfolg Blockbuster

---

res/database/Default/lang/de.xml
res/database/Default/lang/en.xml
res/database/Default/lang/pl.xml
source/game.database.bmx
source/game.database.localizer.bmx
source/game.gameinformation.bmx
source/game.gamescriptexpression.bmx
source/main.bmx

see #1181 
Zunächst als Proof of concept für das Einlesen (noch ohne Auswertung in den Expressions) zur Diskussion. Ich denke, dass GameInformation der falsche Platz ist. Der generische Ansatz mit den Providern macht es unnötig schwer, da die Maps von Hand (de)serialisiert werden müssen.
Aber wo könnte man die Map mit den Sprachen sonst hinpacken, ohne zu sehr an den Laden/Speichern-Code ran zu müssen?

Globale Variablen in der Datenbank

---

source/game.award.culture.bmx
source/game.award.customproduction.bmx
source/game.betty.bmx
source/game.modifier.base.bmx
source/game.player.finance.bmx
source/game.popularity.bmx
source/game.popularity.person.bmx
source/game.production.scripttemplate.bmx
source/game.programme.newsevent.bmx
source/game.programme.programmelicence.bmx

see #1201 
Idee des Ansatzes ist, dass der Delay zentral von der Basisklasse verwaltet werden kann. Dazu wird beim ersten Update-Aufruf die Zeitverzögerung gesetzt.
Alle Modifiersubtypen implementieren ihre eigene init-Methode, rufen aber nicht alle super.init auf. Daher setze ich data explizit in den Subtypen, für die ich eine zeitverzögerte Ausführung für sinnvoll halte. Ggf. kann man das Setzen noch einschränken (wenn "time"-Attribut vorhanden).
Ausprobiert habe ich das ganze mit einem modifyScriptAvailability (2 Effekte - einmal sofort auf disable setzen, einnmal mit Verzögerung auf enable setzen und Ausgabe der Änderung im run).
Zu klären wäre zunächst der Ansatz an sich.

zeitverzögerte Effekte

---

source/game.gamescriptexpression.bmx

Der Ansatz mit HasVariable schlägt für Kindelemente fehl. Die Variable ist nicht enthalten, kann aber dennoch aufgelöst werden.
see #1244

Reparatur Variablenauflösung

---

source/game.modifier.base.bmx
source/game.production.bmx

see #1177 
Vorschlag:
* neuer Effekttrigger bei Produktionsstart
* API-Änderung für Rückgabewert bei RemoveOrphans - statt zurückzugeben, ob etwas gelöscht wurde, lieber zurückgeben, ob noch etwas übrig ist

Effekt für Produktionsstart

---

source/game.betty.bmx

closes #1169 
Neben dem Flag und den umgesetzten Effekten, mit denen Betty-Punkte vergeben werden können, erlauben die Modifier über die Datenbank zusätzlich auf die Punktberechnung Einfluss zu nehmen
* Definition einer absoluten Änderung pro Ausstrahlung (kein Einfluss der Aktualität)
* Definition der zugrundliegen Programmqualität
* Definition eines Faktors
Damit ist es auch möglich für Nichtkulturprogramme "Überraschungspunkte" zu verteilen.

Unterstützung Betty-Modifier

---

source/game.database.localizer.bmx
source/game.gamescriptexpression.bmx

Proof of concept für #1246
Ich würde ungern Personen und Rollen mit LocalizedStrings versehen (an sich und es persönlich machen zu müssen). Um die Lesbarkeit des gameexpressions-codes in den case-Fällen hoch zu halten, würde ich für die einzelnen Attribute lokale getter bauen, die zunächst prüfen ob eine Lokalisierung existiert.
(Statt direkt die structs zurückzugeben, könnte man natürlich auch reduzierte PersonBase-Objekte in die Cache-Map des DatabaseLocalizers packen. Dann spart man sich das Zusammenbauen von fullname etc.
Vor dem Ausimplementieren wollte ich den Ansatz abnicken lassen.

Reparatur Personenlokalisierung

---

source/game.player.finance.bmx

Das Kaufen neuer Nachrichten erfolgt vergleichsweise häufig und das Logging über die Beträge bietet wenig Mehrwert. Daher würde ich dieses Logging standardmäßig rausnehmen wollen.

Redutzierung Logging

---

source/game.world.worldtime.bmx

closes #1257 
Für den Typ 5 (Zeitspanne zwischen zwei realen Datumsangaben) sollen Jahr, Monat und Tag nicht separat betrachtet werden
1985,1986,12,1,24,5 sollte wirklich zwischen 24.12.1985 und 5.1.1986 liegen.
Ein ähnliches Problem könnte bei der Zeitberechnung für Spieltage bestehen (Jahr a-b, Spieltag c-d, Stunde e-f, Minute g-h).
Auch hier sind unterschiedliche Interpretationen möglich: Werte separat betrachten oder eine echte Zeitspanne defnineren - oder aber eine Kombination. Denn mindestens bei der Zeit (Stunde/Minute), könnte man ja erreichen wollen, dass etwas morgens oder abends passiert, egal welcher Tag gewürfelt wurde.
In der Dokumentation wird aktuell die Interpretation zwischen zwei Zeitstempeln beschrieben (wie sie für Typ 6 und 7 aktuell *nicht* umgesetzt ist). In der …

Reparatur Zeitberechnung Typ 5

---

source/Dig/base.gfx.bitmapfont.bmx

I don't intend to contribute to code in the future, only this little thing for now.
I compiled and tried, the inch (`″`) and the one-third (`⅓`) chars are working now when they appear in the content. However, the Phi symbol and the Heart symbol is not. But maybe the problem is on my end (something with system font)?

Support for inch, one-third and possibly other chars

---

source/game.database.bmx
source/game.person.base.bmx
source/game.production.productionconcept.bmx
source/game.production.scripttemplate.bmx
source/game.screen.supermarket.production.bmx

closes #1065
Erster Durchstich für das Definieren von Besetzungen in einer Drehbuchvorlage.
* Definition eines Attributs (person - Diskussionsgrundlage) in der Datenbank (GUID oder Variable, die zu einer GUID ausgewertet wird) - aktuell wird nur eine feste GUID unterstützt
* konkrete Person wird beim Erstellen des Drehbuchs/Konzepts ermittelt und weitergegeben
* Im Supermarkt kann der Slot nicht verändert werden und ist ausgegraut
* Für Texte im Script würde ich die Expressionauswertung nicht ändern. Stattdessen würde man mit dem normalen .person arbeiten und die GUID aus einer Variable ziehen, die sowohl für den Text als auch für die Cast-Vorauswahl verwendet wird. Auf die Weise sollte die Definition konsistent sein, weil man eben nicht cast verwenden kann und hoffen, dass final auch der …

Unterstützung vorausgewählter Besetzung

---

source/game.programme.newsevent.bmx
source/main.bmx

* Thread-Protection auch beim Erstellen von Nachfolgenachrichten
* Altnachrichten nicht jede Stunde aufräumen (die Methode arbeitet ohnehin nur auch Tagesbasis)
* fix News-History-Index (wenn das Array gekürzt wird, sollte auch der Index angepasst werden; im Debugscreen wurde nach 100 Nachrichten nur noch eine statt 4 angezeigt)

Nacharbeiten Nachrichtenrefactoring

---

source/game.production.script.bmx

Die Logik die ermittelt, ob der Produkttyp mit angezeigt werden muss, hatte einen Fehler. Der Produkttyp Reportage wurde angezeigt, obwohl er zum Genre Boulevard passte.
Außerdem ist in dem Fall vielleicht verwirren, dass die Trennung durch Schrägstrich erfolgt.
Vorschlag: Produkttyp wird in Klammern angezeigt und sieht daher deutlich anders aus als eine Genrebezeichnung.
Weiterhin wurden für Filme (zumnindest bis zu 2) Untergenre in die Anzeige aufgenommen, da es verwirrend sein kann, wenn in der finalen Lizenz plötzlich Genre dazukommen.

Reparatur und Verbesserung Genreanzeige für Drehbücher; Report Rauxelerritter

---

source/game.player.programmeplan.bmx
source/game.production.bmx

see #1295 
Zu prüfen wäre, ob der folgende Ansatz tragbar wäre.
* Live-Produktionen enden schon x:50 statt x:55, damit das tradeable-Flag gesetzt wird, bevor die Prüfung für das Entfernen einer Lizenz x:54 stattfindet
* Es wird ja zwischen Entfernen und Verkaufen beim Erreichen des Limits unterschieden. Beim Entfernen wird nicht mehr auf das tradeable-Flag geachtet, die Lizenz wird einfach entfernt
Es kann nun aber folgendes Verhalten auftreten.
* Serie mit 2 Folgen
* Folge 1 produziert und gesendet
* Limit erreicht, Serie verschwindet
* Folge 2 produziert
* Serie erscheint wieder (Header hat aber vermutlich den falschen Owner)
* Folge 2 gesendet, Limit erreicht, Serie verschwindet wieder
Das sichtbare Ergebnis scheint erstmal wie gewünscht zu sein - wenn das Limit aller Folgen erreicht …

Live-Serien und Broadcastlimit; Report Rauxelerritter

---

source/game.production.productionconcept.bmx
source/game.production.script.bmx
source/game.roomhandler.studio.bmx

Ich plädiere für eine grundsätzliche Anpassung der Genre-Fit-Berechnung. Outcome sollte komplett aus der Wertung genommen werden. Die Zuschauerwertung ist ein Ergebnis (und kein Parameter) der Gesamtgüte.
Ich verstehe zwar die Idee, mit den (hinterlegten und dem Drehbuch verglichenen) Werten genrespezifische Clichés einfangen zu wolllen, aber im Gesamtpaket funktioniert das aktuell nicht gut. Bei der Berechnung der Zuschauerzahlen wird einfach wieder eine gewichtete Summe über Speed, Critics etc. gebildet. D.h. den höchsten Wert erreicht man nicht, indem die Lizenz am nächsten an der Verteilung bezüglich der Genredefinition ist, sondern indem all diese Werte bei 100% liegen.
Ohne einen grundsätzlichen Umbau (z.B. für Lizenzen nur noch Qualität und Zuschauerwertung) wäre mein Vorschlag, …

Anpassung Genre-Fit-Berechnung

---

source/game.production.bmx
source/game.production.productionconcept.bmx
source/game.roomhandler.studio.bmx

see #1285 
Aktuell wird (nur) eine gewichtete Summe der vergebenen Punkte ins Verhältnis zur möglichen Gesamtpunktzahl verwendet um die Verteilung der Fokuspunkte zu bewerten. Das halte ich für zu kurz gegriffen. Einerseits wird damit gar keine "gute Verteilung" belohnt, weil man einfach möglichst viele Punkte für höher gewichtete Attribute vergeben muss, andererseits werden teure Produktionen doppelt belohnt einfach weil sie teuer waren.
Vorschlag ist, tatsächlich die Verteilung auf die unterschiedlichen Kategorien zu bewerten (und zwar in Abhängigkeit der Anzahl der Punkte, die mit der Produktionsfirma überhaupt vergeben werden können). Grundidee ist, dass man aufgrund der Gewichtung der Attribute ermittelt wie viele Punkte pro Kategorie "für ein optimales Ergebnis" zu erwarten wären. …

Auswertung der Fokuspunkte für die Qualität einer Produktion

---

source/game.roomhandler.base.bmx

Allow concurrent room event handling by no longer using a global which is potentially manipulated from concurrently happening events (room draw/update + figure enters/leaves rooms etc). They could possible (and actually did) override the global ...leading to issues (null access or wrong room handler being asked!)
The concurrent access happened if a different Thread created corresponding events. Example: AI sends their figure to somewhere, this leading to "tryleaveroom" ...
Affects #1311

Fix: [Rooms] Allow concurrent room-event handling

---

source/game.misc.roomboardsign.bmx
source/game.newsagency.base.bmx

closes #1316 
Umstellung der Prüfung, welche Nachricht verwendet werden soll auf den String mit den ermittelten Sendern. Die Ermittlung der Beteiligten scheint aber auch noch Probleme zu haben. In Testpielen gab es zum Teil Explosionen in Spielerräumen, aber kein einziger Spieler war am Umhängen der Schilder beteiligt (ich meine nicht, dass die finale Nachricht so lautete, sondern dass der übergebene Wert im Event sagte, dass kein Spieler das Schild umgehängt hätte).

Reparatur fehlende Sendernamen bei Nachrichten mit Ermittlungserfolg; Report scr0llbaer

---

source/game.roomhandler.office.bmx

Dalli suggested per Discord to only show unread messages on the desk.
I adjusted values - and also fixed an issue that the old code counted ALL messages regardless of owner.

[Office] Only show unread messages on desk. Idea: Dalli

---

source/Dig/base.util.string.bmx

see #1322
Bei Verwendung der Übersetzung stürzt das Spiel sofort ab, weil für nichtleere Strings mit unbekannten Zeichen der Index für FirstUpper nicht ermittelt werden kann.

Absturz wegen unbekannter Zeichen verhindern

---

source/game.betty.bmx
source/game.gamerules.bmx
source/game.roomhandler.betty.bmx

Die Bedingung für den Generalschlüssel war bisher ein Bettywert von 75%. Obwohl da vielleicht realistisch ist, bedeutet das für das Spiel, dass der Schlüssel keine Rolle spielt, da der Wert erst sehr spät erreicht werden kann.
Die geänderte Bedingung, setzt den Wert runter und macht ihn zusätzlich abhängig von den überreichten Geschenken.

Bedingung für Generalschlüssel

---

source/game.person.base.bmx

fixes #1333 
Beim Übertragen der Filtereigenschaften sind zwei Attribute in der Reihenfolge vertauscht worden.

Reparatur Personenfilter

---

source/main.bmx

Im Testspiel mit deaktivierten Spielern aufgefallen. Ohne die Anpassung kommt die Toastnachricht nicht nur für den eigenen Chef sondern auch die Chefs der anderen Spieler.

Nachricht, dass Chef ruft nur für menschlichen Spieler

---

res/ai/DefaultAIPlayer/TaskAdAgency.lua
res/database/Default/user/stukov_ads.xml
res/lang/advertisement/advertisement_de.txt
res/lang/advertisement/advertisement_en.txt
res/lang/advertisement/advertisement_es.txt
res/lang/advertisement/advertisement_fr.txt
res/lang/advertisement/advertisement_pl.txt
res/lang/advertisement/advertisement_pt-br.txt
res/lang/advertisement/advertisement_tr.txt
source/game.database.bmx
source/game.ingameinterface.bmx
source/game.programme.adcontract.bmx
source/main.bmx

closes #1200 
* verbotene Flags werden nun ausgewertet
* Bestandswerbung angepasst (Kult kann nicht erkannt werden, sollte als Flag also nicht gefordert/verboten werden)

Verbotene Programmflags bei Werbung auswerten

---

source/Dig/base.sfx.soundmanager.base.bmx

AdjustSettings() requires an existing channel, so ensure one exists before adjusting.
forceVolume did not multiply with the sfxVolume and thus was constant "forceVolume"

Fix: [Dig] fix sfxVolume issues (channels and forcedVolume)

---

source/game.broadcastmaterialsource.base.bmx
source/game.ingameinterface.bmx
source/game.programme.programmedata.bmx
source/game.programme.programmelicence.bmx

* image-Verzeichnis im Haupverzeichnis kann (korrekt skalierte) Bilder enthalten
* png und jpg
* fertige Programme, Werbung, Eigenproduktionen
* Name muss Konvention entsprechen (Werbung - GUID aus DB, Eigenproduktionen - GUID der Drehbuchvorlage aus DB, Programme - "data-"+GUID aus DB)
* Für Serien können Einzelfolgen spezifische Bilder haben, ansonsten Fallback auf GUID des Haupteintrags
* Für Programme erfolgt ein Caching des Bilds für die Zeit der Ausstrahlung, für Werbung wird das Bild dauerhaft gespeichert (Werbung kommt immer wieder und wesentlich weniger Einträge)
closes #1140

Unterstützung programmabhängiger Bilder

---

source/game.roomhandler.movieagency.bmx

In längeren Testspielen ist mir aufgefallen, dass z.T. Jahre alte Sportübertragungen bei den Auktionen dabei waren. Der zusätzliche Filter stellt sicher, dass keine Live-On-Tape-Lizenzen im Angebot landen.

Keine alten Live-Programme als Auktion

---

source/game.programme.programmedata.bmx

Ich denke, es gibt einen schwerwiegenden Fehler in der Qualitätsberechnung. Problem 1 ist, dass das Alter mehrfach in die Berechnung eingeht - einerseits durch den Einfluss auf die MaxTopicality, andererseits als direkter Faktor siehe Commit). Problem 2 ist, dass der direkte Faktor "falsch" ermittelt wird. Bei Alter 1 ist er nämlich nicht 1 wie im Kommentar impliziert sondern 1.5. Warum ist das schlecht? Weil die Gesamtqualität zwischen 0 und 1 liegen muss. Ein komplett neuer Film, dessen Attribute alle 1 sind, hat genauso die Qualität 1 wie ein Film, dessen Attribute 0.8 sind.
Von dem Faktor 1.5 profitieren natürlich insbesondere neue Filme schlechter Qualtität. Eine Reduktion des Faktors auf einen Wert zwischen x und 1 hätte einen riesigen Einfluss auf die Quotenberechnung.
Mögliches …

Einfluss Alter auf Qualität
